### ISSUE TITLE
mac os 7.0.0-beta.5 语言字幕没有显示

### ISSUE THREAD

**Issue by Wei98** [poooi/poi#1149]

**Comment by KochiyaOcean** [comment]
cc @grzhan
烦请提供更加详细的信息，比如开发者工具报错等

**Comment by Wei98** [comment]
开发者工具没有报错，只是字幕没显示而已

**Comment by grzhan** [comment]
@Wei98 插件存在与 POI 7.0.0 的兼容问题，现在已尝试修复，请把插件升级到新版本(0.4.2)看问题是否解决。

如果问题没解决，请尝试删除  `~/Library/Application Support/poi` 下的 `poi-plugin-subtitle` 文件夹并重启 POI

**Comment by Wei98** [comment]
更新和删除重启都不行

**Comment by grzhan** [comment]
@Wei98 之前在 7.0 之前的版本（如 6.3）插件是否能正常使用？

打开 ` ~/Library/Application Support/poi/poi-plugin-subtitle/i18n` 看看是否有 `zh-CN.json` 等缓存字幕文件

**Comment by Wei98** [comment]
在之前的版本插件都能正常使用，在7.0beta.3时也能正常使用，只是突然有天就没显示了，之后的beta.4和beta.5都没显示，现在换回6.3版本也没有显示，zh-CN.json 等缓存字幕文件都有在文件夹

**Comment by qdb99581** [comment]
似乎不少人有這問題  我照著你說的把subtitle文件夾刪除後 重新安裝插件後在用文字文件打開zh-CN.json或zh-TW.json都出現以下文字

{
	"Subtitle Miss": "本【%s】的台词字幕缺失的说，来舰娘百科（http://zh.kcwiki.moe/）帮助我们补全台词吧！",
	"Update Success": "语音字幕数据更新成功",
	"Update Failed": "语音字幕自动更新失败，请联系有关开发人员，并手动更新插件以更新字幕数据",
	"KCwiki Quotes Subtitle": "kcwiki语音字幕",
	"Subtitle of ship girl's quotes (supported by kcwiki)": "语音字幕插件（舰娘百科支持）"
}

**Comment by grzhan** [comment]
@qdb99581 感谢反馈出错信息，目前插件在 POI 7.0.0 运行确实存在问题。

原因 POI 7.0.0 中 Bluebird 异步 coroutine 返回结果不同用户间似乎存在差异。

主要体现在 File IO 有关函数：

以`readFileAsync`为例：

```
yield fs.readFileAsync _path
```

其结果可能返回 `[Uint8Array[0]]`，也可能返回`[]` （……）

目前计划是对于文件 IO 暂时弃用 yield 异步写法，直接使用同步函数或者用 async/await 重写。

但 @Wei98 开发者工具没有返回出错信息，可能不是同个原因导致的错误。

**Comment by Wei98** [comment]
不好意思，之前没注意到，我的开发者工具也有返回出错信息
/Applications/poi.app/Contents/Resources/app.asar/views/services/utils.js:86 poi-plugin-kcwiki-report: No translate file found.
/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/debuggability.js:804 Unhandled rejection TypeError: Cannot read property '0' of undefined
    at /Users/Wei/Library/Application Support/poi/plugins/node_modules/poi-plugin-subtitle/index.cjsx:91:44
    at undefined.next (native)
    at undefined.tryCatcher (/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:566:26)
    at Promise._settlePromise0 (/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:630:18)
    at /Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Applications/poi.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/ensure/file.js:14:28
    at FSReqWrap.cb [as oncomplete] (fs.js:251:19)
/Applications/poi.app/Contents/Resources/app.asar/views/services/update.js:36 Remote version: 6.3.3. Current version: v7.0.0-beta.5
/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/debuggability.js:804 Unhandled rejection TypeError: Cannot read property '0' of undefined
    at /Users/Wei/Library/Application Support/poi/plugins/node_modules/poi-plugin-subtitle/index.cjsx:91:44
    at undefined.next (native)
    at undefined.tryCatcher (/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:566:26)
    at Promise._settlePromise0 (/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:630:18)
    at /Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Applications/poi.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/ensure/file.js:14:28
    at FSReqWrap.cb [as oncomplete] (fs.js:251:19)
/Applications/poi.app/Contents/Resources/app.asar/views/env-parts/data-resolver.js:14 Performing garbage collection
2/Users/Wei/Library/Application Support/poi/plugins/node_modules/poi-plugin-subtitle/index.cjsx:303 Uncaught TypeError: Cannot read property '145' of undefined

**Comment by grzhan** [comment]
@Wei98 那问题和其他人是一样的，之后会尝试修复。

**Comment by grzhan** [comment]
@Wei98 @qdb99581 请将插件升级到 0.4.3-beta.0 。如果仍然有问题，请将错误信息反馈给我。

升级方法：在【扩展程序】的【高级设置】中勾选【检查 beta 版插件更新】选项，重启以检测更新。

或者在插件安装的输入框直接输入 `poi-plugin-subtitle@0.4.3-beta.0` 安装亦可

**Comment by qdb99581** [comment]
@grzhan 我的修好了 非常感謝! 辛苦了

**Comment by grzhan** [comment]
@qdb99581  多谢反馈， @Wei98 现在将插件直接升级到 0.4.3 亦可

**Comment by Wei98** [comment]
@grzhan 不好意思，今天有点忙，晚了回复，我更新了还是不行
2
/Applications/poi.app/Contents/Resources/app.asar/views/services/utils.js:86 poi-plugin-kcwiki-report: No translate file found.
/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/debuggability.js:804 Unhandled rejection SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at loadSubtitles (/Users/Wei/Library/Application Support/poi/plugins/node_modules/poi-plugin-subtitle/index.cjsx:94:17)
    at /Users/Wei/Library/Application Support/poi/plugins/node_modules/poi-plugin-subtitle/index.cjsx:144:25
    at undefined.next (native)
    at undefined.tryCatcher (/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/generators.js:97:49)
    at /Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/generators.js:197:15
    at initialize (/Users/Wei/Library/Application Support/poi/plugins/node_modules/poi-plugin-subtitle/index.cjsx:248:12)
    at Object.pluginDidLoad (/Users/Wei/Library/Application Support/poi/plugins/node_modules/poi-plugin-subtitle/index.cjsx:328:7)
    at postEnableProcess (/Applications/poi.app/Contents/Resources/app.asar/views/services/utils.js:279:14)
    at enablePlugin (/Applications/poi.app/Contents/Resources/app.asar/views/services/utils.js:201:12)
    at pluginPaths.map.pluginPath (/Applications/poi.app/Contents/Resources/app.asar/views/services/plugin-manager.js:143:42)
    at Array.map (native)
    at PluginManager.readPlugins (/Applications/poi.app/Contents/Resources/app.asar/views/services/plugin-manager.js:140:31)
    at PluginManager.getPlugins (/Applications/poi.app/Contents/Resources/app.asar/views/services/plugin-manager.js:243:19)
    at PluginManager.initialize (/Applications/poi.app/Contents/Resources/app.asar/views/services/plugin-manager.js:136:10)
    at Object.<anonymous> (/Applications/poi.app/Contents/Resources/app.asar/views/services/plugin-manager.js:424:15)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Applications/poi.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (/Applications/poi.app/Contents/Resources/app.asar/node_modules/coffee-react/lib/register.js:44:34)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/poi.app/Contents/Resources/app.asar/views/components/settings/parts/plugin-config.js:33:22)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Applications/poi.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (/Applications/poi.app/Contents/Resources/app.asar/node_modules/coffee-react/lib/register.js:44:34)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/poi.app/Contents/Resources/app.asar/views/components/settings/parts/index.js:14:21)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Applications/poi.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (/Applications/poi.app/Contents/Resources/app.asar/node_modules/coffee-react/lib/register.js:44:34)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/poi.app/Contents/Resources/app.asar/views/components/settings/index.js:19:14)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Applications/poi.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (/Applications/poi.app/Contents/Resources/app.asar/node_modules/coffee-react/lib/register.js:44:34)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/poi.app/Contents/Resources/app.asar/views/tabarea.js:36:17)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Applications/poi.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (/Applications/poi.app/Contents/Resources/app.asar/node_modules/coffee-react/lib/register.js:44:34)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/poi.app/Contents/Resources/app.asar/views/app.js:23:16)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Applications/poi.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (/Applications/poi.app/Contents/Resources/app.asar/node_modules/coffee-react/lib/register.js:44:34)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at file:///Applications/poi.app/Contents/Resources/app.asar/index.html:46:5
/Applications/poi.app/Contents/Resources/app.asar/views/services/update.js:36 Remote version: 6.3.3. Current version: v7.0.0-beta.6
/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/debuggability.js:804 Unhandled rejection SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at loadSubtitles (/Users/Wei/Library/Application Support/poi/plugins/node_modules/poi-plugin-subtitle/index.cjsx:94:17)
    at /Users/Wei/Library/Application Support/poi/plugins/node_modules/poi-plugin-subtitle/index.cjsx:144:25
    at undefined.next (native)
    at undefined.tryCatcher (/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/generators.js:97:49)
    at /Applications/poi.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/generators.js:197:15
    at initialize (/Users/Wei/Library/Application Support/poi/plugins/node_modules/poi-plugin-subtitle/index.cjsx:248:12)
    at handleGameResponse (/Users/Wei/Library/Application Support/poi/plugins/node_modules/poi-plugin-subtitle/index.cjsx:260:7)
    at parseResponses (/Applications/poi.app/Contents/Resources/app.asar/views/env-parts/data-resolver.js:114:10)
    at resolveResponses (/Applications/poi.app/Contents/Resources/app.asar/views/env-parts/data-resolver.js:125:7)
    at handleProxyGameOnResponse (/Applications/poi.app/Contents/Resources/app.asar/views/env-parts/data-resolver.js:138:7)
    at CallbacksRegistry.apply (/Applications/poi.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:54:39)
    at EventEmitter.<anonymous> (/Applications/poi.app/Contents/Resources/electron.asar/renderer/api/remote.js:241:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
2
/Users/Wei/Library/Application Support/poi/plugins/node_modules/poi-plugin-subtitle/index.cjsx:290 Uncaught TypeError: Cannot read property '145' of undefined

**Comment by grzhan** [comment]
似乎是缓存文件的解析出现了问题，能够将 `~/Library/Application Support/poi/poi-plugin-subtitle` 下的`zh-CN.json` 文件通过邮件发给我检查下吗（我的邮箱：envy518@gmail.com ）

此外发完邮件后可以尝试删除 `~/Library/Application Support/poi/poi-plugin-subtitle` 看问题是否解决

**Comment by Wei98** [comment]
@grzhan 已发，删除也无法解决

**Comment by Wei98** [comment]
@grzhan 已发，删除也无法解决

**Comment by grzhan** [comment]
@Wei98 查收下邮件

**Comment by Wei98** [comment]
我删除后成功了，谢谢
抱歉打扰了你这么久

**Comment by grzhan** [comment]
@Wei98 谢谢反馈，如果有问题可以继续提 issue 或者邮件联系我，
