### ISSUE TITLE
poi linux打不开一直白屏

### ISSUE THREAD

**Issue by Margular** [poooi/poi#1257]
**poi 版本 / poi version:**
7.1.0

**操作系统 / OS:**
kali linux rolling 2016.2

**详细描述 / Details:**
无论是deb安装还是7z解压运行都是一直白屏，啥反应都木有- -
关掉之后提示信息:

[ERROR] Error: Cannot find module './lib/window'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/home/cui/下载/linux-unpacked/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at BrowserWindow.mainWindow.on (/home/cui/下载/linux-unpacked/resources/app.asar/app.js:144:5)
    at emitOne (events.js:96:13)
    at BrowserWindow.emit (events.js:188:7)

**Comment by KochiyaOcean** [comment]
看起来是下载不完整

**Comment by Margular** [comment]
cui@margular:~/下载$ ls poi-7.1.0-linux-x64.7z -l --block-size=K
-rw-r--r-- 1 cui cui 39839K 11月 11 12:39 poi-7.1.0-linux-x64.7z

大小没错啊

**Comment by KagamiChan** [comment]
如果我没理解错的话，在 #1223 的时候是可以运行的，然后现在不能运行了……
不知道在不能运行之前有没有做过什么相关的操作？

**Comment by Margular** [comment]
我同学Ubuntu kylin运行没问题，难道是我系统的问题，我擦，我刚重装的kali

**Comment by Margular** [comment]
卧槽，我知道为什么了，我是WIN10 + Kali双系统，poi的缓存目录link到win下的，我换了挂载位置。。所以.config/poi这个文件夹废了，就打不开了。
