### ISSUE TITLE
新版本插件依然无效

### ISSUE THREAD

**Issue by ghost941941** [poooi/poi#1258]
**poi 版本 / poi version:** 7.2.0 beta 2&3

**操作系统 / OS:** win10

**插件名和版本 / Plugin name & version:** 海域血量 3.0.6 
*(如果这是一个关于插件的 issue / If this is an issue about plugin)*

**详细描述 / Details:** 还是显示“点击出击后才能显示数据”
*(建议提供开发者工具 Console 选项卡的截图 / A screenshot of developer tool console tab is welcome)*

**Comment by yukixz** [comment]
@ghost941941 本来就是这样的吧……

**Comment by KagamiChan** [comment]
是在母港界面点击 [出击] - [出击] 之后还是没有显示吗

**Comment by ghost941941** [comment]
是的，而且那个显示小地图的插件是未卜先知吗，似乎也无效

**Comment by KagamiChan** [comment]
请问能否提供开发者工具 console 选项卡的截图？游戏界面下方信息栏的左手第一个按钮就是开发者工具

**Comment by ghost941941** [comment]
Scheduling daily refresh at 331200000 (now 1478857422094)
Remote version: 7.1.0. Current version: v7.2.0-beta.2
http://203.104.209.55 http://203.104.209.55/kcsapi/api_get_member/mapinfo TypeError: Cannot read property 'api_area_id' of null
    at F:\win-ia32-unpacked\resources\app.asar\views\utils\tools.js:161:41
    at F:\win-ia32-unpacked\resources\app.asar\node_modules\lodash\lodash.js:4938:15
    at baseForOwn (F:\win-ia32-unpacked\resources\app.asar\node_modules\lodash\lodash.js:2988:24)
    at F:\win-ia32-unpacked\resources\app.asar\node_modules\lodash\lodash.js:4907:18
    at forEach (F:\win-ia32-unpacked\resources\app.asar\node_modules\lodash\lodash.js:9319:14)
    at compareUpdate (F:\win-ia32-unpacked\resources\app.asar\views\utils\tools.js:160:23)
    at F:\win-ia32-unpacked\resources\app.asar\views\utils\tools.js:161:18
    at arrayEach (F:\win-ia32-unpacked\resources\app.asar\node_modules\lodash\lodash.js:530:11)
    at forEach (F:\win-ia32-unpacked\resources\app.asar\node_modules\lodash\lodash.js:9319:14)
    at compareUpdate (F:\win-ia32-unpacked\resources\app.asar\views\utils\tools.js:160:23)
    at reducer (F:\win-ia32-unpacked\resources\app.asar\views\redux\info\airbase.js:20:38)
    at combination (F:\win-ia32-unpacked\resources\app.asar\node_modules\redux\lib\combineReducers.js:132:29)
    at F:\win-ia32-unpacked\resources\app.asar\node_modules\reduce-reducers\lib\index.js:13:14
    at Array.reduce (native)
    at F:\win-ia32-unpacked\resources\app.asar\node_modules\reduce-reducers\lib\index.js:12:21
    at combination (F:\win-ia32-unpacked\resources\app.asar\node_modules\redux\lib\combineReducers.js:132:29)
    at Object.dispatch (F:\win-ia32-unpacked\resources\app.asar\node_modules\redux\lib\createStore.js:179:22)
    at dispatch (F:\win-ia32-unpacked\resources\app.asar\node_modules\redux-batched-subscribe\lib\index.js:63:34)
    at F:\win-ia32-unpacked\resources\app.asar\node_modules\redux-thunk\lib\index.js:14:16
    at action (F:\win-ia32-unpacked\resources\app.asar\views\middlewares\promise-action.js:36:12)
    at parseResponses (F:\win-ia32-unpacked\resources\app.asar\views\env-parts\data-resolver.js:89:5)
    at resolveResponses (F:\win-ia32-unpacked\resources\app.asar\views\env-parts\data-resolver.js:112:7)
    at handleProxyGameOnResponse (F:\win-ia32-unpacked\resources\app.asar\views\env-parts\data-resolver.js:125:7)
    at CallbacksRegistry.apply (F:\win-ia32-unpacked\resources\electron.asar\common\api\callbacks-registry.js:54:39)
    at EventEmitter.<anonymous> (F:\win-ia32-unpacked\resources\electron.asar\renderer\api\remote.js:282:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)

这个吗，不好意思暂时没弄明白怎么上传图片 = =

**Comment by KochiyaOcean** [comment]
你海图的攻略情况如何（以及陆航

**Comment by KochiyaOcean** [comment]
关掉 poi 后删除 `%appdata%/poi/local storage` 再开看看
