### ISSUE TITLE
win10系统无法使用7.3.0版本poi

### ISSUE THREAD

**Issue by hakkaa** [poooi/poi#1346]
64位win10系统,打开poi后就无限连接,界面全黑
(7.2版本时也出现过,最终因为无法解决用了一段时间的kcv)
console界面为
C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\services\plugin-manager-utils.js:267 Error: Cannot find module 'remote'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\index.js:4:10)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at enablePlugin (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\services\plugin-manager-utils.js:260:31)
    at pluginPaths.map.pluginPath (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\services\plugin-manager.js:148:55)
    at Array.map (native)
    at PluginManager.readPlugins (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\services\plugin-manager.js:145:31)
    at PluginManager.getPlugins (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\services\plugin-manager.js:248:19)
    at PluginManager.initialize (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\services\plugin-manager.js:141:10)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\services\plugin-manager.js:451:15)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\components\settings\parts\plugin-config.js:45:22)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\components\settings\parts\index.js:14:21)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\components\settings\index.js:19:14)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\tabarea.js:38:17)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\app.js:23:16)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at file:///C:/Users/hakkaa/AppData/Local/poi/app-7.3.0/resources/app.asar/index.html:47:5enablePlugin @ C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\services\plugin-manager-utils.js:267
C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\services\plugin-manager-utils.js:267 Error: Cannot find module 'remote'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Roaming\poi\plugins\node_modules\poi-plugin-hensei-nikki\views\main.cjsx:9:12)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Roaming\poi\plugins\node_modules\poi-plugin-hensei-nikki\views\main.cjsx:151:4)
    at Module._compile (module.js:556:32)
    at Object.loadFile (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:15:17)
    at Module.load (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Roaming\poi\plugins\node_modules\poi-plugin-hensei-nikki\views\index.cjsx:3:11)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Roaming\poi\plugins\node_modules\poi-plugin-hensei-nikki\views\index.cjsx:6:4)
    at Module._compile (module.js:556:32)
    at Object.loadFile (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:15:17)
    at Module.load (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Roaming\poi\plugins\node_modules\poi-plugin-hensei-nikki\index.cjsx:13:10)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Roaming\poi\plugins\node_modules\poi-plugin-hensei-nikki\index.cjsx:402:4)
    at Module._compile (module.js:556:32)
    at Object.loadFile (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:15:17)
    at Module.load (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at enablePlugin (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\services\plugin-manager-utils.js:260:31)
    at pluginPaths.map.pluginPath (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\services\plugin-manager.js:148:55)
    at Array.map (native)
    at PluginManager.readPlugins (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\services\plugin-manager.js:145:31)
    at PluginManager.getPlugins (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\services\plugin-manager.js:248:19)
    at PluginManager.initialize (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\services\plugin-manager.js:141:10)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\services\plugin-manager.js:451:15)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\components\settings\parts\plugin-config.js:45:22)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\components\settings\parts\index.js:14:21)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\components\settings\index.js:19:14)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\tabarea.js:38:17)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\views\app.js:23:16)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\AppData\Local\poi\app-7.3.0\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at file:///C:/Users/hakkaa/AppData/Local/poi/app-7.3.0/resources/app.asar/index.html:47:5

**Comment by KagamiChan** [comment]
请问如果下载 https://npm.taobao.org/mirrors/poi/v7.4.0-beta.0/poi-7.4.0-beta.0-win-x64.7z 并解压到某个文件目录下再运行 poi 的话，是否也报同样的错误？

**Comment by hakkaa** [comment]
C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\services\plugin-manager-utils.js:274 Error: Cannot find module 'remote'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\index.js:4:10)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at enablePlugin (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\services\plugin-manager-utils.js:267:31)
    at pluginPaths.map.pluginPath (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\services\plugin-manager.js:148:55)
    at Array.map (native)
    at PluginManager.readPlugins (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\services\plugin-manager.js:145:31)
    at PluginManager.getPlugins (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\services\plugin-manager.js:249:19)
    at PluginManager.initialize (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\services\plugin-manager.js:141:10)
    at Object.<anonymous> (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\services\plugin-manager.js:452:15)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\components\settings\parts\plugin-config.js:45:22)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\components\settings\parts\index.js:14:21)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\components\settings\index.js:19:14)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\tabarea.js:38:17)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\app.js:23:16)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at file:///C:/Users/hakkaa/Desktop/poi-7.4.0-beta.0-win-x64/win-unpacked/resources/app.asar/index.html:47:5enablePlugin @ C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\services\plugin-manager-utils.js:274
C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\services\plugin-manager-utils.js:274 Error: Cannot find module 'remote'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Roaming\poi\plugins\node_modules\poi-plugin-hensei-nikki\views\main.cjsx:9:12)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Roaming\poi\plugins\node_modules\poi-plugin-hensei-nikki\views\main.cjsx:151:4)
    at Module._compile (module.js:556:32)
    at Object.loadFile (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:15:17)
    at Module.load (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Roaming\poi\plugins\node_modules\poi-plugin-hensei-nikki\views\index.cjsx:3:11)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Roaming\poi\plugins\node_modules\poi-plugin-hensei-nikki\views\index.cjsx:6:4)
    at Module._compile (module.js:556:32)
    at Object.loadFile (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:15:17)
    at Module.load (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Roaming\poi\plugins\node_modules\poi-plugin-hensei-nikki\index.cjsx:13:10)
    at Object.<anonymous> (C:\Users\hakkaa\AppData\Roaming\poi\plugins\node_modules\poi-plugin-hensei-nikki\index.cjsx:402:4)
    at Module._compile (module.js:556:32)
    at Object.loadFile (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:15:17)
    at Module.load (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at enablePlugin (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\services\plugin-manager-utils.js:267:31)
    at pluginPaths.map.pluginPath (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\services\plugin-manager.js:148:55)
    at Array.map (native)
    at PluginManager.readPlugins (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\services\plugin-manager.js:145:31)
    at PluginManager.getPlugins (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\services\plugin-manager.js:249:19)
    at PluginManager.initialize (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\services\plugin-manager.js:141:10)
    at Object.<anonymous> (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\services\plugin-manager.js:452:15)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\components\settings\parts\plugin-config.js:45:22)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\components\settings\parts\index.js:14:21)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\components\settings\index.js:19:14)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\tabarea.js:38:17)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\views\app.js:23:16)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (C:\Users\hakkaa\Desktop\poi-7.4.0-beta.0-win-x64\win-unpacked\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at file:///C:/Users/hakkaa/Desktop/poi-7.4.0-beta.0-win-x64/win-unpacked/resources/app.asar/index.html:47:5
看上去错误相同

**Comment by KagamiChan** [comment]
先试试把 `%appdata%/poi` 目录下的 `plugins` 目录删掉看看吧……
你是 32 位的系统，还是 64 位的？是原版系统还是某些修改版？
系统里安装了什么杀毒软件/安全软件吗？

**Comment by hakkaa** [comment]
64位,淘宝科技激活的win10企业版, windows defender

**Comment by hakkaa** [comment]
尝试中

**Comment by hakkaa** [comment]
貌似可以正常使用了,万分感谢dalao指教

**Comment by KagamiChan** [comment]
@hakkaa 作为对今后类似错误的一个参考，请问你大概是从哪一个版本升级到 7.2.0 的？

**Comment by hakkaa** [comment]
记得不太清楚了,貌似是6.3.3?

**Comment by KagamiChan** [comment]
@hakkaa 好的，多谢～
