### ISSUE TITLE
MAC POI 打开后除字幕栏其他信息不显示

### ISSUE THREAD

**Issue by KuZhu** [poooi/poi#1476]
poi 版本 / poi version: 7.7.0
操作系统 / OS:10.12.4

你遇到了什么样的问题 / The problem you've met: 打开后除了字幕栏显示语音字幕更新成功其他区块全部黑屏且无文字呈现。

有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:见附件中截图

Console 选项卡的截图不知什么原因上传不了所以直接复制黏贴了：
/Applications/poi.app/Contents/Resources/app.asar/views/redux/info/quests.js:533 Scheduling daily refresh at 331200000 (now 1495938008834)
2/Applications/poi.app/Contents/Resources/app.asar/views/services/plugin-manager-utils.js:163 poi-plugin-kcwiki-report: No translate file found.
updateI18n @ /Applications/poi.app/Contents/Resources/app.asar/views/services/plugin-manager-utils.js:163
/Applications/poi.app/Contents/Resources/app.asar/node_modules/i18n-2/i18n.js:23 Uncaught TypeError: Cannot read property 'length' of undefined
    at dotNotation (/Applications/poi.app/Contents/Resources/app.asar/node_modules/i18n-2/i18n.js:23:15)
    at module.exports.translate (/Applications/poi.app/Contents/Resources/app.asar/node_modules/i18n-2/i18n.js:340:10)
    at module.exports.__ (/Applications/poi.app/Contents/Resources/app.asar/node_modules/i18n-2/i18n.js:153:18)
    at Object.__ (/Users/Larry.Y/Library/Application Support/poi/plugins/node_modules/poi-plugin-translator/index.cjsx:51:49)
    at _react2.default.createElement.airbaseProps.map (/Applications/poi.app/Contents/Resources/app.asar/views/components/ship-parts/landbase-button.js:104:33)
    at Array.map (native)
    at exports.LandbaseButton (/Applications/poi.app/Contents/Resources/app.asar/views/components/ship-parts/landbase-button.js:93:18)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:309:14)
    at ReactCompositeComponentWrapper._constructComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:285:19)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:188:21)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:697:32)
    at ReactDOMComponent.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:697:32)
    at ReactDOMComponent.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:697:32)
    at ReactDOMComponent.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:697:32)
    at ReactDOMComponent.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:697:32)
    at ReactDOMComponent.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:697:32)
    at ReactDOMComponent.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:697:32)
    at ReactDOMComponent.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:697:32)
    at ReactDOMComponent.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:697:32)
    at ReactDOMComponent.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:697:32)
    at ReactDOMComponent.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:697:32)
    at ReactDOMComponent.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:697:32)
    at ReactDOMComponent.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:697:32)
    at ReactDOMComponent.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:697:32)
    at ReactDOMComponent.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createInitialChildren (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:697:32)
    at ReactDOMComponent.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at mountComponentIntoNode (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMount.js:104:32)
    at ReactReconcileTransaction.perform (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:140:20)
    at batchedMountComponentIntoNode (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMount.js:126:15)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.batchedUpdates (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at Object._renderNewRootComponent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMount.js:320:18)
    at Object._renderSubtreeIntoContainer (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMount.js:401:32)
    at Object.render (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactMount.js:422:23)
    at Object.<anonymous> (/Applications/poi.app/Contents/Resources/app.asar/views/app.js:76:20)
    at Object.<anonymous> (/Applications/poi.app/Contents/Resources/app.asar/views/app.js:84:3)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Applications/poi.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (/Applications/poi.app/Contents/Resources/app.asar/node_modules/coffee-react/lib/register.js:44:34)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at file:///Applications/poi.app/Contents/Resources/app.asar/index.html:49:5
/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponentTree.js:113 Uncaught TypeError: Cannot read property '__reactInternalInstance$afsztpksj5qbyflw0q9s02j4i' of null
    at Object.getClosestInstanceFromNode (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponentTree.js:113:11)
    at findParent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:38:32)
    at handleTopLevelImpl (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:67:28)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.batchedUpdates (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at dispatchEvent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:147:20)
/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponentTree.js:113 Uncaught TypeError: Cannot read property '__reactInternalInstance$afsztpksj5qbyflw0q9s02j4i' of null
    at Object.getClosestInstanceFromNode (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponentTree.js:113:11)
    at findParent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:38:32)
    at handleTopLevelImpl (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:67:28)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.batchedUpdates (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at dispatchEvent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:147:20)
/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponentTree.js:113 Uncaught TypeError: Cannot read property '__reactInternalInstance$afsztpksj5qbyflw0q9s02j4i' of null
    at Object.getClosestInstanceFromNode (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponentTree.js:113:11)
    at findParent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:38:32)
    at handleTopLevelImpl (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:67:28)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.batchedUpdates (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at dispatchEvent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:147:20)
/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponentTree.js:113 Uncaught TypeError: Cannot read property '__reactInternalInstance$afsztpksj5qbyflw0q9s02j4i' of null
    at Object.getClosestInstanceFromNode (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponentTree.js:113:11)
    at findParent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:38:32)
    at handleTopLevelImpl (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:67:28)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.batchedUpdates (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at dispatchEvent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:147:20)
/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponentTree.js:113 Uncaught TypeError: Cannot read property '__reactInternalInstance$afsztpksj5qbyflw0q9s02j4i' of null
    at Object.getClosestInstanceFromNode (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponentTree.js:113:11)
    at findParent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:38:32)
    at handleTopLevelImpl (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:67:28)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.batchedUpdates (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at dispatchEvent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:147:20)
/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponentTree.js:113 Uncaught TypeError: Cannot read property '__reactInternalInstance$afsztpksj5qbyflw0q9s02j4i' of null
    at Object.getClosestInstanceFromNode (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponentTree.js:113:11)
    at findParent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:38:32)
    at handleTopLevelImpl (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:67:28)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.batchedUpdates (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at dispatchEvent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:147:20)
/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponentTree.js:113 Uncaught TypeError: Cannot read property '__reactInternalInstance$afsztpksj5qbyflw0q9s02j4i' of null
    at Object.getClosestInstanceFromNode (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponentTree.js:113:11)
    at findParent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:38:32)
    at handleTopLevelImpl (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:67:28)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.batchedUpdates (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at dispatchEvent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:147:20)
/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponentTree.js:113 Uncaught TypeError: Cannot read property '__reactInternalInstance$afsztpksj5qbyflw0q9s02j4i' of null
    at Object.getClosestInstanceFromNode (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOMComponentTree.js:113:11)
    at findParent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:38:32)
    at handleTopLevelImpl (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:67:28)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.batchedUpdates (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at dispatchEvent (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactEventListener.js:147:20)
/Applications/poi.app/Contents/Resources/app.asar/views/env-parts/devtool-message.js:16 This is poi@v7.7.0 on darwin x64 with Electron@1.6.7, 
        PLUGINS: poi-plugin-prophet@6.6.3, poi-plugin-exp-calc@3.3.1, poi-plugin-expedition@3.1.0, poi-plugin-quest-info@3.2.3, poi-plugin-hensei-nikki@3.10.3, poi-plugin-senka-calc@4.3.1, poi-plugin-map-hp@3.0.6, poi-plugin-secretary@0.7.1, poi-plugin-almanac@1.2.1, poi-plugin-anchorage-repair@0.4.5, poi-plugin-akashic-records@6.0.3, poi-plugin-battle-detail@3.6.4, poi-plugin-wheres-my-fuel-gone@0.5.4, poi-plugin-item-improvement@4.0.0, poi-plugin-ship-info@2.5.1, ItemInfo@2.2.0, poi-plugin-k2badge@0.2.2, poi-plugin-new-window@2.7.2, poi-plugin-kcwiki-report@3.0.3, poi-plugin-report@3.2.4, poi-plugin-subtitle@0.5.9, poi-plugin-translator@0.8.1, 
        FCD: map@2017/05/04/01, maphp@2016/08/20/01, shiptag@2017/05/04/01

**Comment by KagamiChan** [comment]
在 terminal 内运行 `/Applications/poi.app/Contents/MacOS/poi -s`，之后应该就会回复正常了
也可以升级到 poi 7.8.0 beta.1

**Comment by KuZhu** [comment]
我也希望下载7.8但是网页上显示not found

**Comment by KochiyaOcean** [comment]
https://npm.taobao.org/mirrors/poi/v7.8.0-beta.1/poi-7.8.0-beta.1-macos.dmg

**Comment by KuZhu** [comment]
万分感谢！！
