### ISSUE TITLE
Windows 平台下构建失败

### ISSUE THREAD

**Issue by wbsdty331** [poooi/poi#1544]
## 系统环境 
* Windows 10 15063.540
* NodeJS `8.4.0` Current + npm `5.3.0`
```
C:\Users\wb\Documents\poi-master\poi-master>npm --version
5.3.0
C:\Users\wb\Documents\poi-master\poi-master>node --version
v8.4.0
```

* Git Windows 2.14.1

---

构建失败时的日志:
```
2001 silly decomposeActions install brace-expansion@1.1.8
2002 silly decomposeActions postinstall brace-expansion@1.1.8
2003 silly decomposeActions finalize brace-expansion@1.1.8
2004 silly decomposeActions refresh-package-json brace-expansion@1.1.8
2005 silly decomposeActions fetch contains-path@0.1.0
2006 silly decomposeActions extract contains-path@0.1.0
2007 silly decomposeActions preinstall contains-path@0.1.0
2008 silly decomposeActions build contains-path@0.1.0
2009 silly decomposeActions install contains-path@0.1.0
2010 silly decomposeActions postinstall contains-path@0.1.0
2011 silly decomposeActions finalize contains-path@0.1.0
2012 silly decomposeActions refresh-package-json contains-path@0.1.0
2013 silly decomposeActions fetch convert-source-map@1.5.0
2014 silly decomposeActions extract convert-source-map@1.5.0
2015 silly decomposeActions preinstall convert-source-map@1.5.0
2016 silly decomposeActions build convert-source-map@1.5.0
2017 silly decomposeActions install convert-source-map@1.5.0
2018 silly decomposeActions postinstall convert-source-map@1.5.0
2019 silly decomposeActions finalize convert-source-map@1.5.0
2020 silly decomposeActions refresh-package-json convert-source-map@1.5.0
2021 silly decomposeActions fetch core-js@2.4.1
2022 silly decomposeActions extract core-js@2.4.1
2023 silly decomposeActions preinstall core-js@2.4.1
2024 silly decomposeActions build core-js@2.4.1
2025 silly decomposeActions install core-js@2.4.1
2026 silly decomposeActions postinstall core-js@2.4.1
2027 silly decomposeActions finalize core-js@2.4.1
2028 silly decomposeActions refresh-package-json core-js@2.4.1
2029 silly decomposeActions fetch core-util-is@1.0.2
2030 silly decomposeActions extract core-util-is@1.0.2
2031 silly decomposeActions preinstall core-util-is@1.0.2
2032 silly decomposeActions build core-util-is@1.0.2
2033 silly decomposeActions install core-util-is@1.0.2
2034 silly decomposeActions postinstall core-util-is@1.0.2
2035 silly decomposeActions finalize core-util-is@1.0.2
2036 silly decomposeActions refresh-package-json core-util-is@1.0.2
2037 silly decomposeActions fetch crc@3.4.4
2038 silly decomposeActions extract crc@3.4.4
2039 silly decomposeActions preinstall crc@3.4.4
2040 silly decomposeActions build crc@3.4.4
2041 silly decomposeActions install crc@3.4.4
2042 silly decomposeActions postinstall crc@3.4.4
2043 silly decomposeActions finalize crc@3.4.4
2044 silly decomposeActions refresh-package-json crc@3.4.4
2045 silly decomposeActions fetch create-error-class@3.0.2
2046 silly decomposeActions extract create-error-class@3.0.2
2047 silly decomposeActions preinstall create-error-class@3.0.2
2048 silly decomposeActions build create-error-class@3.0.2
2049 silly decomposeActions install create-error-class@3.0.2
2050 silly decomposeActions postinstall create-error-class@3.0.2
2051 silly decomposeActions finalize create-error-class@3.0.2
2052 silly decomposeActions refresh-package-json create-error-class@3.0.2
2053 silly decomposeActions fetch crypto-random-string@1.0.0
2054 silly decomposeActions extract crypto-random-string@1.0.0
2055 silly decomposeActions preinstall crypto-random-string@1.0.0
2056 silly decomposeActions build crypto-random-string@1.0.0
2057 silly decomposeActions install crypto-random-string@1.0.0
2058 silly decomposeActions postinstall crypto-random-string@1.0.0
2059 silly decomposeActions finalize crypto-random-string@1.0.0
2060 silly decomposeActions refresh-package-json crypto-random-string@1.0.0
2061 silly decomposeActions fetch cson-parser@1.3.5
2062 silly decomposeActions extract cson-parser@1.3.5
2063 silly decomposeActions preinstall cson-parser@1.3.5
2064 silly decomposeActions build cson-parser@1.3.5
2065 silly decomposeActions install cson-parser@1.3.5
2066 silly decomposeActions postinstall cson-parser@1.3.5
2067 silly decomposeActions finalize cson-parser@1.3.5
2068 silly decomposeActions refresh-package-json cson-parser@1.3.5
2069 silly decomposeActions fetch cuint@0.2.2
2070 silly decomposeActions extract cuint@0.2.2
2071 silly decomposeActions preinstall cuint@0.2.2
2072 silly decomposeActions build cuint@0.2.2
2073 silly decomposeActions install cuint@0.2.2
2074 silly decomposeActions postinstall cuint@0.2.2
2075 silly decomposeActions finalize cuint@0.2.2
2076 silly decomposeActions refresh-package-json cuint@0.2.2
2077 silly decomposeActions fetch currently-unhandled@0.4.1
2078 silly decomposeActions extract currently-unhandled@0.4.1
2079 silly decomposeActions preinstall currently-unhandled@0.4.1
2080 silly decomposeActions build currently-unhandled@0.4.1
2081 silly decomposeActions install currently-unhandled@0.4.1
2082 silly decomposeActions postinstall currently-unhandled@0.4.1
2083 silly decomposeActions finalize currently-unhandled@0.4.1
2084 silly decomposeActions refresh-package-json currently-unhandled@0.4.1
2085 silly decomposeActions fetch cycle@1.0.3
2086 silly decomposeActions extract cycle@1.0.3
2087 silly decomposeActions preinstall cycle@1.0.3
2088 silly decomposeActions build cycle@1.0.3
2089 silly decomposeActions install cycle@1.0.3
2090 silly decomposeActions postinstall cycle@1.0.3
2091 silly decomposeActions finalize cycle@1.0.3
2092 silly decomposeActions refresh-package-json cycle@1.0.3
2093 silly decomposeActions fetch assert-plus@1.0.0
2094 silly decomposeActions extract assert-plus@1.0.0
2095 silly decomposeActions preinstall assert-plus@1.0.0
2096 silly decomposeActions build assert-plus@1.0.0
2097 silly decomposeActions install assert-plus@1.0.0
2098 silly decomposeActions postinstall assert-plus@1.0.0
2099 silly decomposeActions finalize assert-plus@1.0.0
2100 silly decomposeActions refresh-package-json assert-plus@1.0.0
2101 silly decomposeActions fetch dashdash@1.14.1
2102 silly decomposeActions extract dashdash@1.14.1
2103 silly decomposeActions preinstall dashdash@1.14.1
2104 silly decomposeActions build dashdash@1.14.1
2105 silly decomposeActions install dashdash@1.14.1
2106 silly decomposeActions postinstall dashdash@1.14.1
2107 silly decomposeActions finalize dashdash@1.14.1
2108 silly decomposeActions refresh-package-json dashdash@1.14.1
2109 silly decomposeActions fetch data-uri-to-buffer@0.0.4
2110 silly decomposeActions extract data-uri-to-buffer@0.0.4
2111 silly decomposeActions preinstall data-uri-to-buffer@0.0.4
2112 silly decomposeActions build data-uri-to-buffer@0.0.4
2113 silly decomposeActions install data-uri-to-buffer@0.0.4
2114 silly decomposeActions postinstall data-uri-to-buffer@0.0.4
2115 silly decomposeActions finalize data-uri-to-buffer@0.0.4
2116 silly decomposeActions refresh-package-json data-uri-to-buffer@0.0.4
2117 silly decomposeActions fetch dateformat@2.0.0
2118 silly decomposeActions extract dateformat@2.0.0
2119 silly decomposeActions preinstall dateformat@2.0.0
2120 silly decomposeActions build dateformat@2.0.0
2121 silly decomposeActions install dateformat@2.0.0
2122 silly decomposeActions postinstall dateformat@2.0.0
2123 silly decomposeActions finalize dateformat@2.0.0
2124 silly decomposeActions refresh-package-json dateformat@2.0.0
2125 silly decomposeActions fetch decamelize@1.2.0
2126 silly decomposeActions extract decamelize@1.2.0
2127 silly decomposeActions preinstall decamelize@1.2.0
2128 silly decomposeActions build decamelize@1.2.0
2129 silly decomposeActions install decamelize@1.2.0
2130 silly decomposeActions postinstall decamelize@1.2.0
2131 silly decomposeActions finalize decamelize@1.2.0
2132 silly decomposeActions refresh-package-json decamelize@1.2.0
2133 silly decomposeActions fetch deep-extend@0.4.2
2134 silly decomposeActions extract deep-extend@0.4.2
2135 silly decomposeActions preinstall deep-extend@0.4.2
2136 silly decomposeActions build deep-extend@0.4.2
2137 silly decomposeActions install deep-extend@0.4.2
2138 silly decomposeActions postinstall deep-extend@0.4.2
2139 silly decomposeActions finalize deep-extend@0.4.2
2140 silly decomposeActions refresh-package-json deep-extend@0.4.2
2141 silly decomposeActions fetch deep-is@0.1.3
2142 silly decomposeActions extract deep-is@0.1.3
2143 silly decomposeActions preinstall deep-is@0.1.3
2144 silly decomposeActions build deep-is@0.1.3
2145 silly decomposeActions install deep-is@0.1.3
2146 silly decomposeActions postinstall deep-is@0.1.3
2147 silly decomposeActions finalize deep-is@0.1.3
2148 silly decomposeActions refresh-package-json deep-is@0.1.3
2149 silly decomposeActions fetch defaults@1.0.3
2150 silly decomposeActions extract defaults@1.0.3
2151 silly decomposeActions preinstall defaults@1.0.3
2152 silly decomposeActions build defaults@1.0.3
2153 silly decomposeActions install defaults@1.0.3
2154 silly decomposeActions postinstall defaults@1.0.3
2155 silly decomposeActions finalize defaults@1.0.3
2156 silly decomposeActions refresh-package-json defaults@1.0.3
2157 silly decomposeActions fetch delayed-stream@1.0.0
2158 silly decomposeActions extract delayed-stream@1.0.0
2159 silly decomposeActions preinstall delayed-stream@1.0.0
2160 silly decomposeActions build delayed-stream@1.0.0
2161 silly decomposeActions install delayed-stream@1.0.0
2162 silly decomposeActions postinstall delayed-stream@1.0.0
2163 silly decomposeActions finalize delayed-stream@1.0.0
2164 silly decomposeActions refresh-package-json delayed-stream@1.0.0
2165 silly decomposeActions fetch combined-stream@1.0.5
2166 silly decomposeActions extract combined-stream@1.0.5
2167 silly decomposeActions preinstall combined-stream@1.0.5
2168 silly decomposeActions build combined-stream@1.0.5
2169 silly decomposeActions install combined-stream@1.0.5
2170 silly decomposeActions postinstall combined-stream@1.0.5
2171 silly decomposeActions finalize combined-stream@1.0.5
2172 silly decomposeActions refresh-package-json combined-stream@1.0.5
2173 silly decomposeActions fetch deprecated@0.0.1
2174 silly decomposeActions extract deprecated@0.0.1
2175 silly decomposeActions preinstall deprecated@0.0.1
2176 silly decomposeActions build deprecated@0.0.1
2177 silly decomposeActions install deprecated@0.0.1
2178 silly decomposeActions postinstall deprecated@0.0.1
2179 silly decomposeActions finalize deprecated@0.0.1
2180 silly decomposeActions refresh-package-json deprecated@0.0.1
2181 silly decomposeActions fetch diff@3.2.0
2182 silly decomposeActions extract diff@3.2.0
2183 silly decomposeActions preinstall diff@3.2.0
2184 silly decomposeActions build diff@3.2.0
2185 silly decomposeActions install diff@3.2.0
2186 silly decomposeActions postinstall diff@3.2.0
2187 silly decomposeActions finalize diff@3.2.0
2188 silly decomposeActions refresh-package-json diff@3.2.0
2189 silly decomposeActions fetch isarray@1.0.0
2190 silly decomposeActions extract isarray@1.0.0
2191 silly decomposeActions preinstall isarray@1.0.0
2192 silly decomposeActions build isarray@1.0.0
2193 silly decomposeActions install isarray@1.0.0
2194 silly decomposeActions postinstall isarray@1.0.0
2195 silly decomposeActions finalize isarray@1.0.0
2196 silly decomposeActions refresh-package-json isarray@1.0.0
2197 silly decomposeActions fetch dom-helpers@3.2.1
2198 silly decomposeActions extract dom-helpers@3.2.1
2199 silly decomposeActions preinstall dom-helpers@3.2.1
2200 silly decomposeActions build dom-helpers@3.2.1
2201 silly decomposeActions install dom-helpers@3.2.1
2202 silly decomposeActions postinstall dom-helpers@3.2.1
2203 silly decomposeActions finalize dom-helpers@3.2.1
2204 silly decomposeActions refresh-package-json dom-helpers@3.2.1
2205 silly decomposeActions fetch duplexer3@0.1.4
2206 silly decomposeActions extract duplexer3@0.1.4
2207 silly decomposeActions preinstall duplexer3@0.1.4
2208 silly decomposeActions build duplexer3@0.1.4
2209 silly decomposeActions install duplexer3@0.1.4
2210 silly decomposeActions postinstall duplexer3@0.1.4
2211 silly decomposeActions finalize duplexer3@0.1.4
2212 silly decomposeActions refresh-package-json duplexer3@0.1.4
2213 silly decomposeActions fetch editions@1.3.3
2214 silly decomposeActions extract editions@1.3.3
2215 silly decomposeActions preinstall editions@1.3.3
2216 silly decomposeActions build editions@1.3.3
2217 silly decomposeActions install editions@1.3.3
2218 silly decomposeActions postinstall editions@1.3.3
2219 silly decomposeActions finalize editions@1.3.3
2220 silly decomposeActions refresh-package-json editions@1.3.3
2221 silly decomposeActions fetch electron-builder-core@17.2.0
2222 silly decomposeActions extract electron-builder-core@17.2.0
2223 silly decomposeActions preinstall electron-builder-core@17.2.0
2224 silly decomposeActions build electron-builder-core@17.2.0
2225 silly decomposeActions install electron-builder-core@17.2.0
2226 silly decomposeActions postinstall electron-builder-core@17.2.0
2227 silly decomposeActions finalize electron-builder-core@17.2.0
2228 silly decomposeActions refresh-package-json electron-builder-core@17.2.0
2229 silly decomposeActions fetch electron-builder-core@18.7.0
2230 silly decomposeActions extract electron-builder-core@18.7.0
2231 silly decomposeActions preinstall electron-builder-core@18.7.0
2232 silly decomposeActions build electron-builder-core@18.7.0
2233 silly decomposeActions install electron-builder-core@18.7.0
2234 silly decomposeActions postinstall electron-builder-core@18.7.0
2235 silly decomposeActions finalize electron-builder-core@18.7.0
2236 silly decomposeActions refresh-package-json electron-builder-core@18.7.0
2237 silly decomposeActions fetch co@4.6.0
2238 silly decomposeActions extract co@4.6.0
2239 silly decomposeActions preinstall co@4.6.0
2240 silly decomposeActions build co@4.6.0
2241 silly decomposeActions install co@4.6.0
2242 silly decomposeActions postinstall co@4.6.0
2243 silly decomposeActions finalize co@4.6.0
2244 silly decomposeActions refresh-package-json co@4.6.0
2245 silly decomposeActions fetch minimist@1.2.0
2246 silly decomposeActions extract minimist@1.2.0
2247 silly decomposeActions preinstall minimist@1.2.0
2248 silly decomposeActions build minimist@1.2.0
2249 silly decomposeActions install minimist@1.2.0
2250 silly decomposeActions postinstall minimist@1.2.0
2251 silly decomposeActions finalize minimist@1.2.0
2252 silly decomposeActions refresh-package-json minimist@1.2.0
2253 silly decomposeActions fetch minimist@1.2.0
2254 silly decomposeActions extract minimist@1.2.0
2255 silly decomposeActions preinstall minimist@1.2.0
2256 silly decomposeActions build minimist@1.2.0
2257 silly decomposeActions install minimist@1.2.0
2258 silly decomposeActions postinstall minimist@1.2.0
2259 silly decomposeActions finalize minimist@1.2.0
2260 silly decomposeActions refresh-package-json minimist@1.2.0
2261 silly decomposeActions fetch electron-is-dev@0.1.2
2262 silly decomposeActions extract electron-is-dev@0.1.2
2263 silly decomposeActions preinstall electron-is-dev@0.1.2
2264 silly decomposeActions build electron-is-dev@0.1.2
2265 silly decomposeActions install electron-is-dev@0.1.2
2266 silly decomposeActions postinstall electron-is-dev@0.1.2
2267 silly decomposeActions finalize electron-is-dev@0.1.2
2268 silly decomposeActions refresh-package-json electron-is-dev@0.1.2
2269 silly decomposeActions fetch minimist@1.2.0
2270 silly decomposeActions extract minimist@1.2.0
2271 silly decomposeActions preinstall minimist@1.2.0
2272 silly decomposeActions build minimist@1.2.0
2273 silly decomposeActions install minimist@1.2.0
2274 silly decomposeActions postinstall minimist@1.2.0
2275 silly decomposeActions finalize minimist@1.2.0
2276 silly decomposeActions refresh-package-json minimist@1.2.0
2277 silly decomposeActions fetch element-class@0.2.2
2278 silly decomposeActions extract element-class@0.2.2
2279 silly decomposeActions preinstall element-class@0.2.2
2280 silly decomposeActions build element-class@0.2.2
2281 silly decomposeActions install element-class@0.2.2
2282 silly decomposeActions postinstall element-class@0.2.2
2283 silly decomposeActions finalize element-class@0.2.2
2284 silly decomposeActions refresh-package-json element-class@0.2.2
2285 silly decomposeActions fetch env-paths@1.0.0
2286 silly decomposeActions extract env-paths@1.0.0
2287 silly decomposeActions preinstall env-paths@1.0.0
2288 silly decomposeActions build env-paths@1.0.0
2289 silly decomposeActions install env-paths@1.0.0
2290 silly decomposeActions postinstall env-paths@1.0.0
2291 silly decomposeActions finalize env-paths@1.0.0
2292 silly decomposeActions refresh-package-json env-paths@1.0.0

...
11603 silly extract bytes@2.4.0
11604 silly extract builtin-modules@1.1.1
11605 silly extract buffers@0.1.1
11606 silly extract buffer-crc32@0.2.13
11607 silly extract browser-stdout@1.3.0
11608 silly extract bluebird-lst@1.0.2
11609 silly extract bluebird@3.5.0
11610 silly extract beeper@1.1.1
11611 silly extract base64-js@1.2.0
11612 silly extract balanced-match@1.0.0
11613 silly extract babylon@6.17.3
11614 verbose unlock done using C:\Users\wb\AppData\Roaming\npm-cache\_locks\staging-dcbba5522d53f0df.lock for C:\Users\wb\Documents\poi-master\poi-master\node_modules\.staging
11615 warn optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules\7zip-bin-mac):
11616 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\wb\Documents\poi-master\poi-master\node_modules\.staging\7zip-bin-mac-31a017a6\7za'
11617 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
11617 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
11618 warn optional SKIPPING OPTIONAL DEPENDENCY: node-forge@0.7.1 (node_modules\node-forge):
11619 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\wb\Documents\poi-master\poi-master\node_modules\.staging\node-forge-781e0e93\lib\tls.js'
11620 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
11620 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
11621 warn optional SKIPPING OPTIONAL DEPENDENCY: iconv-lite@0.4.17 (node_modules\iconv-lite):
11622 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\wb\Documents\poi-master\poi-master\node_modules\.staging\iconv-lite-fed7c0d5\encodings\tables\cp950.json'
11623 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
11623 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
11624 verbose type OperationalError
11625 verbose stack Error: sha1-u8qATAQE2cZAECsrZWrkzVvqNcg= integrity checksum failed when using sha1: wanted sha1-u8qATAQE2cZAECsrZWrkzVvqNcg= but got sha1-3xx1LJIncskknRUk7Y0ue7BksNA=. (111622 bytes)
11625 verbose stack     at Transform.on (C:\Program Files\nodejs\node_modules\npm\node_modules\ssri\index.js:275:19)
11625 verbose stack     at emitNone (events.js:110:20)
11625 verbose stack     at Transform.emit (events.js:207:7)
11625 verbose stack     at endReadableNT (_stream_readable.js:1059:12)
11625 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
11625 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
11626 verbose cwd C:\Users\wb\Documents\poi-master\poi-master
11627 verbose Windows_NT 10.0.15063
11628 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
11629 verbose node v8.4.0
11630 verbose npm  v5.3.0
11631 error code EINTEGRITY
11632 error sha1-u8qATAQE2cZAECsrZWrkzVvqNcg= integrity checksum failed when using sha1: wanted sha1-u8qATAQE2cZAECsrZWrkzVvqNcg= but got sha1-3xx1LJIncskknRUk7Y0ue7BksNA=. (111622 bytes)
11633 verbose exit [ 1, true ]

**Comment by KochiyaOcean** [comment]
确认一下使用的 npm 镜像的 sha1 值和 npmjs 是否有差别吧

**Comment by wbsdty331** [comment]
好的
