### ISSUE TITLE
改修插件出问题了- -

### ISSUE THREAD

**Issue by cydad111** [poooi/poi#1587]
**poi 版本 / poi version:**
7.10.0beta

**操作系统 / OS:**

WIN7 SP1 64位
**插件名和版本 / Plugin name & version:**

装备改修

**你遇到了什么样的问题 / The problem you've met:**

打开后无显示，等了30分钟还是无显示，删除重装也一样

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

Failed to load resource: net::ERR_TIMED_OUT
3337921 
Failed to load resource: net::ERR_TIMED_OUT
17797795 
Failed to load resource: net::ERR_TIMED_OUT
11089376 
Failed to load resource: net::ERR_TIMED_OUT
2235314
 Failed to load resource: net::ERR_TIMED_OUT
12785565 
Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
6986642 
Failed to load resource: net::ERR_TIMED_OUT
1183568 
Failed to load resource: net::ERR_TIMED_OUT
6861365
 Failed to load resource: net::ERR_EMPTY_RESPONSE
250x250.png
Failed to load resource: net::ERR_TIMED_OUT
12995396 
Failed to load resource: net::ERR_TIMED_OUT
6753092 
Failed to load resource: net::ERR_TIMED_OUT
index.html:1
 GET https://raw.githubusercontent.com/andanteyk/ElectronicObserver/develop/ElectronicObserver/Assets/AppIcon_64.png net::ERR_TIMED_OUT

**Comment by KochiyaOcean** [comment]
在改修插件按 ctrl + shift + i 看看报错内容

**Comment by cydad111** [comment]
已经列出来了

**Comment by KochiyaOcean** [comment]
这个是本体的吧……

**Comment by cydad111** [comment]
Uncaught Error: Cannot find module 'react-numeric-input'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-item-improvement\views\starcraft\plan-modify-control.js:24:26)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-item-improvement\views\starcraft\plan-modify-control.js:170:3)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-item-improvement\views\starcraft\equip-view.js:20:26)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-item-improvement\views\starcraft\equip-view.js:114:3)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-item-improvement\views\item-wrapper.js:22:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-item-improvement\views\item-wrapper.js:111:3)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-item-improvement\views\item-info-area.js:28:20)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-item-improvement\views\item-info-area.js:210:3)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-item-improvement\views\index.js:15:21)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-item-improvement\views\index.js:30:3)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-item-improvement\item-improvement.js:87:1)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-item-improvement\item-improvement.js:88:3)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (E:\BaiduYunDownload\poi-7.10.0-beta.0-win\resources\app\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at file:///C:/Users/Administrator/AppData/Roaming/poi/plugins/node_modules/poi-plugin-item-improvement/index.html:15:7

**Comment by cydad111** [comment]
。。。。能看完么- -很长的

**Comment by KochiyaOcean** [comment]
@cydad111 最好是截图

**Comment by KochiyaOcean** [comment]
@cydad111 截图直接黏贴就可以上传

**Comment by cydad111** [comment]
问题就是截图的话一张截不完整啊。。。

**Comment by cydad111** [comment]
![qq 20170923235851](https://user-images.githubusercontent.com/31899636/30774288-36d62f06-a0bb-11e7-81a2-d05b897ec4bf.jpg)
![qq 20170923235934](https://user-images.githubusercontent.com/31899636/30774292-4e712a62-a0bb-11e7-9d4c-071dc5c6475a.jpg)
截完了- -

**Comment by KochiyaOcean** [comment]
插件设置 - 高级设置 - 打开插件文件夹
全部删除以后再安装看看？

**Comment by cydad111** [comment]
你知不知道我以前安装不上也试过这个。。。。然后发觉安装上就是因为下载服务器问题。。。所以我估计试了全删除也没用拉。。。。

**Comment by cydad111** [comment]
我都估计了。。。。装备改修应该是连接到专门服务器下载改修信息吧？那么只有可能是连不上那个服务器

**Comment by KochiyaOcean** [comment]
@cydad111 并没有……单纯的是没有安装完全依赖的模组而已

**Comment by KochiyaOcean** [comment]
@cydad111 你之前全部删除的时候是在 7.9.x 下么？ 7.10.0 是修复了 7.9.x 的安装的一个 bug 的

**Comment by cydad111** [comment]
但我这个问题7.10.0也出现了，最后发觉是下载服务器问题，而且只修复了任务信息下载。。。

**Comment by KochiyaOcean** [comment]
@cydad111 换过服务器和切换过是否通过代理下载？

**Comment by cydad111** [comment]
不，装备改修下载貌似只能用过非US服务器不用代理下载- -。我的上一个帖子试出来了。。。。

**Comment by KochiyaOcean** [comment]
@cydad111 win+r 输入 cmd 然后把 poi.exe 拖进去看看安装的时候有什么 log 吧
以及使用的是什么代理……

**Comment by cydad111** [comment]
试过了，全删除然后安装还是那段错误

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/30774444-287cc254-a0b5-11e7-9e1f-6ae2568f81e7.png)
是需要看这样的安装日志啦

**Comment by cydad111** [comment]
不行啊不知道为何，CMD的截图传不上

**Comment by KochiyaOcean** [comment]
@cydad111 呃复制下文字也好……

**Comment by cydad111** [comment]
CMD界面能这样么。。。

**Comment by KochiyaOcean** [comment]
@cydad111 拖动选择然后右击就直接复制了

**Comment by cydad111** [comment]
打个错误吧- -
error：socket hang up 
顺带- -我说了，CMD界面怎么拖动选择？？？我只有右键可以选择而且不能复制

**Comment by cydad111** [comment]
Wait for app ready
[INFO] Proxy listening on 53576
C:\Users\Administrator\Desktop\poi.lnk

C:\Users\Administrator>
Wait for app ready
[INFO] Proxy listening on 53609
[ERROR] Connection failed: GET http://static.ads-twitter.com/uwt.js Error: socke
t hang up
NOT SANDBOXED
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Administrat
or\AppData\Roaming\poi\plugins\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Administrator\
AppData\Roaming\poi\plugins\package.json'
npm WARN react-numeric-input@2.2.0 requires a peer of react@>=0.14.0 || ^15.6.1
but none is installed. You must install peer dependencies yourself.
npm WARN plugins No description
npm WARN plugins No repository field.
npm WARN plugins No README data
npm WARN plugins No license field.

+ poi-plugin-item-improvement@5.0.3
added 1 package in 1.148s
[ERROR] Connection failed: GET http://s-cs.send.microad.jp/hs?k=bypass_2&id=cb1d
4a4d-1157-41a2-9d6b-f6f847025bb5 Error: socket hang up
[ERROR] Connection failed: GET http://aw.dw.impact-ad.jp/ut/rep?u=1673&v=209&r=h
ttp%3A%2F%2Fwww.dmm.com%2Fnetgame%2Fsocial%2F-%2Fgadgets%2F%3D%2Fapp_id%3D854854
%2F&t=62594 Error: socket hang up

**Comment by KochiyaOcean** [comment]
![image](https://user-images.githubusercontent.com/8194131/30774548-ec15d2ae-a0b6-11e7-855e-78e991bd6687.png)

shang'shu上述路径有这样的文件夹么

顺便确认一下， 7.10.0 是使用安装包或者自动更新安装的，还是压缩包直接覆盖的

**Comment by cydad111** [comment]
所以说是什么文件夹？？？图片没载入完全= =我是从服务器上面下载的

**Comment by cydad111** [comment]
package.json首先确定没有这个文件。。。

**Comment by KochiyaOcean** [comment]
就是插件文件夹里面的 poi-plugin-item-improvement/node_modules

**Comment by cydad111** [comment]
有这2个文件夹。。。

**Comment by KochiyaOcean** [comment]
react-numeric-input 里面呢

**Comment by cydad111** [comment]
有package.json文件

**Comment by KochiyaOcean** [comment]
只有这个文件么？

**Comment by cydad111** [comment]
嗯

**Comment by KochiyaOcean** [comment]
嗯看来是这个依赖安装失败了
使用的是什么地区的什么运营商的网络？更换网络环境（比如手机开热点）是否会有不同？

**Comment by cydad111** [comment]
上海电信，手机热点是什么？？？？

**Comment by KochiyaOcean** [comment]
@cydad111 呃就是手机共享 wifi
代理呢是什么

**Comment by cydad111** [comment]
代理是岛风GO= =

**Comment by KochiyaOcean** [comment]
很微妙啊，看起来像是网络问题但是我在上海电信环境下的时候网络环境似乎没这么糟糕（至少 3 个服务器都能好好装上）
感觉需要进一步调查

**Comment by cydad111** [comment]
我上海电信用了11以上年了- -都是老用户。

**Comment by cydad111** [comment]
反正最近我这边网络有点不稳定。。。昨天半夜出现断线情况（连续），连上后不久又断了，再连上又好了。。。。反正我估计我这边电信挺少的。。。

**Comment by KochiyaOcean** [comment]
https://ci.appveyor.com/project/KochiyaOcean/poi/build/1.0.1893/artifacts
使用这个版本试试看？

**Comment by cydad111** [comment]
结果还是一样的～

**Comment by gnattu** [comment]
看上去不像poi的问题，建议你
1. 找一个岛风Go以外的代理下载插件
2. 用上海电信以外的网络下载插件
然后看是不是能解决问题。
