### ISSUE TITLE
插件"舰娘信息"按钮失效

### ISSUE THREAD

**Issue by deeporist** [poooi/poi#1595]
**poi 版本 / poi version:**
7.9.1

**操作系统 / OS:**
win 8.1 x64

**插件名和版本 / Plugin name & version:**
舰娘信息 Ver 4.3.0

**你遇到了什么样的问题 / The problem you've met:**
舰娘数据显示正常 但是在插件页面点击"书签","导出数据","出击计划", 没有任何反应.

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
删除插件后重装 =>无效
切换npm源安装 =>无效
取消代理选择直连 =>无效
在cmd里启动 => 
C:\Users\XXXX>H:\poi-7.9.1-win\poi.exe

C:\Users\XXXX>
Wait for app ready
[INFO] Proxy listening on 52350
[ERROR] Error: read ECONNRESET
[ERROR] Error: read ECONNRESET

在插件页面打开调试页面 console标签输出如下
H:\poi-7.9.1-win\resources\app\views\redux\info\quests.js:534 Scheduling daily refresh at 331200000 (now 1507128841436)
22:54:01.458 H:\POI\plugins\node_modules\poi-plugin-ship-info\ship-info.js:42 Error: Cannot find module 'poi-plugin-translator'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (H:\poi-7.9.1-win\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (H:\POI\plugins\node_modules\poi-plugin-ship-info\ship-info.js:39:3)
    at Object.<anonymous> (H:\POI\plugins\node_modules\poi-plugin-ship-info\ship-info.js:73:3)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (H:\poi-7.9.1-win\resources\app\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (H:\poi-7.9.1-win\resources\app\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at file:///H:/POI/plugins/node_modules/poi-plugin-ship-info/index.html:15:7

在手动安装"poi-plugin-translator"后 此warning消失但是按钮仍然点击无反应

![279](https://user-images.githubusercontent.com/19790639/31185184-edff55e0-a95d-11e7-8c1a-924a1c50635a.png)

poi的网络设置
http代理=>岛风go

isp 
电信

印象里之前还用得好好的 莫名其妙地就再也不能导出数据了 点"导出数据"也不弹出下拉菜单了

![sdgsgdfg](https://user-images.githubusercontent.com/19790639/31185284-29da90d4-a95e-11e7-96a0-bbc9022e74e6.jpg)
另外 poi的"webview开发者工具" 在dmm登陆界面时
H:\poi-7.9.1-win\resources\app\assets\js\webview-preload.js:109 Failed. Will retry in 100ms.
显示这个warning一直重复了1K多次.......

**Comment by KagamiChan** [comment]
多谢报告

舰娘信息的那个信息只是说检测到没有翻译插件，不是造成这个问题的原因
webview 的这个错误是正常的，我们需要在游戏载入之后做调整游戏区域的大小之类的工作，在没有载入之前都会一直重试

**Comment by KagamiChan** [comment]
发布了 4.3.1 版本的插件，请试一下
