### ISSUE TITLE
关于 战斗记录 和 航海日志 经常不能正常工作的问题。

### ISSUE THREAD

**Issue by wuskyjian** [poooi/poi#1634]
**poi 版本 / poi version:** v8.0.0-beta.2

**操作系统 / OS:** Windows 10 Professional 16299.64

**插件名和版本 / Plugin name & version:** **航海日志** Ver. 6.1.4 和 **战斗记录** Ver. 3.7.5

**你遇到了什么样的问题 / The problem you've met:** 
1. 在经过一段时间（不定，时长时短）的游戏以后，会出现点击 **战斗记录** 插件毫无反应的问题，这个时候打开 **航海日志** 的出击选项卡，仍然能看到有战斗被记录，但是点击最左侧圆圈i查看详情是毫无反应，这时候必须重启poi才能恢复正常，再次查看之前无法打开 **战斗记录** 的时候的任何出击，**航海日志** 都提示 **“战斗详情：无法找到该战斗”**。

2. 亦或者是 **航海日志** 打开完全漆黑一片毫无反应，但是此时 **战斗记录** 工作正常，这时候所有的出击均不会被 **航海日志** 所记录， 必须禁用航海日志再启用或者重启POI才能让航海日志恢复正常工作。

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:** 重现方法不明确，出现问题的时间是在更新到 POI 8.0.0 beta1以后，之后更新到 8.0.0 beta2后问题仍然没有得到任何改善。

**Comment by KagamiChan** [comment]
这些战斗是活动图中进行的，通常图中进行的，还是两者都有？

在航海日志毫无反应，或者战斗记录毫无反应的时候，在航海日志或者战斗日志的窗口激活的情况下按 ctrl+ shift + I 打开的开发者工具，console 里面会有什么内容出现吗，有的话麻烦复制或者截图贴一下

**Comment by wuskyjian** [comment]
活动图和通常图都出现过，我打完前半段E4航海日志有记录，战斗记录无反应，重启以后后半段整个E4航海日志都没反应，但是战斗记录可以正常使用，当然连斩杀记录都没有了。今天刷了半天5-4，挂机无操作出去吃饭，再回来看的时候出现航海日志无法打开的问题，禁用启用恢复正常。下次出现问题我会注意下截图和开发者工具的内容。
![image](https://user-images.githubusercontent.com/27017155/33235594-5423c1b6-d23b-11e7-987f-46c8febf1431.png)

**Comment by wuskyjian** [comment]
再出出现此问题，**航海日志** 无无任何显示内容，战斗详情工作正常。console显示内容：
D:\舰娘\poi-8.0.0-beta.2-win\resources\app\views\redux\info\quests.js:577 Scheduling daily refresh at 331200000 (now 1511646147261)
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-achievement\views\calendar.es:35 [pluginAchievement] ===== init chart =====
D:\舰娘\poi-8.0.0-beta.2-win\resources\app\views\components\settings\misc\index.js:159 No newer version of map: current 2017/11/19/02, remote 2017/11/19/02, mode default
D:\舰娘\poi-8.0.0-beta.2-win\resources\app\views\components\settings\misc\index.js:159 No newer version of maphp: current 2016/08/20/01, remote 2016/08/20/01, mode default
D:\舰娘\poi-8.0.0-beta.2-win\resources\app\views\components\settings\misc\index.js:159 No newer version of shiptag: current 2017/11/18/01, remote 2017/11/18/01, mode default
D:\舰娘\poi-8.0.0-beta.2-win\resources\app\views\components\settings\misc\index.js:167 Update fcd from https://poi.io/fcd/ successfully in mode default.
D:\舰娘\poi-8.0.0-beta.2-win\resources\app\views\services\update.js:125 Remote version: v8.0.0-beta.2. Current version: v8.0.0-beta.2
2D:\舰娘\poi-8.0.0-beta.2-win\resources\app\views\env-parts\devtool-message.js:24 This is poi@v8.0.0-beta.2 on win32 x64 with Electron@1.7.9,
        PLUGINS: poi-plugin-prophet@7.0.0-beta.16, poi-plugin-exp-calc@4.0.2, poi-plugin-quest-info@4.2.1, poi-plugin-ezexped@1.4.3, poi-plugin-map-hp@4.0.0, poi-plugin-akashic-records@6.1.4, poi-plugin-battle-detail@3.7.5, poi-plugin-wheres-my-fuel-gone@0.6.2, poi-plugin-item-info@3.1.0, poi-plugin-navy-album@0.3.1, poi-plugin-k2badge@0.3.2, poi-plugin-subtitle@1.2.2, poi-plugin-achievement@1.4.4,
        FCD: map@2017/11/19/02, maphp@2016/08/20/01, shiptag@2017/11/18/01

截图如下：
![image](https://user-images.githubusercontent.com/27017155/33235824-8aec4ee2-d241-11e7-9faf-5555a0ea8de9.png)

**Comment by KagamiChan** [comment]
@wuskyjian 我想看的不是主窗口的开发者工具，而是不响应的战斗记录或者航海日志的窗口的开发者工具，你需要激活相应的窗口再用 ctrl shift I 快捷键

**Comment by wuskyjian** [comment]
@KagamiChan 此问题再次出现，console代码提示如下：
Scheduling daily refresh at 331200000 (now 1511683318902)
D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:163 TypeError: Cannot read property '0' of undefined
    at AkashicResourceChart.shouldComponentUpdate (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:387:90)
    at updateClassInstance (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:111:249)
    at beginWork (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:133:60)
    at d (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:160:93)
    at f (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:160:416)
    at g (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:161:150)
    at z (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:167:461)
    at I (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:167:189)
    at x (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:165:427)
    at u (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:164:365)
    at Object.enqueueSetState (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:107:299)
    at Connect.t.setState (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react\cjs\react.production.min.js:11:357)
    at Connect.onStateChange (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:222:16)
    at Object.dispatch (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\redux\lib\createStore.js:186:7)
    at APIResolver.handleResponse.e (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\api-resolver.js:216:26)
    at parseResponses (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\views\env-parts\data-resolver.js:106:10)
    at resolveResponses (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\views\env-parts\data-resolver.js:113:7)
    at handleProxyGameOnResponse (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\views\env-parts\data-resolver.js:126:7)
    at CallbacksRegistry.apply (D:\舰娘\poi-8.0.0-beta.2-win\resources\electron.asar\common\api\callbacks-registry.js:48:25)
    at EventEmitter.<anonymous> (D:\舰娘\poi-8.0.0-beta.2-win\resources\electron.asar\renderer\api\remote.js:299:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)

k @ D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:163
D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:167 Uncaught TypeError: Cannot read property '0' of undefined
    at AkashicResourceChart.shouldComponentUpdate (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:387:90)
    at updateClassInstance (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:111:249)
    at beginWork (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:133:60)
    at d (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:160:93)
    at f (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:160:416)
    at g (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:161:150)
    at z (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:167:461)
    at I (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:167:189)
    at x (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:165:427)
    at u (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:164:365)
    at Object.enqueueSetState (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:107:299)
    at Connect.t.setState (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react\cjs\react.production.min.js:11:357)
    at Connect.onStateChange (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:222:16)
    at Object.dispatch (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\node_modules\redux\lib\createStore.js:186:7)
    at APIResolver.handleResponse.e (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\api-resolver.js:216:26)
    at parseResponses (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\views\env-parts\data-resolver.js:106:10)
    at resolveResponses (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\views\env-parts\data-resolver.js:113:7)
    at handleProxyGameOnResponse (D:\舰娘\poi-8.0.0-beta.2-win\resources\app\views\env-parts\data-resolver.js:126:7)
    at CallbacksRegistry.apply (D:\舰娘\poi-8.0.0-beta.2-win\resources\electron.asar\common\api\callbacks-registry.js:48:25)
    at EventEmitter.<anonymous> (D:\舰娘\poi-8.0.0-beta.2-win\resources\electron.asar\renderer\api\remote.js:299:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)

C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

window.onresize @ C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73
C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components…:73 Uncaught TypeError: Cannot read property 'style' of null
    at window.onresize (C:\Users\jiant\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:73:41)

截图如下：
![image](https://user-images.githubusercontent.com/27017155/33239803-5398e036-d2aa-11e7-824a-98b06db8706f.png)

**Comment by KagamiChan** [comment]
@JenningsWu 看起来需要修一下的样子，虽然我这边没有复现过

**Comment by KagamiChan** [comment]
@wuskyjian 至于战斗详情，出现问题的时候也请同样贴一下这些内容，这两个出的问题很可能不是同样的

**Comment by wuskyjian** [comment]
@KagamiChan 不幸的是我 **战斗详情** 的无反应的问题从上次遇到后，到现在还没有遇到过，不清楚还能不能重现。如果我有再次遇到会报告的。还有个细节是，**战斗详情** 我只有在 **活动海域** 出击的时候 **有且仅有一次** 遇到过无反应，**常规图** 到现在还 **没有遇到过**。

**Comment by KagamiChan** [comment]
航海日志那边已经修好了，战斗详情遇到了再重新 open 吧
