### ISSUE TITLE
航海日誌無回應

### ISSUE THREAD

**Issue by jerry78424** [poooi/poi#1666]
**poi 版本 / poi version:**
8.0.0

**操作系统 / OS:**
win7 64bit

**插件名和版本 / Plugin name & version:**
航海日誌6.1.6

**你遇到了什么样的问题 / The problem you've met:**

有時航海日誌會突然無回應，重啟插件後才能回復正常，中間的出擊不會被記錄
![2017-12-20 - 00 59 06](https://user-images.githubusercontent.com/3656749/34169249-bbb76938-e521-11e7-8f83-2619388594d4.png)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

以ctrl+shift+i查看，發現四種錯誤訊息，似乎一種與拆船有關，另三種與資源有關
![2017-12-20 - 01 00 04 myimgur v3 90 - myimgur eden fm x64](https://user-images.githubusercontent.com/3656749/34169278-d615d4cc-e521-11e7-86f9-57e4abf7e1a6.png)
![2017-12-20 - 01 00 23](https://user-images.githubusercontent.com/3656749/34169279-d646fdd6-e521-11e7-890d-29a6715b06c0.png)
![2017-12-20 - 01 00 41](https://user-images.githubusercontent.com/3656749/34169280-d679fa10-e521-11e7-8232-b800c964b0c8.png)
![2017-12-20 - 01 01 01](https://user-images.githubusercontent.com/3656749/34169282-d6acd3fe-e521-11e7-97d6-be2ac2801505.png)

類似的現象在"艦娘信息"插件也偶有發生，因難以復現暫時無法提供錯誤訊息

**Comment by jerry78424** [comment]
![2017-12-23 - 23 15 50 myimgur v3 90 - myimgur eden fm x64](https://user-images.githubusercontent.com/3656749/34324142-75e05bb2-e8a1-11e7-85e0-b4bf388c8708.png)

戰鬥記錄無回應，以ctrl+shift+i查看

**Comment by KagamiChan** [comment]
@jerry78424 你的战斗记录是什么版本的，有没有做过什么操作？截图里面的这种错误属于完全没有载入，一般挺难出现的

**Comment by jerry78424** [comment]
@KagamiChan 
v3.8.4
平時一直都是開著的，方便隨時切換視窗查看出擊狀態
遇到錯誤前應該沒什麼特別操作，只是普通的在出擊，切換視窗看勸退原因時才發現出錯的

**Comment by Ryuuen** [comment]
我使用航海日志的时候也会出现该情况，无法载入，期间的记录皆無

**Comment by chune780411** [comment]
我使用航海日誌也有相同問題

**Comment by JenningsWu** [comment]
难以重现，找不到问题具体处在哪里。

目前加了个异常捕获以防止组件的错误导致整个插件失效，大概能解决一些问题。

之后有空的话计划重写一下资源列表页面（flag

**Comment by Ryuuen** [comment]
回想了一下，最近几次好像都是东九区时间0000一过就会出现这个问题，而且一次一个准

**Comment by Ryuuen** [comment]
果然今天日期变更之后就出现了这个情况，打开航海日志无反应

![image](https://user-images.githubusercontent.com/7549347/35160419-69434998-fd80-11e7-825c-2fe851ef6ce4.png)

**Comment by JenningsWu** [comment]
@Ryuuen 试试新发的 6.2.1

**Comment by Ryuuen** [comment]
@JenningsWu 其实这个是昨晚更新到6.2.1之后的截图，过了12点就无响应的情况跟以前是一样的
我今晚再看看吧

**Comment by Ryuuen** [comment]
@JenningsWu 计算机使用东九区时间
000005时，可以打开
000050时，再次尝试打开时已经无法载入
![image](https://user-images.githubusercontent.com/7549347/35184878-7d088006-fe3e-11e7-88b1-f97793f561da.png)

**Comment by JenningsWu** [comment]
@Ryuuen 很奇怪，我这边难以重现，所以不好修。这两天有空的时候再看看

**Comment by KagamiChan** [comment]
看看新的 6.2.2 版本有没有修复这类问题

**Comment by Ryuuen** [comment]
今天过了0点，插件可以打开，资源选项卡出现下列错误，回想了一下，以前我一直是放在资源选项卡的

> TypeError: undefined is not a function
    at AkashicResourceChart.shouldComponentUpdate (C:\Users\zjkev\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\components\akashic-resource-chart.js:413:15)
    at updateClassInstance (D:\Poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:112:249)
    at beginWork (D:\Poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:133:475)
    at d (D:\Poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:161:93)
    at f (D:\Poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:161:417)
    at g (D:\Poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:162:149)
    at m (D:\Poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:169:173)
    at w (D:\Poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:168:413)
    at z (D:\Poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:167:32)
    at u (D:\Poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:165:441)
    at Object.enqueueSetState (D:\Poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:108:299)
    at Connect.A.setState (D:\Poi\resources\app\node_modules\react\cjs\react.production.min.js:12:357)
    at Connect.onStateChange (D:\Poi\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:222:16)
    at Object.dispatch (D:\Poi\resources\app\node_modules\redux\lib\createStore.js:186:7)
    at APIResolver.handleResponse.e (C:\Users\zjkev\AppData\Roaming\poi\plugins\node_modules\poi-plugin-akashic-records\views\api-resolver.js:216:26)
    at parseResponses (D:\Poi\resources\app\views\env-parts\data-resolver.js:106:10)
    at resolveResponses (D:\Poi\resources\app\views\env-parts\data-resolver.js:113:7)
    at handleProxyGameOnResponse (D:\Poi\resources\app\views\env-parts\data-resolver.js:126:7)
    at CallbacksRegistry.apply (D:\Poi\resources\electron.asar\common\api\callbacks-registry.js:48:25)
    at EventEmitter.<anonymous> (D:\Poi\resources\electron.asar\renderer\api\remote.js:299:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)


    in AkashicResourceChart
    in Connect(AkashicResourceChart)
    in div
    in TabPane
    in Tab
    in div
    in TabContent
    in div
    in TabContainer
    in Tabs
    in Uncontrolled(Tabs)
    in div
    in AkashicResourceLog
    in ErrorBoundary
    in div
    in TabPane
    in Tab
    in div
    in TabContent
    in div
    in TabContainer
    in Tabs
    in Uncontrolled(Tabs)
    in div
    in AkashicRecordsArea
    in Provider

>

**Comment by JenningsWu** [comment]
@Ryuuen 你现在的版本是？最新版本应该是 6.2.3，看看最新版本是否还会出这个错误

**Comment by Ryuuen** [comment]
6.2.3下，
这两天应该没有重现过该问题

**Comment by JenningsWu** [comment]
@Ryuuen
