### ISSUE TITLE
插件问题

### ISSUE THREAD

**Issue by telessa** [poooi/poi#1729]
**poi 版本 / poi version:**
8.1.0

**操作系统 / OS:**

Windows 10 版本 1709 （OS内部版本16299.192）
**插件名和版本 / Plugin name & version:**

未卜先知 7.0.2
经验计算 4.1.0
任务信息 5.0.0
易及远征 1.6.0
秘书通知 2.0.2
舰步如飞 1.2.3
战斗记录 3.10.0
士气速查 0.5.2
舰娘信息 5.0.2
装备改修 6.0.1
装备信息 3.1.0
海色相簿 0.7.1

**你遇到了什么样的问题 / The problem you've met:**

任务信息 易及远征 秘书通知 士气速查

 灰色不可用提示错误

经验计算 舰步如飞 战斗记录 舰娘信息 装备改修 装备信息  海色相簿

打开插件 新窗口什么也没有

未卜先知 乌龟

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
未卜先知
TypeError: (0 , _lodash2.default)(...).filter(...).flatMap is not a function
    at exports.getTPDazzyDing (C:\Users\G\AppData\Roaming\poi\plugins\node_modules\poi-plugin-prophet\utils.js:290:65)
    at Function.BattleViewArea [as mapToProps] (C:\Users\G\AppData\Roaming\poi\plugins\node_modules\poi-plugin-prophet\views\battle-view-area.js:80:50)
    at mapToPropsProxy (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\connect\wrapMapToProps.js:54:46)
    at Function.detectFactoryAndVerify (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\connect\wrapMapToProps.js:63:19)
    at mapToPropsProxy (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\connect\wrapMapToProps.js:54:46)
    at handleFirstCall (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\connect\selectorFactory.js:37:18)
    at pureFinalPropsSelector (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\connect\selectorFactory.js:85:81)
    at Object.runComponentSelector [as run] (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:43:25)
    at Connect.initSelector (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:195:23)
    at new Connect (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:136:15)
    at constructClassInstance (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:109:354)
    at beginWork (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:133:440)
    at d (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:161:93)
    at f (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:161:417)
    at g (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:162:149)
    at m (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:169:173)
    at w (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:168:413)
    at z (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:167:32)
    at u (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:165:441)
    at Object.enqueueSetState (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:108:299)
    at Connect.A.setState (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react\cjs\react.production.min.js:12:357)
    at Connect.onStateChange (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:222:16)
    at dispatch (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\redux\lib\createStore.js:186:7)
    at C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\redux-thunk\lib\index.js:14:16
    at action (C:\Users\G\AppData\Local\Programs\poi\resources\app\views\middlewares\promise-action.js:40:14)
    at C:\Users\G\AppData\Local\Programs\poi\resources\app\views\services\plugin-manager.js:479:9
    at Generator.next (<anonymous>)
    at step (C:\Users\G\AppData\Local\Programs\poi\resources\app\views\services\plugin-manager.js:37:191)
    at C:\Users\G\AppData\Local\Programs\poi\resources\app\views\services\plugin-manager.js:37:361
    at <anonymous>

    in Connect(Component)
    in div
    in Prophet
    in Connect(Prophet)
    in div
    in PluginWrap
    in div
    in div
    in div
    in tabContentsUnion
    in Connect(tabContentsUnion)
    in div
    in ControlledTabArea
    in Connect(ControlledTabArea)
    in Provider

舰步如飞的Console

C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:168 Uncaught TypeError: Expected a function
    at Function.flow (C:\Users\G\node_modules\lodash\index.js:3297:19)
    at prepareFilter (C:\Users\G\AppData\Roaming\poi\plugins\node_modules\poi-plugin-leveling\shiplist-ops.es:54:27)
    at ShipPicker.render (C:\Users\G\AppData\Roaming\poi\plugins\node_modules\poi-plugin-leveling\ui\goal-area\ship-picker\index.es:73:51)
    at h (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:130:280)
    at beginWork (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:133:485)
    at d (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:161:93)
    at f (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:161:417)
    at g (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:162:149)
    at m (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:169:173)
    at w (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:168:413)
    at z (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:167:32)
    at u (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:165:441)
    at Object.updateContainer (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:175:31)
    at C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:225:260
    at Object.unbatchedUpdates (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:171:453)
    at Pg (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:225:230)
    at Object.render (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:227:304)
    at Object.<anonymous> (C:\Users\G\AppData\Roaming\poi\plugins\node_modules\poi-plugin-leveling\ui\index.es:79:20)
    at Object.<anonymous> (C:\Users\G\AppData\Roaming\poi\plugins\node_modules\poi-plugin-leveling\ui\index.es:85:3)
    at Module._compile (module.js:571:32)
    at loader (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .es] (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\G\AppData\Roaming\poi\plugins\node_modules\poi-plugin-leveling\entry.es:92:1)
    at Object.<anonymous> (C:\Users\G\AppData\Roaming\poi\plugins\node_modules\poi-plugin-leveling\entry.es:94:3)
    at Module._compile (module.js:571:32)
    at loader (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .es] (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (C:\Users\G\AppData\Local\Programs\poi\resources\app\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at file:///C:/Users/G/AppData/Roaming/poi/plugins/node_modules/poi-plugin-leveling/index.html:15:7

**Comment by KagamiChan** [comment]
重新安装 poi 看一下

**Comment by telessa** [comment]
没变化

**Comment by KagamiChan** [comment]
你在舰娘信息的窗口激活的情况下，按 ctrl + shift + i 然后在 console 里面输入 require.resolve('lodash') 看看得到什么结果

**Comment by telessa** [comment]
![default](https://user-images.githubusercontent.com/30003325/36533918-02cf65ee-1800-11e8-998f-2221c1455dae.PNG)

**Comment by KagamiChan** [comment]
@telessa 建议你删掉打印出来的这个 node_modules 文件夹

**Comment by telessa** [comment]
除语音字幕插件提示错误 以外都好了
