### ISSUE TITLE
士气速查插件问题

### ISSUE THREAD

**Issue by flawxh** [poooi/poi#1793]
**poi 版本 / poi version:8.3.0-beta.2

**操作系统 / OS:win10 1607

**插件名和版本 / Plugin name & version:**士气速查 0.5.3

**你遇到了什么样的问题 / The problem you've met:**
士气速查乌龟

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
TypeError: Cannot read property 'map' of undefined
    at moraleListSelector (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-mo2\ui\fleet-morale-list/C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-mo2\ui\fleet-morale-list\selectors.es:86:24)
    at D:\poi\resources\app\node_modules\reselect\lib\index.js:76:25
    at D:\poi\resources\app\node_modules\reselect\lib\index.js:36:25
    at D:\poi\resources\app\node_modules\reselect\lib\index.js:90:33
    at D:\poi\resources\app\node_modules\reselect\lib\index.js:36:25
    at D:\poi\resources\app\node_modules\reselect\lib\index.js:86:37
    at Function.mapToProps (D:\poi\resources\app\node_modules\reselect\lib\index.js:36:25)
    at mapToPropsProxy (D:\poi\resources\app\node_modules\react-redux\lib\connect\wrapMapToProps.js:54:46)
    at handleNewState (D:\poi\resources\app\node_modules\react-redux\lib\connect\selectorFactory.js:63:26)
    at handleSubsequentCalls (D:\poi\resources\app\node_modules\react-redux\lib\connect\selectorFactory.js:80:30)
    at pureFinalPropsSelector (D:\poi\resources\app\node_modules\react-redux\lib\connect\selectorFactory.js:85:32)
    at Object.runComponentSelector (D:\poi\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:43:25)
    at Connect.onStateChange (D:\poi\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:216:23)
    at Object.notify (D:\poi\resources\app\node_modules\react-redux\lib\utils\Subscription.js:30:21)
    at Subscription.notifyNestedSubs (D:\poi\resources\app\node_modules\react-redux\lib\utils\Subscription.js:69:20)
    at Connect.onStateChange (D:\poi\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:219:16)
    at Object.notify (D:\poi\resources\app\node_modules\react-redux\lib\utils\Subscription.js:30:21)
    at Subscription.notifyNestedSubs (D:\poi\resources\app\node_modules\react-redux\lib\utils\Subscription.js:69:20)
    at Connect.onStateChange (D:\poi\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:219:16)
    at Object.notify (D:\poi\resources\app\node_modules\react-redux\lib\utils\Subscription.js:30:21)
    at Subscription.notifyNestedSubs (D:\poi\resources\app\node_modules\react-redux\lib\utils\Subscription.js:69:20)
    at Connect.notifyNestedSubsOnComponentDidUpdate (D:\poi\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:233:14)
    at commitLifeCycles (D:\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:149:308)
    at b (D:\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:158:229)
    at m (D:\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:169:217)
    at w (D:\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:168:413)
    at z (D:\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:167:32)
    at u (D:\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:165:441)
    at Object.enqueueSetState (D:\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:108:299)
    at Connect.A.setState (D:\poi\resources\app\node_modules\react\cjs\react.production.min.js:12:357)
    at Connect.onStateChange (D:\poi\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:222:16)
    at Object.notify (D:\poi\resources\app\node_modules\react-redux\lib\utils\Subscription.js:30:21)
    at Subscription.notifyNestedSubs (D:\poi\resources\app\node_modules\react-redux\lib\utils\Subscription.js:69:20)
    at Connect.onStateChange (D:\poi\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:219:16)
    at Object.notify (D:\poi\resources\app\node_modules\react-redux\lib\utils\Subscription.js:30:21)
    at Subscription.notifyNestedSubs (D:\poi\resources\app\node_modules\react-redux\lib\utils\Subscription.js:69:20)
    at Connect.onStateChange (D:\poi\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:219:16)
    at dispatch (D:\poi\resources\app\node_modules\redux\lib\createStore.js:186:7)
    at D:\poi\resources\app\node_modules\redux-thunk\lib\index.js:14:16
    at action (D:\poi\resources\app\views\middlewares\promise-action.js:55:12)
    at Object.pStateLoaded (D:\poi\resources\app\node_modules\redux\lib\bindActionCreators.js:7:12)
    at setTimeout (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-mo2\observers/C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-mo2\observers\p-state-loader.es:35:13)

    in Connect(FleetMoraleListImpl)
    in div
    in TabPane
    in Tab
    in div
    in TabContent
    in div
    in TabContainer
    in Tabs
    in Uncontrolled(Tabs)
    in div
    in MoraleMonitorImpl
    in Connect(MoraleMonitorImpl)
    in div
    in PluginWrap
    in I18n
    in Translate(PluginWrap)
    in div
    in div
    in div
    in TabContentsUnion
    in Connect(TabContentsUnion)
    in div
    in div
    in t
    in div
    in ControlledTabArea
    in Connect(ControlledTabArea)
    in I18n
    in Translate(Connect(ControlledTabArea))
    in poi-nav-tabs
    in poi-nav
    in div
    in poi-app
    in PoiApp
    in Connect(PoiApp)
    in poi-main
    in Poi
    in Connect(Poi)
    in Provider
    in I18nextProvider

**Comment by Javran** [comment]
打开 `%APPDATA%\poi\morale-monitor` 里头应该有个扩展名是json的文件, 可以贴一下那个文件的内容吗?

**Comment by flawxh** [comment]
{"fleets":{},"ships":{"sort":{},"filter":{"methods":[{"type":"lessThan","value":50},{"type":"lessThan","value":53},{"type":"lessThan","value":76},{"type":"lessThan","value":85},{"type":"lessThan","value":100}],"moraleFilters":{}}},"tab":"fleet","$version":"0.5.0"}
@Javran

**Comment by Javran** [comment]
@flawxh 了解, 把这个文件删掉, 然后禁用再启用插件应该就可以了.

**Comment by flawxh** [comment]
@Javran 解决了，感谢

**Comment by Javran** [comment]
实际上还是有点在意这个问题. 所以已经发了一个新版试着修一下, 不过不会影响使用.

@flawxh  只是顺便问一下: 这个插件你是全新安全, 还是从旧版本升级的, 如果是旧版本的话, 原来的版本是在早于0.4.0, 还是0.4.0或者后续版本?
