### ISSUE TITLE
未卜先知功能加载失败

### ISSUE THREAD

**Issue by PULIFAN** [poooi/poi#1828]
mac系统
poi版本8.2.0

报错：
<img width="616" alt="default" src="https://user-images.githubusercontent.com/29934655/39758683-2ef16382-5303-11e8-88ae-c222cd317f5f.png">

TypeError: _lodash2.default.sumBy is not a function
    at BattleViewArea (/Users/a123/Library/Application Support/poi/plugins/node_modules/poi-plugin-prophet/views/battle-view-area.js:141:44)
    at beginWork (/Applications/poi.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.production.min.js:132:493)
    at d (/Applications/poi.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.production.min.js:161:93)
    at f (/Applications/poi.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.production.min.js:161:417)
    at g (/Applications/poi.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.production.min.js:162:149)
    at m (/Applications/poi.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.production.min.js:169:173)
    at w (/Applications/poi.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at z (/Applications/poi.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.production.min.js:167:32)
    at u (/Applications/poi.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.production.min.js:165:441)
    at Object.enqueueSetState (/Applications/poi.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.production.min.js:108:299)
    at Connect.A.setState (/Applications/poi.app/Contents/Resources/app/node_modules/react/cjs/react.production.min.js:12:357)
    at Connect.onStateChange (/Applications/poi.app/Contents/Resources/app/node_modules/react-redux/lib/components/connectAdvanced.js:222:16)
    at Object.notify (/Applications/poi.app/Contents/Resources/app/node_modules/react-redux/lib/utils/Subscription.js:30:21)
    at Subscription.notifyNestedSubs (/Applications/poi.app/Contents/Resources/app/node_modules/react-redux/lib/utils/Subscription.js:69:20)
    at Connect.onStateChange (/Applications/poi.app/Contents/Resources/app/node_modules/react-redux/lib/components/connectAdvanced.js:219:16)
    at Object.notify (/Applications/poi.app/Contents/Resources/app/node_modules/react-redux/lib/utils/Subscription.js:30:21)
    at Subscription.notifyNestedSubs (/Applications/poi.app/Contents/Resources/app/node_modules/react-redux/lib/utils/Subscription.js:69:20)
    at Connect.onStateChange (/Applications/poi.app/Contents/Resources/app/node_modules/react-redux/lib/components/connectAdvanced.js:219:16)
    at dispatch (/Applications/poi.app/Contents/Resources/app/node_modules/redux/lib/createStore.js:186:7)
    at /Applications/poi.app/Contents/Resources/app/node_modules/redux-thunk/lib/index.js:14:16
    at action (/Applications/poi.app/Contents/Resources/app/views/middlewares/promise-action.js:55:12)
    at PluginManager.enablePlugin (/Applications/poi.app/Contents/Resources/app/views/services/plugin-manager.js:493:5)
    at <anonymous>

    in Unknown
    in Connect(Component)
    in div
    in Prophet
    in Connect(Prophet)
    in div
    in PluginWrap
    in I18n
    in Translate(PluginWrap)
    in div
    in div
    in div
    in TabContentsUnion
    in Connect(TabContentsUnion)
    in div
    in div
    in t
    in div
    in ControlledTabArea
    in Connect(ControlledTabArea)
    in I18n
    in Translate(Connect(ControlledTabArea))
    in poi-nav-tabs
    in poi-nav
    in div
    in poi-app
    in PoiApp
    in Connect(PoiApp)
    in poi-main
    in Poi
    in Connect(Poi)
    in Provider
    in I18nextProvider

**Comment by KagamiChan** [comment]
请问你的 `~` 目录下是不是有一个 `node_modules` 文件夹？

**Comment by PULIFAN** [comment]
对的 
<img width="602" alt="issue" src="https://user-images.githubusercontent.com/29934655/39792832-33d7f2ea-5375-11e8-9e48-e5e744f40772.png">

**Comment by KagamiChan** [comment]
我是说，你的个人主目录下

在终端里面输入 `ls ~/node_modules` 的结果是什么？

**Comment by PULIFAN** [comment]
<img width="1269" alt="pic_1" src="https://user-images.githubusercontent.com/29934655/39793263-42b9e19a-5377-11e8-8ad9-2f3054b9e332.png">
...好多东西

**Comment by KagamiChan** [comment]
放在个人目录下的 node_modules 会对 poi 的运行产生干扰，并且一般来说也不需要在这里出现这个文件夹，建议你删掉

**Comment by PULIFAN** [comment]
好的 谢谢啦我试试 
性感大佬在线答疑
![image](https://user-images.githubusercontent.com/29934655/39794344-6dfdbaca-537c-11e8-8d77-fa0591cfd9ea.png)

**Comment by PULIFAN** [comment]
好了 谢谢大佬～
