### ISSUE TITLE
未卜先知插件加载失败怎么回事

### ISSUE THREAD

**Issue by csjtc** [poooi/poi#1841]
**插件名和版本 / Plugin name & version:**

未卜先知7.4.4

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by KagamiChan** [comment]
我这里的 8.2.0 没有看到问题，请点击游戏区域下方的第一个按钮，打开开发者工具，看看有没有出错日志，并截图

**Comment by csjtc** [comment]
![j9iebgec9ml7 o6hpbkn_m](https://user-images.githubusercontent.com/21023431/40838489-fbb5728e-65d0-11e8-8cf4-34e612e608c9.jpg)
是这样么

**Comment by KagamiChan** [comment]
@csjtc 请切换到 console 再截图

**Comment by KagamiChan** [comment]
@csjtc 请问 %appdata%/poi/plugins/poi-plugin-prophet 里面有内容吗
如果没有的话请把这个文件夹删掉再看一下

**Comment by csjtc** [comment]
{有这个txt
  "_from": "poi-plugin-prophet",
  "_id": "poi-plugin-prophet@7.4.4",
  "_inBundle": false,
  "_integrity": "sha1-FWN95hl8DMN1JWWII2tT1UKTUGc=",
  "_location": "/poi-plugin-prophet",
  "_phantomChildren": {},
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "poi-plugin-prophet",
    "name": "poi-plugin-prophet",
    "escapedName": "poi-plugin-prophet",
    "rawSpec": "",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "http://r.cnpmjs.org/poi-plugin-prophet/download/poi-plugin-prophet-7.4.4.tgz",
  "_shasum": "15637de6197c0cc375256588236b53d542935067",
  "_shrinkwrap": null,
  "_spec": "poi-plugin-prophet",
  "_where": "C:\\Users\\sbcsj\\AppData\\Roaming\\poi\\plugins",
  "bin": null,
  "bundleDependencies": false,
  "dependencies": {},
  "deprecated": false,
  "devDependencies": {
    "@commitlint/cli": "^6.1.3",
    "@commitlint/config-conventional": "^6.1.3",
    "babel-eslint": "^8.2.1",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-poi-plugin": "^1.0.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-prettier": "^2.6.0",
    "eslint-plugin-react": "^7.7.0",
    "husky": "^1.0.0-rc.1",
    "lint-staged": "^7.1.2",
    "poi-util-transpile": "^8.2.2",
    "prettier": "^1.12.1"
  },
  "name": "poi-plugin-prophet",
  "optionalDependencies": {},
  "peerDependencies": {},
  "version": "7.4.4"
}

**Comment by KagamiChan** [comment]
@csjtc 如果只有这个文件的话，只能说是别的文件被删掉了，你是不是装了什么杀毒软件，先关掉再安装插件看看？

**Comment by csjtc** [comment]
嗯，只有这个文件，一直用360的，突然插件就不能用了，我试试先关了下载一下

**Comment by sapphirecxm** [comment]
遇到了如下所示的问题，所有插件都变成了乌龟，求指导
TypeError: _lodash.default.sumBy is not a function
    at BattleViewArea (/Users/chenxiamin/Library/Application Support/poi/plugins/node_modules/poi-plugin-prophet/views/battle-view-area.js:132:43)
    at beginWork (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:136:36)
    at e (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:175:105)
    at f (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:175:379)
    at G (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:181:329)
    at x (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:180:378)
    at n (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:180:221)
    at B (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:179:117)
    at v (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:178:51)
    at Object.enqueueSetState (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:109:32)
    at Connect.D.setState (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react/cjs/react.production.min.js:12:357)
    at Connect.onStateChange (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-redux/lib/components/connectAdvanced.js:222:16)
    at Object.notify (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-redux/lib/utils/Subscription.js:30:21)
    at Subscription.notifyNestedSubs (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-redux/lib/utils/Subscription.js:69:20)
    at Connect.onStateChange (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-redux/lib/components/connectAdvanced.js:219:16)
    at Object.notify (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-redux/lib/utils/Subscription.js:30:21)
    at Subscription.notifyNestedSubs (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-redux/lib/utils/Subscription.js:69:20)
    at Connect.onStateChange (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-redux/lib/components/connectAdvanced.js:219:16)
    at dispatch (/Applications/poi.app/Contents/Resources/app.asar/node_modules/redux/lib/redux.js:227:7)
    at /Applications/poi.app/Contents/Resources/app.asar/node_modules/redux-thunk/lib/index.js:14:16
    at action (/Applications/poi.app/Contents/Resources/app.asar/views/middlewares/promise-action.js:55:12)
    at PluginManager.installPlugin (/Applications/poi.app/Contents/Resources/app.asar/views/services/plugin-manager.js:428:7)
    at <anonymous>

    in Unknown
    in Connect(Component)
    in I18n
    in Translate(Connect(Component))
    in div
    in Prophet
    in Connect(Prophet)
    in I18n
    in Translate(Connect(Prophet))
    in div
    in PluginWrap
    in I18n
    in Translate(PluginWrap)
    in div
    in div
    in div
    in TabContentsUnion
    in Connect(TabContentsUnion)
    in div
    in div
    in t
    in div
    in ControlledTabArea
    in Connect(ControlledTabArea)
    in I18n
    in Translate(Connect(ControlledTabArea))
    in poi-nav-tabs
    in poi-nav
    in div
    in poi-app
    in PoiApp
    in Connect(PoiApp)
    in poi-main
    in Poi
    in Connect(Poi)
    in Provider
    in I18nextProvider

**Comment by KagamiChan** [comment]
请删除 `~/node_modules` 文件夹

**Comment by KagamiChan** [comment]
@sapphirecxm 请删除 `~/node_modules` 文件夹

**Comment by sapphirecxm** [comment]
@KagamiChan 已解决，非常感谢
