### ISSUE TITLE
一心二用插件出现问题

### ISSUE THREAD

**Issue by Illusorys** [poooi/poi#1851]
一心二用插件突然只显示很狭长的横框 而且UI条全没了，请问下如何解决，且无法正常点击关闭按钮关闭
类似
东西东西东西东西东西东西东西东西东西
东西东西东西东西东西东西东西东西东西
黑屏黑屏黑屏黑屏黑屏黑屏黑屏黑屏黑屏
黑屏黑屏黑屏黑屏黑屏黑屏黑屏黑屏黑屏
黑屏黑屏黑屏黑屏黑屏黑屏黑屏黑屏黑屏
黑屏黑屏黑屏黑屏黑屏黑屏黑屏黑屏黑屏
黑屏黑屏黑屏黑屏黑屏黑屏黑屏黑屏黑屏
黑屏黑屏黑屏黑屏黑屏黑屏黑屏黑屏黑屏

**Comment by Illusorys** [comment]
POI版本8.2.0稳定版，插件版本3.0.0 WIN764位

**Comment by KagamiChan** [comment]
@Illusorys 在激活这个全黑的窗口的情况下按 ctrl + shift + i，然后把弹出来的窗口的 console 里面显示的内容截图或者复制发一下

**Comment by Illusorys** [comment]
额，我升级了9.0测试版就好了。。。现在是9.0.0正常了

**Comment by wyj19901021** [comment]
C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:168 Uncaught TypeError: _react.default.createRef is not a function
    at ControlBar (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\views\control.js:63:29)
    at constructClassInstance (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:109:354)
    at beginWork (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:133:440)
    at d (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:161:93)
    at f (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:161:417)
    at g (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:162:149)
    at m (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:169:173)
    at w (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:168:413)
    at z (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:167:32)
    at u (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:165:441)
    at Object.updateContainer (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:175:31)
    at C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:225:260
    at Object.unbatchedUpdates (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:171:453)
    at Pg (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:225:230)
    at Object.render (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:227:304)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\views\index.js:172:19)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\views\index.js:175:3)
    at Module._compile (module.js:569:30)
    at Module._compile (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:580:10)
    at Object.newLoader [as .js] (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\pirates\lib\index.js:96:7)
    at Module.load (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\new-window.js:18:1)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\new-window.js:63:3)
    at Module._compile (module.js:569:30)
    at Module._compile (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:580:10)
    at Object.newLoader [as .js] (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\pirates\lib\index.js:96:7)
    at Module.load (C:\Users\Administrator\AppData\Local\Programs\poi\resources\app\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at file:///C:/Users/Administrator/AppData/Roaming/poi/plugins/node_modules/poi-plugin-new-window/index.html:18:5

**Comment by wyj19901021** [comment]
@KagamiChan 系统与版本和LZ一样

**Comment by KagamiChan** [comment]
@wyj19901021 请提供我下面回复说到的内容以便更快定位问题

**Comment by wyj19901021** [comment]
@KagamiChan 发了，在@的楼上

**Comment by KagamiChan** [comment]
7e9b242060487e10a5693c57aad2bf34b14af2d5 修复了
删除插件再安装的话应该不会安装到不兼容的新版本
