### ISSUE TITLE
poi9.0.2界面过小而且不能修改大小

### ISSUE THREAD

**Issue by yamato2199** [poooi/poi#1969]
**poi 版本 / poi version:**
9.0.2

**操作系统 / OS:**

win10 1803

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
今天从9.0.0beta2更新到了9.0.2，以前是用分离游戏画面和数据显示界面
今天更新了9.0.2之后有选了下面的那几个选项（虽然不知道是做什么用的）
于是就变成了非常小的界面，而且也没有了游戏画面，大小也不能拉伸

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

Error: Cannot find module 'views/createStore'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (C:\Users\User\poi7.9\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\poi\plugins\node_modules\poi-plugin-senka-calc/index.es:6:1)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\poi\plugins\node_modules\poi-plugin-senka-calc\index.es:110:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Module._compile (C:\Users\User\poi7.9\resources\app.asar\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Object.newLoader [as .es] (C:\Users\User\poi7.9\resources\app.asar\node_modules\pirates\lib\index.js:88:7)
    at Module.load (C:\Users\User\poi7.9\resources\app.asar\node_modules\coffee-react\lib\register.js:44:34)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Promise.resolve.then (C:\Users\User\poi7.9\resources\app.asar\views\services\plugin-manager-utils.js:304:83)
    at tryCatcher (C:\Users\User\poi7.9\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\User\poi7.9\resources\app.asar\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\User\poi7.9\resources\app.asar\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromiseCtx (C:\Users\User\poi7.9\resources\app.asar\node_modules\bluebird\js\release\promise.js:606:10)
    at Async._drainQueue (C:\Users\User\poi7.9\resources\app.asar\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (C:\Users\User\poi7.9\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Users\User\poi7.9\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
enablePlugin @ C:\Users\User\poi7.9\resources\app.asar\views\services\plugin-manager-utils.js:314
internal/modules/cjs/loader.js:604 Uncaught Error: Cannot find module 'lodash'
internal/modules/cjs/loader.js:604 Uncaught Error: Cannot find module 'lodash'
C:\Users\User\poi7.9\resources\app.asar\views\services\plugin-manager-utils.js:173 poi-plugin-kcwiki-report: No translate file found.
updateI18n @ C:\Users\User\poi7.9\resources\app.asar\views\services\plugin-manager-utils.js:173
C:\Users\User\poi7.9\resources\app.asar\views\components\settings\misc\wctf-db.js:173 No update for wctf-db, current: 2018.9.16, remote: 2018.9.16
/C:/Users/User/AppData/Roaming/poi/plugins/node_modules/poi-plugin-hensei-nikki/assets/ship-item.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
C:\Users\User\AppData\Roaming\poi\plugins\node_modules\poi-plugin-wheres-my-fuel-gone\views\redux\readDataFiles.js:91 Unable to read C:\Users\User\AppData\Roaming\poi\wheres-my-fuel-gone\1000308\filters.json:  Error: ENOENT: no such file or directory, open 'C:\Users\User\AppData\Roaming\poi\wheres-my-fuel-gone\1000308\filters.json'
_ref4 @ C:\Users\User\AppData\Roaming\poi\plugins\node_modules\poi-plugin-wheres-my-fuel-gone\views\redux\readDataFiles.js:91
C:\Users\User\poi7.9\resources\app.asar\views\components\settings\misc\fcd.js:105 No newer version of map: current 2018/09/13/01, remote 2018/09/13/01, mode default
C:\Users\User\poi7.9\resources\app.asar\views\components\settings\misc\fcd.js:105 No newer version of shipavatar: current 2018/09/08/02, remote 2018/09/08/02, mode default
C:\Users\User\poi7.9\resources\app.asar\views\components\settings\misc\fcd.js:105 No newer version of shiptag: current 2018/09/12/01, remote 2018/09/12/01, mode default
C:\Users\User\poi7.9\resources\app.asar\views\components\settings\misc\fcd.js:114 Update fcd from https://poi.io/fcd/ successfully in mode default.
C:\Users\User\poi7.9\resources\app.asar\views\services\update.js:86 Remote version: v9.0.2. Current version: 9.0.2
C:\Users\User\poi7.9\resources\app.asar\views\env-parts\devtool-message.js:18 This is poi@9.0.2 on win32 x64 with Electron@3.0.0-beta.12,
        PLUGINS: poi-plugin-prophet@7.7.2, poi-plugin-exp-calc@4.1.1, poi-plugin-expedition@3.3.2, poi-plugin-quest-info@5.3.2, poi-plugin-hensei-nikki@4.0.4, poi-plugin-map-hp@4.0.3, poi-plugin-secretary@2.0.3, poi-plugin-almanac@2.0.0, poi-plugin-anchorage-repair@0.6.1, poi-plugin-akashic-records@7.1.1, poi-plugin-battle-detail@5.1.0, poi-plugin-wheres-my-fuel-gone@0.7.2, poi-plugin-item-improvement@7.1.1, poi-plugin-ship-info@6.1.3, poi-plugin-item-info@4.1.1, poi-plugin-navy-album@1.0.1, poi-plugin-k2badge@0.3.2, poi-plugin-new-window@3.1.1, poi-plugin-kcwiki-report@3.1.2, poi-plugin-report@3.8.1, poi-plugin-subtitle@1.2.16, resources@2.2.3,
        FCD: map@2018/09/13/01, maphp@2016/08/20/01, shiptag@2018/09/12/01, shipavatar@2018/09/08/02
![image](https://user-images.githubusercontent.com/27760521/45595397-483b4900-b9ee-11e8-99b0-eac157c62b2a.png)

这些是concole里的报错

**Comment by KochiyaOcean** [comment]
右键托盘图标的菜单，选择 poi => 重置分辨率

**Comment by yamato2199** [comment]
> 右键托盘图标的菜单，选择 poi => 重置分辨率

已解决，谢谢
