### ISSUE TITLE
9.0.3版本一心二用仍旧无限黑板+关闭不能

### ISSUE THREAD

**Issue by sadarthur** [poooi/poi#1981]
**poi 版本 / poi version:** 
9.0.3

**操作系统 / OS:**
 Win10 1803 (17134.285)

**插件名和版本 / Plugin name & version:**

一心二用（3.1.1）

**你遇到了什么样的问题 / The problem you've met:**
点开就黑板，按右上角关闭都无效。必须用任务管理器整个关掉POI

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

TypeError: Cannot read property 'map' of undefined
    at ControlBar.render (C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\views\control.js:466:36)
    at Kg (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:167:226)
    at Rg (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:180:75)
    at xh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:202:22)
    at yh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:203:234)
    at Vh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:212:353)
    at Yh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:278)
    at Wh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:113)
    at Ah (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:209:281)
    at og (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:207:333)
    at Object.enqueueSetState (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:148:225)
    at ControlBar.F.setState (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:357)
    at ControlBar.componentDidMount (C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\views\control.js:311:10)

Xg @ C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:188
C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:188 TypeError: Cannot read property 'removeEventListener' of null
    at NavigatorBar.componentWillUnmount (C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\views\navigator-bar.js:159:13)
    at $g (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:189:191)
    at ah (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:193:315)
    at ai (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:217:52)
    at Vh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:212:374)
    at Yh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:278)
    at Wh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:113)
    at Ah (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:209:281)
    at og (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:207:333)
    at Object.enqueueSetState (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:148:225)
    at ControlBar.F.setState (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:357)
    at ControlBar.componentDidMount (C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\views\control.js:311:10)

Xg @ C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:188
C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\new-window.js:37 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at remote.getCurrentWebContents.on (C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\new-window.js:37:15)
    at CallbacksRegistry.apply (C:\Users\nabaichuan\Desktop\舰C\POI\resources\electron.asar\common\api\callbacks-registry.js:47:25)
    at EventEmitter.ipcRenderer.on (C:\Users\nabaichuan\Desktop\舰C\POI\resources\electron.asar\renderer\api\remote.js:284:21)
    at EventEmitter.emit (events.js:182:13)

C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\views\control.js:466 Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at ControlBar.render (C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\views\control.js:466:36)
    at Kg (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:167:226)
    at Rg (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:180:75)
    at xh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:202:22)
    at yh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:203:234)
    at Vh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:212:353)
    at Yh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:278)
    at Wh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:113)
    at Ah (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:209:281)
    at og (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:207:333)
    at Object.enqueueSetState (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:148:225)
    at ControlBar.F.setState (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:357)
    at ControlBar.componentDidMount (C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\views\control.js:311:10)

C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\fs-extra\lib\ensure\file.js:16 Uncaught TypeError: callback is not a function
    at fs.exists.fileExists (C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\fs-extra\lib\ensure\file.js:16:28)
    at suppressedCallback (fs.js:238:5)
    at FSReqWrap.oncomplete (fs.js:169:20)

C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\jsonfile\index.js:40 Uncaught TypeError: callback is not a function
    at C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\jsonfile\index.js:40:16
    at C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)

C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\jsonfile\index.js:46 Uncaught TypeError: callback is not a function
    at C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\jsonfile\index.js:46:5
    at C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)

3index.html:1 Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. https://www.chromestatus.com/feature/5082396709879808

**Comment by KagamiChan** [comment]
删掉 `%appdata%/poi` 下面的 `new-window` 文件夹试试看

**Comment by sadarthur** [comment]
> 删掉 `%appdata%/poi` 下面的 `new-window` 文件夹试试看

试过了。再用任务管理器关掉整个POI后。进入到 user/appdata/ roaming/ poi 后找到new-window彻底删除。然后重开POI再点开一心二用还是老样子

C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:188 TypeError: Cannot read property 'map' of undefined
    at ControlBar.render (C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\views\control.js:466:36)
    at Kg (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:167:226)
    at Rg (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:180:75)
    at xh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:202:22)
    at yh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:203:234)
    at Vh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:212:353)
    at Yh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:278)
    at Wh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:113)
    at Ah (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:209:281)
    at og (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:207:333)
    at Object.enqueueSetState (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:148:225)
    at ControlBar.F.setState (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:357)
    at ControlBar.componentDidMount (C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\views\control.js:311:10)

Xg @ C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:188
C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:188 TypeError: Cannot read property 'removeEventListener' of null
    at NavigatorBar.componentWillUnmount (C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\views\navigator-bar.js:159:13)
    at $g (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:189:191)
    at ah (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:193:315)
    at ai (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:217:52)
    at Vh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:212:374)
    at Yh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:278)
    at Wh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:113)
    at Ah (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:209:281)
    at og (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:207:333)
    at Object.enqueueSetState (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:148:225)
    at ControlBar.F.setState (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:357)
    at ControlBar.componentDidMount (C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\views\control.js:311:10)

Xg @ C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:188
C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\views\control.js:466 Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at ControlBar.render (C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\views\control.js:466:36)
    at Kg (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:167:226)
    at Rg (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:180:75)
    at xh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:202:22)
    at yh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:203:234)
    at Vh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:212:353)
    at Yh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:278)
    at Wh (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:113)
    at Ah (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:209:281)
    at og (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:207:333)
    at Object.enqueueSetState (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:148:225)
    at ControlBar.F.setState (C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:357)
    at ControlBar.componentDidMount (C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\views\control.js:311:10)

C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\new-window.js:37 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at remote.getCurrentWebContents.on (C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\poi-plugin-new-window\new-window.js:37:15)
    at CallbacksRegistry.apply (C:\Users\nabaichuan\Desktop\舰C\POI\resources\electron.asar\common\api\callbacks-registry.js:47:25)
    at EventEmitter.ipcRenderer.on (C:\Users\nabaichuan\Desktop\舰C\POI\resources\electron.asar\renderer\api\remote.js:284:21)
    at EventEmitter.emit (events.js:182:13)

C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\jsonfile\index.js:30 Uncaught TypeError: callback is not a function
    at ReadFileContext.<anonymous> (C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\jsonfile\index.js:30:21)
    at ReadFileContext.callback (C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\graceful-fs\graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:352:13)

C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\jsonfile\index.js:46 Uncaught TypeError: callback is not a function
    at C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\jsonfile\index.js:46:5
    at C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)

C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\fs-extra\lib\ensure\file.js:11 Uncaught TypeError: callback is not a function
    at fs.writeFile.err (C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\fs-extra\lib\ensure\file.js:11:7)
    at C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\Users\nabaichuan\AppData\Roaming\poi\plugins\node_modules\graceful-fs\graceful-fs.js:43:10
    at C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:169:20)

**Comment by KagamiChan** [comment]
`%UserProfile%` 下面有 `node_modules` 文件夹吗，有的话请删掉

**Comment by sadarthur** [comment]
> `%UserProfile%` 下面有 `node_modules` 文件夹吗，有的话请删掉

啊。好像可以正常用了。我把C:\Users\nabaichuan\AppData\Roaming\poi\plugins里的node_modules以及C:\Users\nabaichuan\Desktop\舰C\POI\resources\app.asar.unpacked里的node_modules删掉再重启POI后重新下载一心二用插件再打开就可以正常使用了，也可以正常退出了
