### ISSUE TITLE
Invariant Violation: Minified React error #254

### ISSUE THREAD

**Issue by deeporist** [poooi/poi#1987]
**poi 版本 / poi version:**
9.0.3

**操作系统 / OS:**

win 8.1 x64
**插件名和版本 / Plugin name & version:**

航海日志  戰鬥記錄

**你遇到了什么样的问题 / The problem you've met:**
打開后不顯示任何東西

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

Invariant Violation: Minified React error #254; visit https://reactjs.org/docs/error-decoder.html?invariant=254&args[]=inner for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at invariant (V:\poi-win\resources\app.asar\node_modules\fbjs\lib\invariant.js:42:15)
    at A (V:\poi-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:14:166)
    at ug (V:\poi-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:153:440)
    at V:\poi-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:163:57
    at Ig (V:\poi-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:166:400)
    at Kg (V:\poi-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:167:283)
    at Rg (V:\poi-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:180:75)
    at xh (V:\poi-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:202:22)
    at yh (V:\poi-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:203:234)
    at Vh (V:\poi-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:212:353)
    at Yh (V:\poi-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:278)
    at Wh (V:\poi-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:113)
    at Ah (V:\poi-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:209:281)
    at og (V:\poi-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:207:333)
    at Object.enqueueSetState (V:\poi-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:148:225)
    at PluginWindowWrap.F.setState (V:\poi-win\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:357)
    at externalWindow.addEventListener.e (V:\poi-win\resources\app.asar\views\plugin-window-wrapper.js:183:14)

    in Uncontrolled(Tabs)
    in div
    in MainAreaImpl
    in Connect(MainAreaImpl)
    in div
    in PluginWrap
    in I18n
    in Translate(PluginWrap)
    in div
    in PluginWindowWrap
    in div
    in div
    in t
    in div
    in ControlledTabArea
    in Connect(ControlledTabArea)
    in I18n
    in Translate(Connect(ControlledTabArea))
    in poi-nav-tabs
    in poi-nav
    in div
    in poi-app
    in PoiApp
    in Connect(PoiApp)
    in poi-main
    in Poi
    in Connect(Poi)
    in Provider
    in I18nextProvider

在chrome上玩的, poi游戲分辨率調成0x0, 開了一個端口給chrome代理，poi走鍋go的代理。神奇的是即便我把(V:\poi-win\resources\app.asar\node_modules這個文件夾改名，這個錯誤仍然不變。

**Comment by KagamiChan** [comment]
看一下你的 %userprofile% 下面有没有 node_modules 文件夹，有的话删掉

**Comment by KagamiChan** [comment]
其它的打开新窗口的插件都能运行吗，比如装备改修，航海日志

**Comment by KagamiChan** [comment]
就是 `C:/Users/{你的用户名}` 下面有没有 node_modules 文件夹

性能监视器是已知问题，和你遇到的错误无关

**Comment by deeporist** [comment]
@KagamiChan 
C:/Users/{你的用户名}
這個路徑下沒有你説的這個文件夾

**Comment by KochiyaOcean** [comment]
@deeporist 重新下载安装包安装看看

**Comment by KagamiChan** [comment]
再试一下扩展程式里面的自动修复

**Comment by deeporist** [comment]
@KagamiChan 
剛才試著直接把c:\user\xxx\appdata\roaming\poi這個文件夾直接刪掉再開啓poi讓它重建用戶目錄, 然後重裝所有擴展程式，結果依然沒有變化，衹有未卜先知能用，航海日志和戰鬥記錄還是打開沒有東西錯誤還是這個#254. 
姑且貼一下所有包含node_modules的路徑
(我把c:\user\xxx\appdata\roaming\poi mklink /d 到了 h:\poi)
H:\POI\plugins\node_modules
H:\POI\plugins\node_modules\poi-plugin-akashic-records\node_modules
H:\POI\plugins\node_modules\poi-plugin-battle-detail\node_modules
H:\POI\wctf-db\node_modules
(主程式文件夾)
H:\poi-win\resources\app.asar.unpacked\node_modules
H:\poi-win\resources\app.asar.unpacked\node_modules\npm\node_modules

**Comment by KagamiChan** [comment]
你有安装一心二用插件吗，它是不是可以正常打开

**Comment by deeporist** [comment]
@KagamiChan 
這是新窗口的控制臺的結果
H:\POI\plugins\node_modules\poi-plugin-new-window\views\control.js:308 SyntaxError: C:\Users\mok\AppData\Roaming\poi\new-window\bookmark.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>:null:null)
    at v:\poi-win\resources\app.asar\node_modules\jsonfile\index.js:33:18
    at v:\poi-win\resources\app.asar\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)

componentDidMount @ H:\POI\plugins\node_modules\poi-plugin-new-window\views\control.js:308
console.log(require.resolve('react'))
VM700:1 v:\poi-win\resources\app.asar\node_modules\react\index.js

開了一心二用后在主程式的控制臺里的結果和上面一樣

但是航海日志和戰鬥記錄還是沒變化。。。。

**Comment by deeporist** [comment]
@KagamiChan 
好了！ 哎呀真不好意費了您那麽多時間精力，原來是我做目錄鏈接導致的問題。我是把poi的用戶目錄從c盤鏈接到了h盤，poi在之前一次更新后文件數量劇增，我就把poi主程式從h盤鏈接到了v盤。但是啓動都是從h盤的鏈接目錄里啓動的，可能是這其中的文件調用路徑沒有跟進上吧。。。現在我直接啓動鏈接到v盤的主程式的快捷方式后問題都沒有了，航海日志和戰鬥記錄都能正常顯示了，再次非常感謝您，給您添麻煩了。。。。

**Comment by KagamiChan** [comment]
没关系，主要我们开发的时候比较少考虑目录链接的情况，所以也不确定具体会有什么表现
