### ISSUE TITLE
求助 战果计算突然变乌龟了 自动修复 删除文件夹重装均无效

### ISSUE THREAD

**Issue by sinlolicon** [poooi/poi#2019]
TypeError: Cannot read property 'length' of null
    at Object.acquireContext (C:\Users\sin\AppData\Roaming\poi\plugins\node_modules\poi-plugin-achievement\assets\Chart.js:10475:20)
    at new Chart.Controller (C:\Users\sin\AppData\Roaming\poi\plugins\node_modules\poi-plugin-achievement\assets\Chart.js:3891:26)
    at new Chart (C:\Users\sin\AppData\Roaming\poi\plugins\node_modules\poi-plugin-achievement\assets\Chart.js:6278:21)
    at createChart (C:\Users\sin\AppData\Roaming\poi\plugins\node_modules\poi-plugin-achievement\views/calendar.es:36:15)
    at SenkaCalendar.createChart [as componentDidMount] (C:\Users\sin\AppData\Roaming\poi\plugins\node_modules\poi-plugin-achievement\views/calendar.es:131:5)
    at ai (C:\Users\sin\AppData\Local\poi\app-7.0.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:219:412)
    at Vh (C:\Users\sin\AppData\Local\poi\app-7.0.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:212:374)
    at Yh (C:\Users\sin\AppData\Local\poi\app-7.0.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:278)
    at Wh (C:\Users\sin\AppData\Local\poi\app-7.0.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:113)
    at Ah (C:\Users\sin\AppData\Local\poi\app-7.0.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:209:281)
    at og (C:\Users\sin\AppData\Local\poi\app-7.0.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:207:333)
    at Object.enqueueSetState (C:\Users\sin\AppData\Local\poi\app-7.0.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:148:225)
    at PluginWindowWrap.F.setState (C:\Users\sin\AppData\Local\poi\app-7.0.2\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:357)
    at externalWindow.addEventListener.e (C:\Users\sin\AppData\Local\poi\app-7.0.2\resources\app.asar\views\plugin-window-wrapper.js:183:14)

    in SenkaCalendar
    in div
    in Row
    in div
    in PluginAchievement
    in Connect(PluginAchievement)
    in div
    in PluginWrap
    in I18n
    in Translate(PluginWrap)
    in div
    in PluginWindowWrap
    in div
    in div
    in t
    in div
    in ControlledTabArea
    in Connect(ControlledTabArea)
    in I18n
    in Translate(Connect(ControlledTabArea))
    in poi-nav-tabs
    in poi-nav
    in div
    in poi-app
    in PoiApp
    in Connect(PoiApp)
    in poi-main
    in Poi
    in Connect(Poi)
    in Provider
    in I18nextProvider

**Comment by KochiyaOcean** [comment]
@sinlolicon 等更新

**Comment by KagamiChan** [comment]
cc @a26214311
