### ISSUE TITLE
耗资纪录变成龟了

### ISSUE THREAD

**Issue by ndrhng1234** [poooi/poi#2030]
**poi 版本 / poi version:**
9.0.4

**操作系统 / OS:**

W10专业版 1709 16299.785
**插件名和版本 / Plugin name & version:**
耗资纪录 .07.4

耗资纪录 0.7.4

**你遇到了什么样的问题 / The problem you've met:**

耗资记录变成龟了

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

RangeError: Unsupported time zone specified undefined
    at new DateTimeFormat (native)
    at Date.toLocaleString (native)
    at DataRow.sumRow.recordData [as sumRow] (C:\Users\andre\AppData\Roaming\poi\plugins\node_modules\poi-plugin-wheres-my-fuel-gone\views\tab_main\data_row.js:65:46)
    at DataRow.render (C:\Users\andre\AppData\Roaming\poi\plugins\node_modules\poi-plugin-wheres-my-fuel-gone\views\tab_main\data_row.js:104:12)
    at Kg (D:\game\舰C用\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:167:226)
    at Rg (D:\game\舰C用\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:180:75)
    at xh (D:\game\舰C用\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:202:22)
    at yh (D:\game\舰C用\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:203:234)
    at Vh (D:\game\舰C用\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:212:353)
    at Yh (D:\game\舰C用\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:278)
    at Wh (D:\game\舰C用\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:113)
    at Ah (D:\game\舰C用\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:209:281)
    at og (D:\game\舰C用\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:207:333)
    at Object.enqueueSetState (D:\game\舰C用\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:148:225)
    at PluginWindowWrap.F.setState (D:\game\舰C用\poi\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:357)
    at externalWindow.addEventListener.e (D:\game\舰C用\poi\resources\app.asar\views\plugin-window-wrapper.js:183:14)

    in DataRow
    in Connect(DataRow)
    in div
    in MainTable
    in div
    in TabMain
    in Connect(TabMain)
    in div
    in div
    in PluginMain
    in Connect(PluginMain)
    in div
    in PluginWrap
    in I18n
    in Translate(PluginWrap)
    in div
    in PluginWindowWrap
    in div
    in div
    in t
    in div
    in ControlledTabArea
    in Connect(ControlledTabArea)
    in I18n
    in Translate(Connect(ControlledTabArea))
    in poi-nav-tabs
    in poi-nav
    in div
    in poi-app
    in PoiApp
    in Connect(PoiApp)
    in poi-main
    in Poi
    in Connect(Poi)
    in Provider
    in I18nextProvider

**Comment by KochiyaOcean** [comment]
@ndrhng1234 你的系统时区设置是什么
