### ISSUE TITLE
海域血量插件bug?

### ISSUE THREAD

**Issue by mic4126** [poooi/poi#2072]
**poi 版本 / poi version:**
10.0.0
**操作系统 / OS:**
在Windows 10 2016 LTSB玩 (14393.2665)
但poi偵查到是Windows Server 2016

**插件名和版本 / Plugin name & version:**
海域血量 5.00

**你遇到了什么样的问题 / The problem you've met:**

RangeError: Unsupported time zone specified undefined
    at new DateTimeFormat (native)
    at Date.toLocaleString (native)
    at PoiPluginMapHp.render (C:\Users\michael\AppData\Roaming\poi\plugins\node_modules\poi-plugin-map-hp\index.js:213:118)
    at Sg (E:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:169:192)
    at Rg (E:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:168:317)
    at Vg (E:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:176:13)
    at Hh (E:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:214:22)
    at Ih (E:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:215:277)
    at ji (E:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:230:348)
    at ki (E:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:229:144)
    at Fh (E:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:226:261)
    at bg (E:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:224:86)
    at Object.enqueueSetState (E:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:140:228)
    at PoiPluginMapHp.F.setState (E:\poi\resources\app.asar\node_modules\react\cjs\react.production.min.js:13:224)
    at value (C:\Users\michael\AppData\Roaming\poi\plugins\node_modules\poi-plugin-map-hp\index.js:172:16)
    at parseResponses (E:\poi\resources\app.asar\views\env-parts\data-resolver.js:115:10)
    at resolveResponses (E:\poi\resources\app.asar\views\env-parts\data-resolver.js:123:7)
    at handleProxyGameOnResponse (E:\poi\resources\app.asar\views\env-parts\data-resolver.js:138:7)
    at CallbacksRegistry.apply (E:\poi\resources\electron.asar\renderer\callbacks-registry.js:47:25)
    at handleMessage (E:\poi\resources\electron.asar\renderer\api\remote.js:285:21)
    at EventEmitter.ipcRenderer.on.args (E:\poi\resources\electron.asar\renderer\api\remote.js:275:7)
    at EventEmitter.emit (events.js:182:13)

    in PoiPluginMapHp
    in Connect(PoiPluginMapHp)
    in NamespacesConsumerComponent
    in WithMergedOptions
    in WithMergedOptions(NamespacesConsumerComponent)
    in LoadNamespace
    in WithMergedOptions
    in LoadNamespace(Connect(PoiPluginMapHp))
    in div
    in Blueprint3.Card
    in div
    in StyledComponent
    in PluginWrap
    in NamespacesConsumerComponent
    in WithMergedOptions
    in WithMergedOptions(NamespacesConsumerComponent)
    in LoadNamespace
    in WithMergedOptions
    in LoadNamespace(PluginWrap)
    in div
    in StyledComponent
    in div
    in StyledComponent
    in TabContentsUnion
    in Connect(TabContentsUnion)
    in div
    in StyledComponent
    in div
    in t
    in div
    in StyledComponent
    in ControlledTabArea
    in Connect(ControlledTabArea)
    in NamespacesConsumerComponent
    in WithMergedOptions
    in WithMergedOptions(NamespacesConsumerComponent)
    in LoadNamespace
    in WithMergedOptions
    in LoadNamespace(Connect(ControlledTabArea))
    in poi-nav-tabs
    in poi-nav
    in div
    in StyledComponent
    in div
    in StyledComponent
    in PoiApp
    in Connect(PoiApp)
    in poi-main
    in Blueprint3.ResizeSensor
    in ThemeProvider
    in Poi
    in Connect(Poi)
    in Provider
    in I18nextProvider

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
發現bug 之後發現艦娘的時鐘慢了8小時
我平時用Windows 自帶的Remote Desktop 功能玩,不知有沒有關係

![image](https://user-images.githubusercontent.com/4671533/50575374-2a78df00-0e39-11e9-92d3-63886caa91cd.png)

**Comment by KagamiChan** [comment]
比较奇特，没有认出你的系统的时区

如果在 console 里面输入 `Intl.DateTimeFormat().resolvedOptions().timeZone`，打出来的结果是什么？

此外时钟慢了 8 个小时也没法玩游戏了吧……

**Comment by mic4126** [comment]
![image](https://user-images.githubusercontent.com/4671533/50592901-0ec11780-0ed1-11e9-8abe-a313dd311569.png)

一開艦娘的時鐘是正常,是玩了一段時間才會發生


重新開poi+KCV F5 之後的結果
![image](https://user-images.githubusercontent.com/4671533/50593313-cf93c600-0ed2-11e9-92ba-401b82f6b934.png)

**Comment by KagamiChan** [comment]
你的作业系统有什么特殊之处吗？这种突然解析不到时区的问题我是第一次遇见

**Comment by mic4126** [comment]
只是在Windows 10 1607 LTSB 版玩
原版M$ image
沒有Microsoft Store 和 Edge 

還有一點,我是在虛擬機玩，所以會一開就開2-3星期
