### ISSUE TITLE
未卜先知故障

### ISSUE THREAD

**Issue by flybikeGx** [poooi/poi#2085]
**poi 版本 / poi version: 10.1.0**

**操作系统 / OS: macOS 10.14.2**

**插件名和版本 / Plugin name & version: 未卜先知 7.11.1**

**你遇到了什么样的问题 / The problem you've met: **
```
TypeError: _lodash.default.sumBy is not a function
    at BattleViewArea (/Users/gx/Library/Application Support/poi/plugins/node_modules/poi-plugin-prophet/views/battle-view-area.js:129:43)
    at Vg (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:174:125)
    at Hh (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:214:22)
    at Ih (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:215:277)
    at ji (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:230:348)
    at ki (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:229:144)
    at Fh (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:226:261)
    at bg (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:224:86)
    at Object.enqueueSetState (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:140:228)
    at Provider.F.setState (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react/cjs/react.production.min.js:13:224)
    at /Applications/poi.app/Contents/Resources/app.asar/node_modules/react-redux/lib/components/Provider.js:65:14
    at dispatch (/Applications/poi.app/Contents/Resources/app.asar/node_modules/redux/lib/redux.js:220:7)
    at /Applications/poi.app/Contents/Resources/app.asar/node_modules/redux-thunk/lib/index.js:14:16
    at action (/Applications/poi.app/Contents/Resources/app.asar/views/middlewares/promise-action.js:55:12)
    at PluginManager.installPlugin (/Applications/poi.app/Contents/Resources/app.asar/views/services/plugin-manager/index.js:349:7)

    in Unknown
    in Connect(Component)
    in NamespacesConsumerComponent
    in WithMergedOptions
    in WithMergedOptions(NamespacesConsumerComponent)
    in LoadNamespace
    in WithMergedOptions
    in LoadNamespace(Connect(Component))
    in div
    in Prophet
    in Connect(Prophet)
    in NamespacesConsumerComponent
    in WithMergedOptions
    in WithMergedOptions(NamespacesConsumerComponent)
    in LoadNamespace
    in WithMergedOptions
    in LoadNamespace(Connect(Prophet))
    in div
    in Blueprint3.Card
    in div
    in StyledComponent
    in PluginWrap
    in NamespacesConsumerComponent
    in WithMergedOptions
    in WithMergedOptions(NamespacesConsumerComponent)
    in LoadNamespace
    in WithMergedOptions
    in LoadNamespace(PluginWrap)
    in div
    in StyledComponent
    in div
    in StyledComponent
    in TabContentsUnion
    in Connect(TabContentsUnion)
    in div
    in StyledComponent
    in div
    in t
    in div
    in StyledComponent
    in ControlledTabArea
    in Connect(ControlledTabArea)
    in NamespacesConsumerComponent
    in WithMergedOptions
    in WithMergedOptions(NamespacesConsumerComponent)
    in LoadNamespace
    in WithMergedOptions
    in LoadNamespace(Connect(ControlledTabArea))
    in poi-nav-tabs
    in poi-nav
    in div
    in StyledComponent
    in div
    in StyledComponent
    in PoiApp
    in Connect(PoiApp)
    in poi-main
    in Blueprint3.ResizeSensor
    in ThemeProvider
    in Poi
    in Connect(Poi)
    in Provider
    in I18nextProvider
```

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related: 无**

以下是Console的打印
```
Scheduling daily refresh at 331200000 (now 1547135905640)
/Applications/poi.app/Contents/Resources/app.asar/views/components/settings/about/update/fcd.js:99 No newer version of map: current 2018/12/27/01, remote 2018/12/27/01, mode default
/Applications/poi.app/Contents/Resources/app.asar/views/components/settings/about/update/fcd.js:99 No newer version of shipavatar: current 2018/09/08/02, remote 2018/09/08/02, mode default
/Applications/poi.app/Contents/Resources/app.asar/views/components/settings/about/update/fcd.js:99 No newer version of shiptag: current 2018/12/27/02, remote 2018/12/27/02, mode default
/Applications/poi.app/Contents/Resources/app.asar/views/components/settings/about/update/fcd.js:108 Update fcd from https://poi.io/fcd/ successfully in mode default.
/Applications/poi.app/Contents/Resources/app.asar/views/components/settings/about/update/wctf-db.js:128 wctf-db updated to 20190107.0.0
/Applications/poi.app/Contents/Resources/app.asar/views/services/update.js:81 Remote version: v10.1.0. Current version: 10.1.0
/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:185 TypeError: _lodash.default.sumBy is not a function
    at BattleViewArea (/Users/gx/Library/Application Support/poi/plugins/node_modules/poi-plugin-prophet/views/battle-view-area.js:129)
    at Vg (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:174)
    at Hh (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:214)
    at Ih (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:215)
    at ji (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:230)
    at ki (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:229)
    at Fh (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:226)
    at bg (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:224)
    at Object.enqueueSetState (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:140)
    at Provider.F.setState (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react/cjs/react.production.min.js:13)
    at /Applications/poi.app/Contents/Resources/app.asar/node_modules/react-redux/lib/components/Provider.js:65
    at dispatch (/Applications/poi.app/Contents/Resources/app.asar/node_modules/redux/lib/redux.js:220)
    at /Applications/poi.app/Contents/Resources/app.asar/node_modules/redux-thunk/lib/index.js:14
    at action (/Applications/poi.app/Contents/Resources/app.asar/views/middlewares/promise-action.js:55)
    at PluginManager.installPlugin (/Applications/poi.app/Contents/Resources/app.asar/views/services/plugin-manager/index.js:349)
ah @ /Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:185
/Applications/poi.app/Contents/Resources/app.asar/views/redux/info/quests.js:541 No quest tracking data!
reducer @ /Applications/poi.app/Contents/Resources/app.asar/views/redux/info/quests.js:541
/Applications/poi.app/Contents/Resources/app.asar/views/redux/index.js:55 Error in extension poi-plugin-prophet TypeError: (0 , _lodash.keyBy) is not a function
    at indexify (/Users/gx/Library/Application Support/poi/plugins/node_modules/poi-plugin-prophet/redux.js:100:44)
    at UseItemReducer (/Users/gx/Library/Application Support/poi/plugins/node_modules/poi-plugin-prophet/redux.js:121:26)
    at combination (/Applications/poi.app/Contents/Resources/app.asar/node_modules/redux/lib/redux.js:451:29)
    at combination (/Applications/poi.app/Contents/Resources/app.asar/views/redux/combine-reducers.js:76:31)
    at /Applications/poi.app/Contents/Resources/app.asar/views/redux/index.js:53:18
    at combination (/Applications/poi.app/Contents/Resources/app.asar/views/redux/combine-reducers.js:76:31)
    at combination (/Applications/poi.app/Contents/Resources/app.asar/views/redux/combine-reducers.js:76:31)
    at dispatch (/Applications/poi.app/Contents/Resources/app.asar/node_modules/redux/lib/redux.js:211:22)
    at /Applications/poi.app/Contents/Resources/app.asar/node_modules/redux-thunk/lib/index.js:14:16
    at action (/Applications/poi.app/Contents/Resources/app.asar/views/middlewares/promise-action.js:55:12)
    at parseResponses (/Applications/poi.app/Contents/Resources/app.asar/views/env-parts/data-resolver.js:98:5)
    at resolveResponses (/Applications/poi.app/Contents/Resources/app.asar/views/env-parts/data-resolver.js:123:7)
    at handleProxyGameOnResponse (/Applications/poi.app/Contents/Resources/app.asar/views/env-parts/data-resolver.js:138:7)
    at CallbacksRegistry.apply (/Applications/poi.app/Contents/Resources/electron.asar/renderer/callbacks-registry.js:47:25)
    at handleMessage (/Applications/poi.app/Contents/Resources/electron.asar/renderer/api/remote.js:285:21)
    at EventEmitter.ipcRenderer.on.args (/Applications/poi.app/Contents/Resources/electron.asar/renderer/api/remote.js:275:7)
    at EventEmitter.emit (events.js:182:13)
(anonymous) @ /Applications/poi.app/Contents/Resources/app.asar/views/redux/index.js:55
/kcs2/resources/ship/remodel/0046_7868.png:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/kcs2/img/common/ship_bg/card/c2.png:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/kcs2/resources/ship/remodel/0101_1441.png:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/kcs2/img/common/ship_bg/card/c1.png:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/kcs2/resources/ship/remodel/0023_6301.png:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/kcs2/resources/ship/remodel/0055_6039.png:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/Applications/poi.app/Contents/Resources/app.asar/views/env-parts/devtool-message.js:13 This is poi@10.1.0 on darwin x64 with Electron@4.0.0,        PLUGINS: poi-plugin-prophet@7.11.1,        FCD: map@2018/12/27/01, shipavatar@2018/09/08/02, shiptag@2018/12/27/02
```

**Comment by KochiyaOcean** [comment]
把 `/User/<username>/node_modules` 删掉看看

**Comment by flybikeGx** [comment]
> 把 `/User/<username>/node_modules` 删掉看看

Thx，已解决
