### ISSUE TITLE
求助...未卜先知變成了

### ISSUE THREAD

**Issue by Kira-kira** [poooi/poi#2103]
**poi 版本 / poi version:**
10.2
**操作系统 / OS:**
window 10 version1803

**插件名和版本 / Plugin name & version:**
未卜先知 8.0.0

**你遇到了什么样的问题 / The problem you've met:**
未卜先知變成了 龟
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
TypeError: Cannot read property 'map' of undefined
    at map (C:\Users\ming\AppData\Roaming\poi\plugins\node_modules\poi-plugin-prophet\index.js:87:36)
    at Array.map (<anonymous>)
    at map (C:\Users\ming\AppData\Roaming\poi\plugins\node_modules\poi-plugin-prophet\index.js:78:109)
    at Array.map (<anonymous>)
    at transformToLibBattleClass (C:\Users\ming\AppData\Roaming\poi\plugins\node_modules\poi-plugin-prophet\index.js:78:70)
    at new Prophet (C:\Users\ming\AppData\Roaming\poi\plugins\node_modules\poi-plugin-prophet\index.js:263:38)
    at sg (C:\Users\ming\Desktop\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:142:201)
    at Rg (C:\Users\ming\Desktop\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:163:149)
    at Vg (C:\Users\ming\Desktop\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:176:13)
    at Hh (C:\Users\ming\Desktop\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:214:22)
    at Ih (C:\Users\ming\Desktop\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:215:277)
    at ji (C:\Users\ming\Desktop\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:230:348)
    at ki (C:\Users\ming\Desktop\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:229:144)
    at Fh (C:\Users\ming\Desktop\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:226:261)
    at bg (C:\Users\ming\Desktop\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:224:86)
    at Object.enqueueSetState (C:\Users\ming\Desktop\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:140:228)
    at Provider.F.setState (C:\Users\ming\Desktop\poi\resources\app.asar\node_modules\react\cjs\react.production.min.js:13:224)
    at C:\Users\ming\Desktop\poi\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:65:14
    at dispatch (C:\Users\ming\Desktop\poi\resources\app.asar\node_modules\redux\lib\redux.js:220:7)
    at C:\Users\ming\Desktop\poi\resources\app.asar\node_modules\redux-thunk\lib\index.js:14:16
    at action (C:\Users\ming\Desktop\poi\resources\app.asar\views\middlewares\promise-action.js:55:12)
    at PluginManager.installPlugin (C:\Users\ming\Desktop\poi\resources\app.asar\views\services\plugin-manager\index.js:343:7)

    in Prophet
    in Connect(Prophet)
    in NamespacesConsumerComponent
    in WithMergedOptions
    in WithMergedOptions(NamespacesConsumerComponent)
    in LoadNamespace
    in WithMergedOptions
    in LoadNamespace(Connect(Prophet))
    in div
    in Blueprint3.Card
    in div
    in StyledComponent
    in PluginWrap
    in NamespacesConsumerComponent
    in WithMergedOptions
    in WithMergedOptions(NamespacesConsumerComponent)
    in LoadNamespace
    in WithMergedOptions
    in LoadNamespace(PluginWrap)
    in div
    in StyledComponent
    in div
    in StyledComponent
    in TabContentsUnion
    in Connect(TabContentsUnion)
    in div
    in StyledComponent
    in div
    in StyledComponent
    in ControlledTabArea
    in Connect(ControlledTabArea)
    in NamespacesConsumerComponent
    in WithMergedOptions
    in WithMergedOptions(NamespacesConsumerComponent)
    in LoadNamespace
    in WithMergedOptions
    in LoadNamespace(Connect(ControlledTabArea))
    in poi-nav-tabs
    in poi-nav
    in div
    in StyledComponent
    in div
    in StyledComponent
    in PoiApp
    in Connect(PoiApp)
    in poi-main
    in Blueprint3.ResizeSensor
    in ThemeProvider
    in Poi
    in Connect(Poi)
    in Provider
    in I18nextProvider

麻煩解答了 謝謝

**Comment by KagamiChan** [comment]
麻烦勾选一下 poi 基本设置里面的「下次启动进入安全模式」，然后重新启动 poi 再登入游戏看看

**Comment by KagamiChan** [comment]
好像没有回复了，关掉 = =
