### ISSUE TITLE
[编程日记]扩展程序出错

### ISSUE THREAD

**Issue by Lenkuroko** [poooi/poi#2128]
**poi 版本 / poi version:**
10.2.4
**操作系统 / OS:**
Windows 10 1809 (OS 17763.194)

**插件名和版本 / Plugin name & version:**
plugin-hensei-nikki    version:4.4.2

**你遇到了什么样的问题 / The problem you've met:**
无法打开 ，重启poi 浏览器在未登入dmm账号（出击界面）时，可以读取数据【能查看以前编辑好的配船配置】，登入后，程序报错
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
TypeError: Cannot read property 'title' of undefined
    at DataModule.componentWillReceiveProps (C:\Users\Lenkuroko\AppData\Roaming\poi\plugins\node_modules\poi-plugin-hensei-nikki\containers\data-module.js:47:60)
    at wf (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:133:83)
    at Og (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:170:180)
    at Tg (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:180:30)
    at bi (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:232:22)
    at ci (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:233:284)
    at Di (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:249:348)
    at Yh (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:248:144)
    at Xh (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:245:332)
    at qf (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:243:86)
    at Object.enqueueSetState (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:130:228)
    at Provider.E.setState (C:\Program Files\poi\resources\app.asar\node_modules\react\cjs\react.production.min.js:13:224)
    at C:\Program Files\poi\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:65:14
    at dispatch (C:\Program Files\poi\resources\app.asar\node_modules\redux\lib\redux.js:220:7)
    at C:\Program Files\poi\resources\app.asar\node_modules\redux-thunk\lib\index.js:14:16
    at action (C:\Program Files\poi\resources\app.asar\views\middlewares\promise-action.js:55:12)
    at parseResponses (C:\Program Files\poi\resources\app.asar\views\env-parts\data-resolver.js:98:5)
    at resolveResponses (C:\Program Files\poi\resources\app.asar\views\env-parts\data-resolver.js:123:7)
    at handleProxyGameOnResponse (C:\Program Files\poi\resources\app.asar\views\env-parts\data-resolver.js:138:7)
    at CallbacksRegistry.apply (C:\Program Files\poi\resources\electron.asar\renderer\callbacks-registry.js:47:25)
    at handleMessage (C:\Program Files\poi\resources\electron.asar\renderer\api\remote.js:285:21)
    at EventEmitter.ipcRenderer.on.args (C:\Program Files\poi\resources\electron.asar\renderer\api\remote.js:275:7)
    at EventEmitter.emit (events.js:182:13)

    in DataModule
    in Connect(DataModule)
    in div
    in HenseiNikki
    in div
    in Blueprint3.Card
    in div
    in StyledComponent
    in tab-area__PluginAppTabpane
    in PluginWrap
    in NamespacesConsumerComponent
    in WithMergedOptions
    in WithMergedOptions(NamespacesConsumerComponent)
    in LoadNamespace
    in WithMergedOptions
    in LoadNamespace(PluginWrap)
    in div
    in StyledComponent
    in tab-contents-union__PoiTabChildPositioner
    in div
    in StyledComponent
    in tab-contents-union__PoiTabContents
    in TabContentsUnion
    in Connect(TabContentsUnion)
    in Connect(TabContentsUnion)
    in div
    in StyledComponent
    in tab-area__PoiTabContainer
    in div
    in t
    in div
    in StyledComponent
    in tab-area__PoiTabsContainer
    in ControlledTabArea
    in Connect(ControlledTabArea)
    in NamespacesConsumerComponent
    in WithMergedOptions
    in WithMergedOptions(NamespacesConsumerComponent)
    in LoadNamespace
    in WithMergedOptions
    in LoadNamespace(Connect(ControlledTabArea))
    in poi-nav-tabs
    in poi-nav
    in div
    in StyledComponent
    in poi-app__PoiAppContainer
    in div
    in StyledComponent
    in poi-app__PoiAppE
    in PoiApp
    in Connect(PoiApp)
    in poi-main
    in Blueprint3.ResizeSensor
    in ThemeProvider
    in Poi
    in Connect(Poi)
    in Provider
    in I18nextProvider

[https://s2.ax1x.com/2019/03/31/ArZFnf.png](url)

**Comment by Asutarotte** [comment]
求解
我也是一樣的問題...
TypeError: Cannot read property 'title' of undefined
    at DataModule.componentWillReceiveProps (C:\Users\shana\AppData\Roaming\poi\plugins\node_modules\poi-plugin-hensei-nikki\containers\data-module.js:47:60)
    at wf (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:133:83)
    at Og (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:170:180)
    at Tg (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:180:30)
    at bi (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:232:22)
    at ci (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:233:284)
    at Di (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:249:348)
    at Yh (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:248:144)
    at Xh (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:245:332)
    at qf (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:243:86)
    at Object.enqueueSetState (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:130:228)
    at Provider.E.setState (D:\poi\resources\app.asar\node_modules\react\cjs\react.production.min.js:13:224)
    at D:\poi\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:65:14
    at dispatch (D:\poi\resources\app.asar\node_modules\redux\lib\redux.js:220:7)
    at D:\poi\resources\app.asar\node_modules\redux-thunk\lib\index.js:14:16
    at Object.action [as dispatch] (D:\poi\resources\app.asar\views\middlewares\promise-action.js:55:12)
    at Object.pluginDidLoad (C:\Users\shana\AppData\Roaming\poi\plugins\node_modules\poi-plugin-hensei-nikki\index.js:183:22)
    at postEnableProcess (D:\poi\resources\app.asar\views\services\plugin-manager\utils.js:439:14)
    at enablePlugin (D:\poi\resources\app.asar\views\services\plugin-manager\utils.js:327:12)

    in DataModule
    in Connect(DataModule)
    in div
    in HenseiNikki
    in div
    in Blueprint3.Card
    in div
    in StyledComponent
    in tab-area__PluginAppTabpane
    in PluginWrap
    in NamespacesConsumerComponent
    in WithMergedOptions
    in WithMergedOptions(NamespacesConsumerComponent)
    in LoadNamespace
    in WithMergedOptions
    in LoadNamespace(PluginWrap)
    in div
    in StyledComponent
    in tab-contents-union__PoiTabChildPositioner
    in div
    in StyledComponent
    in tab-contents-union__PoiTabContents
    in TabContentsUnion
    in Connect(TabContentsUnion)
    in Connect(TabContentsUnion)
    in div
    in StyledComponent
    in tab-area__PoiTabContainer
    in div
    in t
    in div
    in StyledComponent
    in tab-area__PoiTabsContainer
    in ControlledTabArea
    in Connect(ControlledTabArea)
    in NamespacesConsumerComponent
    in WithMergedOptions
    in WithMergedOptions(NamespacesConsumerComponent)
    in LoadNamespace
    in WithMergedOptions
    in LoadNamespace(Connect(ControlledTabArea))
    in poi-nav-tabs
    in poi-nav
    in div
    in StyledComponent
    in poi-app__PoiAppContainer
    in div
    in StyledComponent
    in poi-app__PoiAppE
    in PoiApp
    in Connect(PoiApp)
    in poi-main
    in Blueprint3.ResizeSensor
    in ThemeProvider
    in Poi
    in Connect(Poi)
    in Provider
    in I18nextProvider

**Comment by ruiii** [comment]
编成日记更新至 5.0.1 试试呢？

**Comment by Asutarotte** [comment]
您好，昨天有按檢查更新沒有反應有更新，我是否該先移除再重新安裝?
另外請問如果移除掉編成日記再重安裝我原本儲存的編成紀錄還會在嗎?

Rui <notifications@github.com> 於 2019年4月1日 週一 下午11:42寫道：

**Comment by ruiii** [comment]
@Asutarotte 可以尝试移除后重新安装，纪录不会消失。

**Comment by Asutarotte** [comment]
了解，晚點下班後試試看，感謝您的解答，不行再跟您回報

Rui <notifications@github.com> 於 2019年4月2日 週二 下午3:38寫道：

**Comment by Asutarotte** [comment]
您好，剛剛打開POI自動更新到5.0.1後已正常，感謝

黃謙 <s79236523523@gmail.com> 於 2019年4月2日 週二 下午5:26寫道：
