### ISSUE TITLE
插件经验计算器变成了小乌龟

### ISSUE THREAD

**Issue by ncc1701ed** [poooi/poi#2146]
poi 版本 / poi version:windows 10 版本1809（os内部版本 17763.503）

操作系统 / OS:windows 10 版本1809（os内部版本 17763.503）

插件名和版本 / Plugin name & version:经验计算器 v 4.1.1

你遇到了什么样的问题 / The problem you've met:提示经验计算器出现了某些异常

有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:每次选定开启经验计算器都会发生，提示要汇报给开发者并附上如下代码;

TypeError: Cannot read property 'contains' of null
    at C:\Users\方浩\AppData\Local\Programs\poi\resources\app.asar\node_modules\dom-helpers\query\contains.js:17:17
    at Dropdown.componentWillUpdate (C:\Users\方浩\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-bootstrap\lib\Dropdown.js:170:53)
    at Og (C:\Users\方浩\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:171:33)
    at Tg (C:\Users\方浩\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:180:30)
    at bi (C:\Users\方浩\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:232:22)
    at ci (C:\Users\方浩\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:233:284)
    at Di (C:\Users\方浩\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:249:348)
    at Yh (C:\Users\方浩\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:248:144)
    at Ii (C:\Users\方浩\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:251:256)
    at Cd (C:\Users\方浩\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:85:207)

    in Dropdown
    in Uncontrolled(Dropdown)
    in ShipDropdown
    in div
    in div
    in div
    in ExpCalc
    in ConnectFunction
    in div
    in Blueprint3.Card
    in div
    in StyledComponent
    in tab-area__PluginAppTabpane
    in PluginWrap
    in withI18nextTranslation(PluginWrap)
    in div
    in StyledComponent
    in tab-contents-union__PoiTabChildPositioner
    in div
    in StyledComponent
    in tab-contents-union__PoiTabContents
    in TabContentsUnion
    in ConnectFunction
    in Connect(TabContentsUnion)
    in div
    in StyledComponent
    in tab-area__PoiTabContainer
    in div
    in StyledComponent
    in tab-area__PoiTabsContainer
    in ControlledTabArea
    in ConnectFunction
    in withI18nextTranslation(Connect(ControlledTabArea))
    in poi-nav-tabs
    in poi-nav
    in div
    in StyledComponent
    in poi-app__PoiAppContainer
    in div
    in StyledComponent
    in poi-app__PoiAppE
    in PoiApp
    in ConnectFunction
    in poi-main
    in Blueprint3.ResizeSensor
    in ThemeProvider
    in Poi
    in ConnectFunction
    in Provider
    in I18nextProvider

可以的话请提供开发者工具 Console 选项卡的截图，
开发者工具的打开方式是按 ctrl + shift + i (macOS 上为 ⌥ + ⌘ + i），或游戏区域下方信息栏的最左边齿轮按钮。
Please provide a screenshot of developer tool's console tab, if possible.
To open the dev tool, press ctrl + shift + i (⌥ + ⌘ + i for macOS), or the leftmost gear button on the info bar below the game  
<img width="960" alt="bug" src="https://user-images.githubusercontent.com/51069199/58396342-ce7c5480-807e-11e9-8d1b-280f6e0457f5.PNG">

**Comment by KagamiChan** [comment]
感谢汇报，会在新版本插件中修复

**Comment by KagamiChan** [comment]
新版本已发布
