### ISSUE TITLE
插件海域血量bug

### ISSUE THREAD

**Issue by 313202907** [poooi/poi#2171]
**poi 版本 / poi version:**
10.3.0
**操作系统 / OS:**
Win10 1903（18362.175）

**插件名和版本 / Plugin name & version:**
海域血量6.1.1

**你遇到了什么样的问题 / The problem you've met:**
点击海域血量插件中的设置阈值按钮时，插件崩溃，必须重启插件才能再运行 。错误信息在下方
目前打到E4,，E4是不受影响的，难道只做了E4吗（

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
```
TypeError: Cannot read property 'toString' of null
    at Object.getValueOrEmptyValue (C:\usrApps\poi\resources\app.asar\node_modules\@blueprintjs\core\src\components\forms\numericInputUtils.ts:28:18)
    at new NumericInput (C:\usrApps\poi\resources\app.asar\node_modules\@blueprintjs\core\src\components\forms\numericInput.tsx:207:16)
    at vf (C:\usrApps\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:132:170)
    at Og (C:\usrApps\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:167:149)
    at Tg (C:\usrApps\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:180:30)
    at bi (C:\usrApps\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:232:22)
    at ci (C:\usrApps\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:233:284)
    at Di (C:\usrApps\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:249:348)
    at Yh (C:\usrApps\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:248:144)
    at Ii (C:\usrApps\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:251:256)
    at Cd (C:\usrApps\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:85:207)

    in Blueprint3.NumericInput
    in div
    in div
    in Blueprint3.FormGroup
    in div
    in StyledComponent
    in s__SettingsContainer
    in div
    in div
    in Blueprint3.ResizeSensor
    in div
    in InnerPopper
    in Popper
    in Transition
    in CSSTransition
    in div
    in TransitionGroup
    in Blueprint3.Portal
    in Blueprint3.Overlay
    in span
    in Manager
    in Blueprint3.Popover
    in div
    in StyledComponent
    in s__MapTitle
    in div
    in Unknown
    in ConnectFunction
    in withI18nextTranslation(Connect(Component))
    in div
    in div
    in div
    in StyledComponent
    in s__PluginWrapper
    in PoiPluginMapHp
    in ConnectFunction
    in withI18nextTranslation(Connect(PoiPluginMapHp))
    in div
    in Blueprint3.Card
    in div
    in StyledComponent
    in tab-area__PluginAppTabpane
    in PluginWrap
    in withI18nextTranslation(PluginWrap)
    in div
    in StyledComponent
    in tab-contents-union__PoiTabChildPositioner
    in div
    in StyledComponent
    in tab-contents-union__PoiTabContents
    in TabContentsUnion
    in ConnectFunction
    in Connect(TabContentsUnion)
    in div
    in StyledComponent
    in tab-area__PoiTabContainer
    in div
    in t
    in div
    in StyledComponent
    in tab-area__PoiTabsContainer
    in ControlledTabArea
    in ConnectFunction
    in withI18nextTranslation(Connect(ControlledTabArea))
    in poi-nav-tabs
    in poi-nav
    in div
    in StyledComponent
    in poi-app__PoiAppContainer
    in div
    in StyledComponent
    in poi-app__PoiAppE
    in PoiApp
    in ConnectFunction
    in poi-main
    in Blueprint3.ResizeSensor
    in ThemeProvider
    in Poi
    in ConnectFunction
    in Provider
    in I18nextProvider
```

**Comment by KagamiChan** [comment]
你是设置了 E5 的？

**Comment by 313202907** [comment]
是手残按到前面已经通关的海域就炸了，必须要重启插件，还没打到E5。或许应该把已通关海域的阈值设置按钮取消

**Comment by KagamiChan** [comment]
无法复现……

**Comment by 313202907** [comment]
。。。试了一下身边的设备只有苏菲上有这种情况并且只要点了必定会崩溃，其他几个设备都没这个问题，系统都是1903，poi都是压缩包方法安装的
不行就先关了吧，打扰了- -

**Comment by KagamiChan** [comment]
难道有可能是触摸屏问题……

**Comment by 313202907** [comment]
E4斩杀了，试了下E4E5都是正常的，但是E1~E3还是不行，可能是因为我E1~E3磨血斩杀全程都没有用平板上，所以平板上前几个海域是没有血量数据的？

**Comment by 313202907** [comment]
怎么还加了删除线的。。。请无视删除线

**Comment by 313202907** [comment]
```
{
  "11": {
    "api_id": 11,
    "api_cleared": 1
  },
  "12": {
    "api_id": 12,
    "api_cleared": 1
  },
  "13": {
    "api_id": 13,
    "api_cleared": 1
  },
  "14": {
    "api_id": 14,
    "api_cleared": 1
  },
  "15": {
    "api_id": 15,
    "api_cleared": 0,
    "api_defeat_count": 0,
    "api_required_defeat_count": 4,
    "api_gauge_type": 1,
    "api_gauge_num": 1
  },
  "21": {
    "api_id": 21,
    "api_cleared": 1
  },
  "22": {
    "api_id": 22,
    "api_cleared": 1
  },
  "23": {
    "api_id": 23,
    "api_cleared": 1
  },
  "24": {
    "api_id": 24,
    "api_cleared": 1
  },
  "25": {
    "api_id": 25,
    "api_cleared": 0,
    "api_defeat_count": 0,
    "api_required_defeat_count": 4,
    "api_gauge_type": 1,
    "api_gauge_num": 1
  },
  "31": {
    "api_id": 31,
    "api_cleared": 1
  },
  "32": {
    "api_id": 32,
    "api_cleared": 1
  },
  "33": {
    "api_id": 33,
    "api_cleared": 1
  },
  "34": {
    "api_id": 34,
    "api_cleared": 1
  },
  "35": {
    "api_id": 35,
    "api_cleared": 0,
    "api_defeat_count": 0,
    "api_required_defeat_count": 4,
    "api_gauge_type": 1,
    "api_gauge_num": 1
  },
  "41": {
    "api_id": 41,
    "api_cleared": 1
  },
  "42": {
    "api_id": 42,
    "api_cleared": 1
  },
  "43": {
    "api_id": 43,
    "api_cleared": 1
  },
  "44": {
    "api_id": 44,
    "api_cleared": 1,
    "api_gauge_type": 1,
    "api_gauge_num": 1
  },
  "45": {
    "api_id": 45,
    "api_cleared": 0,
    "api_defeat_count": 0,
    "api_required_defeat_count": 5,
    "api_gauge_type": 1,
    "api_gauge_num": 1
  },
  "51": {
    "api_id": 51,
    "api_cleared": 1
  },
  "52": {
    "api_id": 52,
    "api_cleared": 1,
    "api_gauge_type": 1,
    "api_gauge_num": 1
  },
  "53": {
    "api_id": 53,
    "api_cleared": 1,
    "api_gauge_type": 1,
    "api_gauge_num": 1
  },
  "54": {
    "api_id": 54,
    "api_cleared": 1,
    "api_gauge_type": 1,
    "api_gauge_num": 1
  },
  "55": {
    "api_id": 55,
    "api_cleared": 0,
    "api_defeat_count": 0,
    "api_required_defeat_count": 5,
    "api_gauge_type": 1,
    "api_gauge_num": 1
  },
  "61": {
    "api_id": 61,
    "api_cleared": 1
  },
  "62": {
    "api_id": 62,
    "api_cleared": 1,
    "api_gauge_type": 1,
    "api_gauge_num": 1
  },
  "63": {
    "api_id": 63,
    "api_cleared": 0,
    "api_defeat_count": 1,
    "api_required_defeat_count": 4,
    "api_gauge_type": 1,
    "api_gauge_num": 1
  },
  "71": {
    "api_id": 71,
    "api_cleared": 1,
    "api_gauge_type": 1,
    "api_gauge_num": 1
  },
  "72": {
    "api_id": 72,
    "api_cleared": 0,
    "api_defeat_count": 0,
    "api_required_defeat_count": 3,
    "api_gauge_type": 1,
    "api_gauge_num": 1
  },
  "441": {
    "api_id": 441,
    "api_cleared": 1,
    "api_eventmap": {
      "api_state": 2,
      "api_selected_rank": 4
    },
    "api_sally_flag": [
      1,
      0,
      0
    ],
    "api_gauge_type": 2,
    "api_gauge_num": 1,
    "api_air_base_decks": 1
  },
  "442": {
    "api_id": 442,
    "api_cleared": 1,
    "api_eventmap": {
      "api_state": 2,
      "api_selected_rank": 4
    },
    "api_sally_flag": [
      1,
      0,
      0
    ],
    "api_gauge_type": 2,
    "api_gauge_num": 2,
    "api_air_base_decks": 2
  },
  "443": {
    "api_id": 443,
    "api_cleared": 1,
    "api_eventmap": {
      "api_state": 2,
      "api_selected_rank": 4
    },
    "api_sally_flag": [
      0,
      7,
      0
    ],
    "api_gauge_type": 2,
    "api_gauge_num": 2,
    "api_air_base_decks": 2
  },
  "444": {
    "api_id": 444,
    "api_cleared": 1,
    "api_eventmap": {
      "api_state": 2,
      "api_selected_rank": 4
    },
    "api_sally_flag": [
      0,
      7,
      0
    ],
    "api_gauge_type": 2,
    "api_gauge_num": 1,
    "api_air_base_decks": 2
  },
  "445": {
    "api_id": 445,
    "api_cleared": 0,
    "api_eventmap": {
      "api_now_maphp": 2400,
      "api_max_maphp": 2400,
      "api_state": 1,
      "api_selected_rank": 2
    },
    "api_sally_flag": [
      0,
      7,
      0
    ],
    "api_gauge_type": 2,
    "api_gauge_num": 1,
    "api_air_base_decks": 3
  }
}
```

**Comment by KagamiChan** [comment]
感觉并没有什么问题。阈值设置其实也和海域本身的血量没什么关系

**Comment by KagamiChan** [comment]
试一下输入 `config.set('plugin.maphp.limits')`重置一下设置看看

**Comment by 313202907** [comment]
找不到就暂时算了吧，这个问题或许一般情况下也不会发生，对正在推的图也没什么影响。麻烦dalao了，多谢~

**Comment by 313202907** [comment]
啊好了，不会崩溃了，多谢
