### ISSUE TITLE
秘書化ボイス

### ISSUE THREAD

**Issue by glaciermelt00** [poooi/poi#2172]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by glaciermelt00** [comment]
poi 版本 / poi version:  poi 10.3.0

操作系统 / OS: macOS High Sierra

插件名和版本 / Plugin name & version:  秘書艦ボイス 2.0.3

你遇到了什么样的问题 / The problem you've met: プラグイン不具合

有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:


TypeError: Cannot read property 'contains' of null
    at /Applications/poi.app/Contents/Resources/app.asar/node_modules/dom-helpers/query/contains.js:17:17
    at Dropdown.componentWillUpdate (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-bootstrap/lib/Dropdown.js:170:53)
    at Og (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:171:33)
    at Tg (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:180:30)
    at bi (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:232:22)
    at ci (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:233:284)
    at Di (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:249:348)
    at Yh (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:248:144)
    at Ii (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:251:256)
    at Cd (/Applications/poi.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:85:207)

    in Dropdown
    in Uncontrolled(Dropdown)
    in ShipDropdown
    in div
    in div
    in div
    in div
    in SecretaryArea
    in ConnectFunction
    in div
    in Blueprint3.Card
    in div
    in StyledComponent
    in tab-area__PluginAppTabpane
    in PluginWrap
    in withI18nextTranslation(PluginWrap)
    in div
    in StyledComponent
    in tab-contents-union__PoiTabChildPositioner
    in div
    in StyledComponent
    in tab-contents-union__PoiTabContents
    in TabContentsUnion
    in ConnectFunction
    in Connect(TabContentsUnion)
    in div
    in StyledComponent
    in tab-area__PoiTabContainer
    in div
    in t
    in div
    in StyledComponent
    in tab-area__PoiTabsContainer
    in ControlledTabArea
    in ConnectFunction
    in withI18nextTranslation(Connect(ControlledTabArea))
    in poi-nav-tabs
    in poi-nav
    in div
    in StyledComponent
    in poi-app__PoiAppContainer
    in div
    in StyledComponent
    in poi-app__PoiAppE
    in PoiApp
    in ConnectFunction
    in poi-main
    in Blueprint3.ResizeSensor
    in ThemeProvider
    in Poi
    in ConnectFunction
    in Provider
    in I18nextProvider

**Comment by KagamiChan** [comment]
報告いただきありがとうございます
この不具合は確認済みですが選択操作は有効です

**Comment by KagamiChan** [comment]
v3.0.1 が出ました
