### ISSUE TITLE
poi无法联网

### ISSUE THREAD

**Issue by qqwaaszzx** [poooi/poi#2236]
无法载入游戏，甚至无法上网。使用chrome可以通过岛风go正常载入游戏

**poi 版本 / poi version:**
10.4.0
**操作系统 / OS:**
Window 10家庭中文版
版本1903（OS内部版本18362.476）

可以的话请提供开发者工具 Console 选项卡的截图，
开发者工具的打开方式是按 ctrl + shift + i (macOS 上为 ⌥ + ⌘ + i），或游戏区域下方信息栏的最左边齿轮按钮。
D:\poi\resources\app.asar\node_modules\@babel\core\node_modules\@babel\generator\lib\index.js:65 [BABEL] Note: The code generator has deoptimised the styling of D:\poi\resources\app.asar\node_modules\lodash\lodash.js as it exceeds the max of 500KB.
normalizeOptions @ D:\poi\resources\app.asar\node_modules\@babel\core\node_modules\@babel\generator\lib\index.js:65
D:\poi\resources\app.asar\views\redux\info\quests.js:717 Scheduling daily refresh at 331200000 (now 1575678416301)
D:\poi\resources\app.asar\views\components\settings\about\update\fcd.js:101 No newer version of map: current 2019/11/30/01, remote 2019/11/30/01, mode default
D:\poi\resources\app.asar\views\components\settings\about\update\fcd.js:101 No newer version of shipavatar: current 2018/09/08/02, remote 2018/09/08/02, mode default
D:\poi\resources\app.asar\views\components\settings\about\update\fcd.js:101 No newer version of shiptag: current 2019/11/30/01, remote 2019/11/30/01, mode default
D:\poi\resources\app.asar\views\components\settings\about\update\fcd.js:110 Update fcd from https://poi.moe/fcd/ successfully in mode default.
D:\poi\resources\app.asar\views\services\update.js:81 Remote version: v10.4.0. Current version: 10.4.0
D:\poi\resources\app.asar\views\env-parts\devtool-message.js:13 This is poi@10.4.0 on win32 x64 with Electron@6.1.5,        PLUGINS: poi-plugin-prophet@8.2.0, poi-plugin-akashic-records@7.3.0, poi-plugin-ship-info@7.1.10, poi-plugin-item-info@4.1.4,        FCD: map@2019/11/30/01, shipavatar@2018/09/08/02, shiptag@2019/11/30/01
D:\poi\resources\electron.asar\renderer\ipc-renderer-internal-utils.js:22 Uncaught (in promise) Error: ERR_INVALID_URL (-300) loading ''
    at rejectAndCleanup (D:\poi\resources\electron.asar\browser\navigation-controller.js:67:29)
    at WebContents.failListener (D:\poi\resources\electron.asar\browser\navigation-controller.js:77:21)
    at WebContents.emit (events.js:205:15)
    at WebContents.NavigationController.reload (D:\poi\resources\electron.asar\browser\navigation-controller.js:141:33)
    at D:\poi\resources\electron.asar\browser\rpc-server.js:370:67
    at EventEmitter.<anonymous> (D:\poi\resources\electron.asar\browser\rpc-server.js:249:27)
    at EventEmitter.emit (events.js:200:13)
    at WebContents.<anonymous> (D:\poi\resources\electron.asar\browser\api\web-contents.js:341:29)
    at WebContents.emit (events.js:200:13)

D:\poi\resources\app.asar\views\env-parts\devtool-message.js:13 This is poi@10.4.0 on win32 x64 with Electron@6.1.5,        PLUGINS: poi-plugin-prophet@8.2.0, poi-plugin-akashic-records@7.3.0, poi-plugin-ship-info@7.1.10, poi-plugin-item-info@4.1.4,        FCD: map@2019/11/30/01, shipavatar@2018/09/08/02, shiptag@2019/11/30/01
registry.npm.taobao.org/whocallsthefleet-database/latest:1 Failed to load resource: net::ERR_EMPTY_RESPONSE
D:\poi\resources\app.asar\views\components\settings\about\update\wctf-db.js:120 Can't find update info for wctf-db
WctfDB.updateDB @ D:\poi\resources\app.asar\views\components\settings\about\update\wctf-db.js:120
D:\poi\resources\app.asar\views\components\settings\about\update\wctf-db.js:132 TypeError: Cannot read property 'version' of undefined
    at WctfDB.updateDB (D:\poi\resources\app.asar\views\components\settings\about\update\wctf-db.js:127:63)

WctfDB.updateDB @ D:\poi\resources\app.asar\views\components\settings\about\update\wctf-db.js:132

**Comment by qqwaaszzx** [comment]
以下的是4个bug的位置

D:\poi\resources\app.asar\node_modules\@babel\core\node_modules\@babel\generator\lib\index.js:65 [BABEL] Note: The code generator has deoptimised the styling of D:\poi\resources\app.asar\node_modules\lodash\lodash.js as it exceeds the max of 500KB.


Uncaught (in promise) Error: ERR_INVALID_URL (-300) loading ''
    at rejectAndCleanup (D:\poi\resources\electron.asar\browser\navigation-controller.js:67:29)
    at WebContents.failListener (D:\poi\resources\electron.asar\browser\navigation-controller.js:77:21)
    at WebContents.emit (events.js:205:15)
    at WebContents.NavigationController.reload (D:\poi\resources\electron.asar\browser\navigation-controller.js:141:33)
    at D:\poi\resources\electron.asar\browser\rpc-server.js:370:67
    at EventEmitter.<anonymous> (D:\poi\resources\electron.asar\browser\rpc-server.js:249:27)
    at EventEmitter.emit (events.js:200:13)
    at WebContents.<anonymous> (D:\poi\resources\electron.asar\browser\api\web-contents.js:341:29)
    at WebContents.emit (events.js:200:13)



Failed to load resource: net::ERR_EMPTY_RESPONSE



TypeError: Cannot read property 'version' of undefined
    at WctfDB.updateDB (D:\poi\resources\app.asar\views\components\settings\about\update\wctf-db.js:127:63)

**Comment by qqwaaszzx** [comment]
代理可能误点了

**Comment by qqwaaszzx** [comment]
代理可能误点了
