### ISSUE TITLE
OSX 10.15.4无法启动新10.6.0 beta版poi

### ISSUE THREAD

**Issue by ForeverNoah** [poooi/poi#2292]
**poi 版本 / poi version: v10.6.0-beta.0
**操作系统 / OS: Mac OS X 10.15.4

**你遇到了什么样的问题 / The problem you've met:

更新新版poi之后点开程序图标无法正常启动浏览器
<img width="390" alt="截屏2020-05-05 16 07 55" src="https://user-images.githubusercontent.com/26175756/81046319-b5b12b80-8eea-11ea-91b6-5f29be0f33f0.png">

**Comment by KochiyaOcean** [comment]
菜单里面 view - developer tools 有什么报错信息么

**Comment by ForeverNoah** [comment]
> 错

<img width="459" alt="截屏2020-05-05 21 28 17" src="https://user-images.githubusercontent.com/26175756/81071471-5b7a8f80-8f17-11ea-8b19-8244bbf29a23.png">

我尝试reload和force reload都没有用

**Comment by Shell32-Natsu** [comment]
10.15.3. 同样的问题，似乎是touchbar相关
```
> /Applications/poi.app/Contents/MacOS/poi
(electron) 'systemPreferences.isDarkMode()' is deprecated and will be removed. Please use 'nativeTheme.shouldUseDarkColors' instead.
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[ERROR] Error: Cannot add a single instance of TouchBarItem multiple times in a TouchBar
    at electron/js2c/browser_init.js:2956:15
    at Array.forEach (<anonymous>:null:null)
    at new TouchBar (electron/js2c/browser_init.js:2948:11)
    at Object.<anonymous> (/Applications/poi.app/Contents/Resources/app.asar/lib/touchbar.es:149:22)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Module._compile (/Applications/poi.app/Contents/Resources/app.asar/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Object.newLoader [as .es] (/Applications/poi.app/Contents/Resources/app.asar/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at App.<anonymous> (/Applications/poi.app/Contents/Resources/app.asar/app.js:204:36)
    at App.emit (events.js:215:7)
    at App.EventEmitter.emit (domain.js:476:20)
    at App.emitter.emit (/Applications/poi.app/Contents/Resources/app.asar/node_modules/@sentry/electron/dist/main/integrations/electron.js:55:20)
    at App.topLevelDomainCallback (domain.js:131:23)
```

**Comment by KochiyaOcean** [comment]
3b4a38ea9582f164ce8a73e585584439e3d229a3 试着修复了，如果有自己 build 的话可以试试看

**Comment by KochiyaOcean** [comment]
已确认修复
