### ISSUE TITLE
poi在装有electron9.2.1的系统上刷新、调整大小等功能不正常

### ISSUE THREAD

**Issue by TachibanaOchiba** [poooi/poi#2332]
**poi 版本 / poi version:**
poi@10.6.0
**操作系统 / OS:**
Arch Linux amd64

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**
点击刷新、截图等功能都没有反应 游戏界面上方有白边
使用electron 8.3.4启动恢复正常
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Console:**
```
/usr/share/poi/views/redux/info/quests.es:732 Scheduling daily refresh at 331200000 (now 1599941105081)
/usr/share/poi/node_modules/@babel/register/lib/cache.js:69 Babel could not write cache to file: /usr/share/poi/node_modules/.cache/@babel/register/.babel.7.9.6.production.json 
due to a permission issue. Cache is disabled.
save @ /usr/share/poi/node_modules/@babel/register/lib/cache.js:69
electron/js2c/renderer_init.js:82 Electron Deprecation Warning The 'remote' module is deprecated and will be disabled by default in a future version of Electron. To ensure a smooth upgrade and silence this warning, specify {enableRemoteModule: true} in the WebPreferences for this window.
(anonymous) @ electron/js2c/renderer_init.js:82
electron/js2c/renderer_init.js:154 Uncaught Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at HTMLElement.e.getWebContentsId (electron/js2c/renderer_init.js:154:3685)
    at HTMLElement.<anonymous> (electron/js2c/renderer_init.js:154:4630)
    at ElectronWebView.forceSyncZoom (/usr/share/poi/views/components/etc/webview.es:27:72)
    at ResizeObserver.ElectronWebView.handleResize (/usr/share/poi/views/components/etc/webview.es:39:12)
    at invokeFunc (/usr/share/poi/node_modules/lodash/lodash.js:10333:23)
    at trailingEdge (/usr/share/poi/node_modules/lodash/lodash.js:10382:18)
    at timerExpired (/usr/share/poi/node_modules/lodash/lodash.js:10370:18)

/usr/share/poi/views/kan-game-wrapper.es:230 Uncaught TypeError: this.webview.current.view.getWebContents is not a function
    at Object.KanGameWrapper.handleWebviewMount [as onDidAttach] (/usr/share/poi/views/kan-game-wrapper.es:230:33)
    at HTMLElement.<anonymous> (/usr/share/poi/views/components/etc/webview.es:70:46)
    at WebViewImpl.dispatchEvent (electron/js2c/renderer_init.js:154:2207)
    at dispatchEvent (electron/js2c/renderer_init.js:142:1849)
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:142:2944)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:114:818)

/usr/share/poi/views/components/settings/about/update/fcd.es:101 No newer version of map: current 2020/07/22/01, remote 2020/07/22/01, mode default
/usr/share/poi/views/components/settings/about/update/fcd.es:101 No newer version of shipavatar: current 2018/09/08/02, remote 2018/09/08/02, mode default
/usr/share/poi/views/components/settings/about/update/fcd.es:101 No newer version of shiptag: current 2020/07/18/01, remote 2020/07/18/01, mode default
/usr/share/poi/views/components/settings/about/update/fcd.es:110 Update fcd from https://poi.moe/fcd/ successfully in mode default.
/usr/share/poi/views/services/plugin-manager/utils.es:170 poi-plugin-kcwiki-report: No translate file found.
updateI18n @ /usr/share/poi/views/services/plugin-manager/utils.es:170
/usr/share/poi/views/services/update.es:73 Check update error. FetchError: invalid json response body at https://api.poi.moe/update/latest.json reason: Unexpected token < in JSON at position 0
    at /usr/share/poi/node_modules/node-fetch/lib/index.js:272:32
    at checkUpdate (/usr/share/poi/views/services/update.es:72:23)

(anonymous) @ /usr/share/poi/views/services/update.es:73
electron/js2c/renderer_init.js:134 Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure
  protocols. This exposes users of this app to unnecessary security risks.
  Consider loading the following resources over HTTPS or FTPS. 
- http://203.104.209.23/kcs2/resources/ship/remodel/0200_6868.png?version=17
- http://203.104.209.23/kcs2/resources/ship/remodel/0610_3683.png?version=51
- http://203.104.209.23/kcs2/resources/ship/remodel/0545_9823.png?version=51
- http://203.104.209.23/kcs2/resources/ship/remodel/0390_8735.png?version=19
- http://203.104.209.23/kcs2/resources/ship/remodel/0368_1699.png?version=13
- http://203.104.209.23/kcs2/resources/ship/remodel/0232_1569.png?version=43
- http://203.104.209.23/kcs2/resources/ship/remodel/0314_6346.png?version=13
- http://203.104.209.23/kcs2/resources/ship/remodel/0228_1428.png?version=20
- http://203.104.209.23/kcs2/resources/ship/remodel/0497_7228.png?version=45
- http://203.104.209.23/kcs2/resources/ship/remodel/0326_1612.png?version=15
- http://203.104.209.23/kcs2/resources/ship/remodel/0107_9043.png?version=30
- http://203.104.209.23/kcs2/resources/ship/remodel/0106_3161.png?version=30
- http://203.104.209.23/kcs2/resources/ship/remodel/0623_4645.png?version=54
- http://203.104.209.23/kcs2/resources/ship/remodel/0627_4219.png?version=52
- http://203.104.209.23/kcs2/resources/ship/remodel/0568_2670.png?version=51
- http://203.104.209.23/kcs2/resources/ship/remodel/0394_4389.png
- http://203.104.209.23/kcs2/resources/ship/remodel/0556_5573.png?version=56
- http://203.104.209.23/kcs2/resources/ship/remodel/0678_1293.png?version=51
- http://203.104.209.23/kcs2/resources/ship/remodel/0536_2380.png?version=51
- http://203.104.209.23/kcs2/resources/ship/remodel/0487_5184.png?version=3
- http://203.104.209.23/kcs2/resources/ship/remodel/0569_2422.png?version=53
- http://203.104.209.23/kcs2/resources/ship/remodel/0563_8809.png?version=58
- http://203.104.209.23/kcs2/resources/ship/remodel/0693_8885.png?version=51
- http://203.104.209.23/kcs2/resources/ship/remodel/0319_5232.png?version=16
- http://203.104.209.23/kcs2/resources/ship/remodel_dmg/0328_2256.png?version=31
- http://203.104.209.23/kcs2/img/common/ship_bg/card/r2.png
- http://203.104.209.23/kcs2/resources/ship/remodel_dmg/0237_2690.png?version=14
- http://203.104.209.23/kcs2/img/common/ship_bg/card/r1.png
- http://203.104.209.23/kcs2/resources/ship/remodel_dmg/0240_8777.png?version=11
- http://203.104.209.23/kcs2/resources/ship/remodel/0016_1503.png?version=56
- http://203.104.209.23/kcs2/img/common/ship_bg/card/c1.png
- http://203.104.209.23/kcs2/resources/ship/remodel/0022_6557.png?version=12
- http://203.104.209.23/kcs2/img/common/ship_bg/card/c2.png
- http://203.104.209.23/kcs2/resources/ship/remodel/0012_7373.png?version=14
- http://203.104.209.23/kcs2/resources/ship/remodel/0101_1441.png?version=12
  

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
(anonymous) @ electron/js2c/renderer_init.js:134
electron/js2c/renderer_init.js:14 (electron) Security Warning: webFrame.executeJavaScript was called without worldSafeExecuteJavaScript enabled. This is considered unsafe. worldSafeExecuteJavaScript will be enabled by default in Electron 12.
log @ electron/js2c/renderer_init.js:14
electron/js2c/renderer_init.js:134 Electron Security Warning (allowpopups) A <webview> has "allowpopups" set to true. This exposes
    users of this app to some security risk, since popups are just
    BrowserWindows. If you do not need this feature, you should disable it.

    
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
(anonymous) @ electron/js2c/renderer_init.js:134
electron/js2c/renderer_init.js:134 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
(anonymous) @ electron/js2c/renderer_init.js:134
/usr/share/poi/views/components/settings/about/update/wctf-db.es:140 No update for wctf-db, current: 20200908.0.0, remote: 20200908.0.0
/usr/share/poi/views/services/plugin-manager/utils.es:170 poi-plugin-kcwiki-report: No translate file found.
updateI18n @ /usr/share/poi/views/services/plugin-manager/utils.es:170
/home/ochiba/.config/poi/plugins/node_modules/poi-plugin-wheres-my-fuel-gone/views/redux/readDataFiles.js:91 Unable to read /home/ochiba/.config/poi/wheres-my-fuel-gone/17107104/filters.json:  Error: ENOENT: no such file or directory, open '/home/ochiba/.config/poi/wheres-my-fuel-gone/17107104/filters.json'


_ref4 @ /home/ochiba/.config/poi/plugins/node_modules/poi-plugin-wheres-my-fuel-gone/views/redux/readDataFiles.js:91
/home/ochiba/.config/poi/plugins/node_modules/poi-plugin-subtitle/lib/loader.es:144 write EPROTO 24315865724232:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

Loader._fetchSubtitleUpdates @ /home/ochiba/.config/poi/plugins/node_modules/poi-plugin-subtitle/lib/loader.es:144
/home/ochiba/.config/poi/plugins/node_modules/poi-plugin-subtitle/lib/loader.es:145 Error: write EPROTO 24315865724232:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)

Loader._fetchSubtitleUpdates @ /home/ochiba/.config/poi/plugins/node_modules/poi-plugin-subtitle/lib/loader.es:145
/home/ochiba/.config/poi/plugins/node_modules/poi-plugin-subtitle/lib/loader.es:144 [poi-plugin-subtitle]: Invalid subtitle updates: undefined
Loader._fetchSubtitleUpdates @ /home/ochiba/.config/poi/plugins/node_modules/poi-plugin-subtitle/lib/loader.es:144
/home/ochiba/.config/poi/plugins/node_modules/poi-plugin-subtitle/lib/loader.es:145 Error: [poi-plugin-subtitle]: Invalid subtitle updates: undefined
    at throwPluginError (/home/ochiba/.config/poi/plugins/node_modules/poi-plugin-subtitle/lib/util.es:13:9)
    at Loader._fetchSubtitleUpdates (/home/ochiba/.config/poi/plugins/node_modules/poi-plugin-subtitle/lib/loader.es:141:38)
    at Loader.getSubtitles (/home/ochiba/.config/poi/plugins/node_modules/poi-plugin-subtitle/lib/loader.es:48:14)

Loader._fetchSubtitleUpdates @ /home/ochiba/.config/poi/plugins/node_modules/poi-plugin-subtitle/lib/loader.es:145
/usr/share/poi/views/env-parts/devtool-message.es:13 This is poi@10.6.0 on linux x64 with Electron@9.2.1,        PLUGINS: poi-plugin-prophet@8.4.1, poi-plugin-exp-calc@5.0.1, poi-plugin-quest-info@6.0.2, poi-plugin-ezexped@1.7.2, poi-plugin-hensei-nikki@5.0.4, poi-plugin-senka-calc@4.4.2, poi-plugin-map-hp@6.2.0, poi-plugin-secretary@3.0.2, poi-plugin-anchorage-repair@0.6.1, poi-plugin-akashic-records@7.3.2, poi-plugin-leveling@2.0.1, poi-plugin-battle-detail@5.8.1, poi-plugin-mo2@0.7.1, poi-plugin-wheres-my-fuel-gone@0.7.4, poi-plugin-item-improvement@7.1.3, poi-plugin-ship-info@7.2.0, poi-plugin-item-info@4.1.4, poi-plugin-navy-album@1.3.3, poi-plugin-k2badge@0.3.2, poi-plugin-lock-reminder@1.0.5, poi-plugin-kcwiki-report@3.1.27, poi-plugin-report@4.5.0, poi-plugin-subtitle@1.2.26, resources@2.3.27,        FCD: map@2020/07/22/01, shipavatar@2018/09/08/02, shiptag@2020/07/18/01
DevTools failed to load SourceMap: Could not load content for file:///home/ochiba/.config/poi/plugins/node_modules/poi-plugin-ship-info/lib/html2canvas.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///usr/share/poi/node_modules/poi-asset-themes/dist/blueprint/blueprint.css.map: 
DevTools failed to load SourceMap: Could not load content for file:///home/ochiba/.config/poi/plugins/node_modules/poi-plugin-hensei-nikki/assets/hensei-nikki.css.map: 
DevTools failed to load SourceMap: Could not load content for file:///home/ochiba/.config/poi/plugins/node_modules/poi-plugin-senka-calc/assets/senka-calc.css.map: 
index.es? [sm]:24 TypeError: this.view[method] is not a function
    at ElectronWebView.<computed> [as getWebContents] (/usr/share/poi/views/components/etc/webview.es:79:33)
    at Notifier.handleResponseDetails (/home/ochiba/.config/poi/plugins/node_modules/poi-plugin-subtitle/lib/notifier.es:63:145)
    at /home/ochiba/.config/poi/plugins/node_modules/poi-plugin-subtitle/index.es:31:18
    at CallbacksRegistry.apply (electron/js2c/renderer_init.js:130:792)
    at electron/js2c/renderer_init.js:82:5068
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:82:4308)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:114:818)

(anonymous) @ index.es? [sm]:24
apply @ electron/js2c/renderer_init.js:130
(anonymous) @ electron/js2c/renderer_init.js:82
(anonymous) @ electron/js2c/renderer_init.js:82
emit @ events.js:223
onMessage @ electron/js2c/renderer_init.js:114
/usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:52 Uncaught TypeError: this.view[method] is not a function
    at ElectronWebView.<computed> [as getWebContents] (/usr/share/poi/views/components/etc/webview.es:79:33)
    at Object.gameRefreshPage [as func] (/usr/share/poi/views/services/utils.es:62:41)
    at onClick (/usr/share/poi/views/components/etc/modal.es:72:20)
    at Object.ba (/usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:14:84)
    at ja (/usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:14:238)
    at ka (/usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:14:292)
    at oa (/usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:15:72)
    at lc (/usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:52:170)
    at jc (/usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:51:255)
    at mc (/usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:52:334)
    at sc (/usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:56:10)
    at Ia (/usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:287:189)
    at Ma (/usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:19:57)
    at Rc (/usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:70:279)
    at id (/usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:69:102)
    at exports.unstable_runWithPriority (/usr/share/poi/node_modules/scheduler/cjs/scheduler.production.min.js:19:467)
    at cg (/usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:122:325)
    at Ga (/usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:287:48)
    at gd (/usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:68:371)

<computed> @ webview.es? [sm]:53
gameRefreshPage @ utils.es? [sm]:55
onClick @ modal.es? [sm]:53
ba @ /usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:14
ja @ /usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:14
ka @ /usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:14
oa @ /usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:15
lc @ /usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:52
jc @ /usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:51
mc @ /usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:52
sc @ /usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:56
Ia @ /usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:287
Ma @ /usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:19
Rc @ /usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:70
id @ /usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:69
exports.unstable_runWithPriority @ /usr/share/poi/node_modules/scheduler/cjs/scheduler.production.min.js:19
cg @ /usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:122
Ga @ /usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:287
gd @ /usr/share/poi/node_modules/react-dom/cjs/react-dom.production.min.js:68
```

**Comment by KochiyaOcean** [comment]
Update your local repo
