### ISSUE TITLE
Cannot open Developer Tools from menu button

### ISSUE THREAD

**Issue by KanaHayama** [poooi/poi#2402]
**poi 版本 / poi version:**

10.7.0

**操作系统 / OS:**

Windows 10

**插件名和版本 / Plugin name & version:**

None

**你遇到了什么样的问题 / The problem you've met:**

Cannot open `Developer Tools` by pressing debug menu button. While using shortcut key `Ctrl+Shift+I` can open it. Not the one for WebView.

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

Click the button.

**Comment by KochiyaOcean** [comment]
@KanaHayama Cannot reproduce. Are there any error messages?

**Comment by KanaHayama** [comment]
No error message, the window just does not show. The WebView Developer Tools button works as expected. Windows 10 21H1 (19043.1348).

**Comment by KanaHayama** [comment]
Ok I got these by first opening the tool (by shortcut) then click the button
`
Uncaught TypeError: focusedWindow.openDevTools is not a function
    at Object.click (C:\Program Files\poi\resources\app.asar\views\components\etc\menu.js:141:23)
    at C:\Program Files\poi\resources\app.asar\node_modules\electron-react-titlebar\dist\renderer.js:1:4769
    at Object.Rb (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:52:317)
    at Xb (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:52:471)
    at Yb (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:53:35)
    at Ze (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:100:68)
    at se (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:101:380)
    at C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:113:65
    at Jb (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:292:189)
    at Nb (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:50:57)
    at jd (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:105:469)
    at yc (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:75:265)
    at hd (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:74:124)
    at exports.unstable_runWithPriority (C:\Program Files\poi\resources\app.asar\node_modules\scheduler\cjs\scheduler.production.min.js:18:343)
    at gg (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:325)
    at Hb (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:292:48)
    at gd (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:73:352)
    at HTMLDivElement.sentryWrapped (C:\Program Files\poi\resources\app.asar\node_modules\@sentry\browser\dist\helpers.js:75:23)
`
