### ISSUE TITLE
战斗记录插件发生错误

### ISSUE THREAD

**Issue by lavender94** [poooi/poi#2408]
**poi 版本 / poi version:10.6.0**

**操作系统 / OS:Window 10 版本 1909 (18363.1977)**

**插件名和版本 / Plugin name & version:战斗记录 5.11.0**

**你遇到了什么样的问题 / The problem you've met:打完6-2boss点之后战斗记录插件报错 前两个点打完插件正常 前一个点打完没有观测 推测与boss点或前一个点的战斗记录内容有关 以下是错误信息**
TypeError: Cannot read property '3' of undefined
    at ItemView.render (C:\Users\Lavender\AppData\Roaming\poi\plugins\node_modules\poi-plugin-battle-detail\views\overview-area.js:261:32)
    at gi (C:\Users\Lavender\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:182:192)
    at fi (C:\Users\Lavender\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:181:224)
    at Rj (C:\Users\Lavender\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:263:490)
    at Qj (C:\Users\Lavender\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:246:265)
    at Kj (C:\Users\Lavender\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:246:194)
    at yj (C:\Users\Lavender\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:239:172)
    at C:\Users\Lavender\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:123:115
    at exports.unstable_runWithPriority (C:\Users\Lavender\AppData\Local\Programs\poi\resources\app.asar\node_modules\scheduler\cjs\scheduler.production.min.js:19:467)
    at cg (C:\Users\Lavender\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:325)
    at fg (C:\Users\Lavender\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:123:61)
    at gg (C:\Users\Lavender\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:496)
    at Ig (C:\Users\Lavender\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:230:156)
    at Object.enqueueSetState (C:\Users\Lavender\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:132:237)
    at PluginWindowWrap.F.setState (C:\Users\Lavender\AppData\Local\Programs\poi\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:369)
    at C:\Users\Lavender\AppData\Local\Programs\poi\resources\app.asar\views\components\tab-area\plugin-window-wrapper.es:184:14

    in ItemView
    in div
    in Col
    in div
    in Grid
    in ShipView
    in div
    in Col
    in div
    in Row
    in div
    in Grid
    in div
    in FleetView
    in div
    in div
    in PanelBody
    in div
    in Transition
    in Collapse
    in PanelCollapse
    in div
    in Panel
    in Uncontrolled(Panel)
    in ForwardRef
    in div
    in OverviewArea
    in div
    in div
    in Transition
    in Fade
    in TabPane
    in Tab
    in div
    in TabContent
    in div
    in TabContainer
    in Tabs
    in Uncontrolled(Tabs)
    in ForwardRef
    in div
    in MainAreaImpl
    in ConnectFunction
    in PluginWrap
    in withI18nextTranslation(PluginWrap)
    in div
    in StyledComponent
    in plugin-window-wrapper__PoiAppTabpane
    in StyleSheetManager
    in PluginWindowWrap
    in div
    in StyledComponent
    in tab-area__PoiTabContainer
    in div
    in t
    in div
    in StyledComponent
    in tab-area__PoiTabsContainer
    in ControlledTabArea
    in ConnectFunction
    in withI18nextTranslation(Connect(ControlledTabArea))
    in poi-nav-tabs
    in poi-nav
    in div
    in StyledComponent
    in poi-app__PoiAppContainer
    in div
    in StyledComponent
    in poi-app__PoiAppE
    in PoiApp
    in ConnectFunction
    in poi-main
    in Blueprint3.ResizeSensor
    in ThemeProvider
    in Poi
    in ConnectFunction
    in Provider
    in I18nextProvider
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**
配置和战斗记录（boss点）（来源：航海日志）
![战斗记录插件错误_战斗记录](https://user-images.githubusercontent.com/10097980/147379029-9cc9f061-b8d1-4569-863e-3955d024e188.png)

开发者工具Console截图：
![战斗记录插件错误](https://user-images.githubusercontent.com/10097980/147378879-5ac23b0d-83cd-4d4c-afee-08e5d4b6e6b6.png)

**Comment by lavender94** [comment]
补充：重启poi后可以读取其它战斗记录 但是点击6-2那一趟出击的所有点的战斗记录都会报同样的错
