### ISSUE TITLE
任务信息2报错

### ISSUE THREAD

**Issue by nana996pa** [poooi/poi#2409]
**poi 版本 / poi version:**
10.7
**操作系统 / OS:**
PC  19043.1415

**插件名和版本 / Plugin name & version:**
任务信息2 0.5.8

**你遇到了什么样的问题 / The problem you've met:**
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Jg (E:\computer\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:237:48)
    at Object.enqueueSetState (E:\computer\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:133:211)
    at Text.C.setState (E:\computer\poi\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:369)
    at Text.update (E:\computer\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\text\text.js:60:14)
    at Text.componentDidUpdate (E:\computer\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\text\text.js:40:14)
    at Yi (E:\computer\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:219:502)
    at dk (E:\computer\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:259:160)
    at exports.unstable_runWithPriority (E:\computer\poi\resources\app.asar\node_modules\scheduler\cjs\scheduler.production.min.js:18:343)
    at gg (E:\computer\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:325)
    at Uj (E:\computer\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:252:279)
    at Lj (E:\computer\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:243:371)
    at E:\computer\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:123:115
    at exports.unstable_runWithPriority (E:\computer\poi\resources\app.asar\node_modules\scheduler\cjs\scheduler.production.min.js:18:343)
    at gg (E:\computer\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:325)
    at jg (E:\computer\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:123:61)
    at ig (E:\computer\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:428)
    at Jg (E:\computer\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:237:203)
    at Oh (E:\computer\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:170:408)
    at listener (C:\Users\HASEE\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\poi\hooks.ts:43:32)
    at handleChange (C:\Users\HASEE\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\poi\store.ts:26:7)
    at dispatch (E:\computer\poi\resources\app.asar\node_modules\redux\lib\redux.js:305:7)
    at E:\computer\poi\resources\app.asar\node_modules\redux-thunk\lib\index.js:27:16
    at E:\computer\poi\resources\app.asar\views\middlewares\promise-action.js:55:12
    at parseResponses (E:\computer\poi\resources\app.asar\views\env-parts\data-resolver.js:101:5)
    at resolveResponses (E:\computer\poi\resources\app.asar\views\env-parts\data-resolver.js:126:7)
    at handleProxyGameOnResponse (E:\computer\poi\resources\app.asar\views\env-parts\data-resolver.js:141:7)
    at CallbacksRegistry.apply (E:\computer\poi\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\callbacks-registry.js:54:29)
    at E:\computer\poi\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:345:23
    at EventEmitter.<anonymous> (E:\computer\poi\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:327:13)
    at EventEmitter.emit (node:events:394:28)
    at Object.onMessage (node:electron/js2c/renderer_init:81:1017)

    at Text (E:\computer\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\text\text.js:28:47)
    at div
    at I (E:\computer\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at Card (E:\computer\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\card\card.js:28:42)
    at I (E:\computer\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at ResizeSensor (E:\computer\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\resize-sensor\resizeSensor.js:30:47)
    at InnerReference (E:\computer\poi\resources\app.asar\node_modules\react-popper\lib\cjs\Reference.js:40:35)
    at Reference
    at span
    at Manager (E:\computer\poi\resources\app.asar\node_modules\react-popper\lib\cjs\Manager.js:39:35)
    at Popover (E:\computer\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\popover\popover.js:45:47)
    at Tooltip (E:\computer\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\tooltip\tooltip.js:31:47)
    at MinimalQuestCard (C:\Users\HASEE\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\components\QuestCard.tsx:142:3)
    at QuestCard (C:\Users\HASEE\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\components\QuestCard.tsx:168:3)
    at div
    at CellMeasurer (E:\computer\poi\resources\app.asar\node_modules\react-virtualized\dist\commonjs\CellMeasurer\CellMeasurer.js:51:37)
    at div
    at div
    at Grid (E:\computer\poi\resources\app.asar\node_modules\react-virtualized\dist\commonjs\Grid\Grid.js:93:37)
    at List (E:\computer\poi\resources\app.asar\node_modules\react-virtualized\dist\commonjs\List\List.js:50:37)
    at div
    at AutoSizer (E:\computer\poi\resources\app.asar\node_modules\react-virtualized\dist\commonjs\AutoSizer\AutoSizer.js:48:37)
    at div
    at I (E:\computer\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at QuestList (C:\Users\HASEE\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\components\QuestList.tsx:101:3)
    at Main (C:\Users\HASEE\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\App.tsx:39:39)
    at div
    at I (E:\computer\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at StoreProvider (C:\Users\HASEE\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\store\store.tsx:73:3)
    at App
    at div
    at Card (E:\computer\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\card\card.js:28:42)
    at div
    at I (E:\computer\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at PluginWrap (E:\computer\poi\resources\app.asar\views\components\tab-area\plugin-wrapper.js:24:5)
    at I18nextWithTranslation (E:\computer\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\withTranslation.js:32:31)
    at div
    at I (E:\computer\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (E:\computer\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at TabContentsUnion (E:\computer\poi\resources\app.asar\views\components\tab-area\tab-contents-union.js:50:5)
    at ConnectFunction (E:\computer\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at forwardConnectRef
    at div
    at I (E:\computer\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at t (E:\computer\poi\resources\app.asar\node_modules\react-resizable-area\dist\index.js:1:5417)
    at div
    at I (E:\computer\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at ControlledTabArea (E:\computer\poi\resources\app.asar\views\components\tab-area\index.js:248:5)
    at ConnectFunction (E:\computer\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at I18nextWithTranslation (E:\computer\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\withTranslation.js:32:31)
    at poi-nav-tabs
    at poi-nav
    at div
    at I (E:\computer\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (E:\computer\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at PoiApp (E:\computer\poi\resources\app.asar\views\poi-app.js:89:5)
    at ConnectFunction (E:\computer\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at poi-main
    at ResizeSensor (E:\computer\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\resize-sensor\resizeSensor.js:30:47)
    at exports.ThemeProvider (E:\computer\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:25072)
    at Poi (E:\computer\poi\resources\app.asar\views\app.js:76:5)
    at ConnectFunction (E:\computer\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at Provider (E:\computer\poi\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:21:20)
    at I18nextProvider [[(E:\computer\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\I18nextProvider.js:13:19)
**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by lawvs** [comment]
是打开插件就会崩溃，还是存在触发崩溃的特定条件？

**Comment by nana996pa** [comment]
好像没什么条件有时候点过去就突然这样了,一开始打开是没问题的

**Comment by nana996pa** [comment]
> 是打开插件就会崩溃，还是存在触发崩溃的特定条件？

好像没什么条件有时候点过去就突然这样了,一开始打开是没问题的

**Comment by lawvs** [comment]
尝试修复并发布了 v0.6.5，可以观察一下是否还会崩溃
