### ISSUE TITLE
poi 擴展程式 close quick composition，異常？

### ISSUE THREAD

**Issue by JimmyKuo-24** [poooi/poi#2415]
win10 poi v10.8.0

TypeError: Cannot read properties of undefined (reading 'api_name')
    at C:\Users\user\AppData\Roaming\poi\plugins\node_modules\poi-plugin-cqc\selectors.es:56:18
    at memoized (D:\poi v10.8.0\resources\app.asar\node_modules\lodash\lodash.js:10620:27)
    at Array.map (<anonymous>:null:null)
    at C:\Users\user\AppData\Roaming\poi\plugins\node_modules\poi-plugin-cqc\selectors.es:131:21
    at memoized (D:\poi v10.8.0\resources\app.asar\node_modules\lodash\lodash.js:10620:27)
    at C:\Users\user\AppData\Roaming\poi\plugins\node_modules\poi-plugin-cqc\selectors.es:140:83
    at Array.map (<anonymous>:null:null)
    at C:\Users\user\AppData\Roaming\poi\plugins\node_modules\poi-plugin-cqc\selectors.es:140:46
    at D:\poi v10.8.0\resources\app.asar\node_modules\reselect\lib\index.js:87:25
    at memoized (D:\poi v10.8.0\resources\app.asar\node_modules\reselect\lib\defaultMemoize.js:135:20)
    at D:\poi v10.8.0\resources\app.asar\node_modules\reselect\lib\index.js:101:40
    at memoized (D:\poi v10.8.0\resources\app.asar\node_modules\reselect\lib\defaultMemoize.js:135:20)
    at D:\poi v10.8.0\resources\app.asar\node_modules\reselect\lib\index.js:97:37
    at Function.memoized [as mapToProps] (D:\poi v10.8.0\resources\app.asar\node_modules\reselect\lib\defaultMemoize.js:135:20)
    at mapToPropsProxy (D:\poi v10.8.0\resources\app.asar\node_modules\react-redux\lib\connect\wrapMapToProps.js:53:46)
    at Function.detectFactoryAndVerify (D:\poi v10.8.0\resources\app.asar\node_modules\react-redux\lib\connect\wrapMapToProps.js:62:19)
    at mapToPropsProxy (D:\poi v10.8.0\resources\app.asar\node_modules\react-redux\lib\connect\wrapMapToProps.js:53:46)
    at handleFirstCall (D:\poi v10.8.0\resources\app.asar\node_modules\react-redux\lib\connect\selectorFactory.js:36:18)
    at pureFinalPropsSelector (D:\poi v10.8.0\resources\app.asar\node_modules\react-redux\lib\connect\selectorFactory.js:77:81)
    at D:\poi v10.8.0\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:341:16
    at Object.useMemo (D:\poi v10.8.0\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:172:115)
    at exports.useMemo (D:\poi v10.8.0\resources\app.asar\node_modules\react\cjs\react.production.min.js:23:113)
    at ConnectFunction (D:\poi v10.8.0\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:326:30)
    at Ch (D:\poi v10.8.0\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:157:137)
    at li (D:\poi v10.8.0\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:180:154)
    at ki (D:\poi v10.8.0\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:178:169)
    at ii (D:\poi v10.8.0\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:177:178)
    at ck (D:\poi v10.8.0\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:274:126)
    at bk (D:\poi v10.8.0\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:250:347)
    at ak (D:\poi v10.8.0\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:250:278)
    at Tj (D:\poi v10.8.0\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:250:138)
    at Lj (D:\poi v10.8.0\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:243:163)
    at D:\poi v10.8.0\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:123:115
    at exports.unstable_runWithPriority (D:\poi v10.8.0\resources\app.asar\node_modules\scheduler\cjs\scheduler.production.min.js:18:343)
    at gg (D:\poi v10.8.0\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:325)
    at jg (D:\poi v10.8.0\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:123:61)
    at ig (D:\poi v10.8.0\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:428)
    at Wj (D:\poi v10.8.0\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:244:190)
    at Object.notify (D:\poi v10.8.0\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:21:7)
    at Object.notifyNestedSubs (D:\poi v10.8.0\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:92:15)
    at handleChangeWrapper (D:\poi v10.8.0\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:97:20)
    at dispatch (D:\poi v10.8.0\resources\app.asar\node_modules\redux\lib\redux.js:305:7)
    at D:\poi v10.8.0\resources\app.asar\node_modules\redux-thunk\lib\index.js:27:16
    at PluginManager.installPlugin (D:\poi v10.8.0\resources\app.asar\views\services\plugin-manager\index.js:381:7)
    at D:\poi v10.8.0\resources\app.asar\views\components\settings\plugin\index.js:145:9
    at Object.PluginConfig.handleInstallByName [as onInstall] (D:\poi v10.8.0\resources\app.asar\views\components\settings\plugin\index.js:292:9)

    at ConnectFunction (D:\poi v10.8.0\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at div
    at CqcMainImpl (C:\Users\user\AppData\Roaming\poi\plugins\node_modules\poi-plugin-cqc\ui\index.es:26:1)
    at ConnectFunction (D:\poi v10.8.0\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at div
    at Card (D:\poi v10.8.0\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\card\card.js:28:42)
    at div
    at I (D:\poi v10.8.0\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at PluginWrap (D:\poi v10.8.0\resources\app.asar\views\components\tab-area\plugin-wrapper.js:24:5)
    at I18nextWithTranslation (D:\poi v10.8.0\resources\app.asar\node_modules\react-i18next\dist\commonjs\withTranslation.js:32:31)
    at div
    at I (D:\poi v10.8.0\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (D:\poi v10.8.0\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at TabContentsUnion (D:\poi v10.8.0\resources\app.asar\views\components\tab-area\tab-contents-union.js:50:5)
    at ConnectFunction (D:\poi v10.8.0\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at forwardConnectRef
    at div
    at I (D:\poi v10.8.0\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (D:\poi v10.8.0\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at ControlledTabArea (D:\poi v10.8.0\resources\app.asar\views\components\tab-area\index.js:248:5)
    at ConnectFunction (D:\poi v10.8.0\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at I18nextWithTranslation (D:\poi v10.8.0\resources\app.asar\node_modules\react-i18next\dist\commonjs\withTranslation.js:32:31)
    at poi-nav-tabs
    at poi-nav
    at div
    at I (D:\poi v10.8.0\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (D:\poi v10.8.0\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at PoiApp (D:\poi v10.8.0\resources\app.asar\views\poi-app.js:89:5)
    at ConnectFunction (D:\poi v10.8.0\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at poi-main
    at ResizeSensor (D:\poi v10.8.0\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\resize-sensor\resizeSensor.js:30:47)
    at exports.ThemeProvider (D:\poi v10.8.0\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:25072)
    at Poi (D:\poi v10.8.0\resources\app.asar\views\app.js:76:5)
    at ConnectFunction (D:\poi v10.8.0\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at Provider (D:\poi v10.8.0\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:21:20)
    at I18nextProvider (D:\poi v10.8.0\resources\app.asar\node_modules\react-i18next\dist\commonjs\I18nextProvider.js:13:19)

**Comment by JimmyKuo-24** [comment]
雖然修復了，但是無法儲存圖片...，png/all file都不行？
