### ISSUE TITLE
战斗记录插件报错并无法再次使用

### ISSUE THREAD

**Issue by sslantis** [poooi/poi#2416]
**poi 版本 / poi version:**
10.8.0
**操作系统 / OS:**
Windows 10 版本 21H1 (19043.1466)

**插件名和版本 / Plugin name & version:**
战斗记录 8.0.5

**你遇到了什么样的问题 / The problem you've met:**
在攻略海域6-4的C点后试图使用插件“战斗记录”查看该点战斗过程，点击C点详情后提示插件发生异常。关闭窗口尝试重新打开插件依旧弹出报错页，禁用插件重新启用，删除插件重新安装，重启poi，重新安装poi，重启电脑均无法使插件恢复正常，点击该插件即提示“插件「战斗记录」变成了乌龟（图片）”
报错代码如下：
TypeError: Cannot read properties of undefined (reading '3')
    at ItemView.render (c:\users\Jzh\AppData\Roaming\poi\plugins\node_modules\poi-plugin-battle-detail\views\overview-area.js:261:32)
    at qi (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:187:188)
    at pi (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:186:173)
    at ck (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:269:427)
    at bk (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:250:347)
    at ak (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:250:278)
    at Tj (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:250:138)
    at Lj (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:243:163)
    at C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:123:115
    at exports.unstable_runWithPriority (C:\Program Files\poi\resources\app.asar\node_modules\scheduler\cjs\scheduler.production.min.js:18:343)
    at gg (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:325)
    at jg (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:123:61)
    at ig (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:428)
    at Jg (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:237:203)
    at Object.enqueueSetState (C:\Program Files\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:133:211)
    at PluginWindowWrap.C.setState (C:\Program Files\poi\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:369)
    at C:\Program Files\poi\resources\app.asar\views\components\tab-area\plugin-window-wrapper.js:184:14

    at ItemView (c:\users\Jzh\AppData\Roaming\poi\plugins\node_modules\poi-plugin-battle-detail\views\overview-area.js:238:1)
    at div
    at Col (C:\Program Files\poi\resources\app.asar\node_modules\react-bootstrap\lib\Col.js:219:29)
    at div
    at Grid (C:\Program Files\poi\resources\app.asar\node_modules\react-bootstrap\lib\Grid.js:48:29)
    at LBACView (c:\users\Jzh\AppData\Roaming\poi\plugins\node_modules\poi-plugin-battle-detail\views\overview-area.js:207:1)
    at div
    at Col (C:\Program Files\poi\resources\app.asar\node_modules\react-bootstrap\lib\Col.js:219:29)
    at div
    at Row (C:\Program Files\poi\resources\app.asar\node_modules\react-bootstrap\lib\Row.js:35:29)
    at div
    at Grid (C:\Program Files\poi\resources\app.asar\node_modules\react-bootstrap\lib\Grid.js:48:29)
    at div
    at FleetView (c:\users\Jzh\AppData\Roaming\poi\plugins\node_modules\poi-plugin-battle-detail\views\overview-area.js:74:1)
    at div
    at div
    at PanelBody (C:\Program Files\poi\resources\app.asar\node_modules\react-bootstrap\lib\PanelBody.js:51:29)
    at div
    at Transition (C:\Program Files\poi\resources\app.asar\node_modules\react-transition-group\Transition.js:133:30)
    at Collapse (C:\Program Files\poi\resources\app.asar\node_modules\react-bootstrap\lib\Collapse.js:155:35)
    at PanelCollapse (C:\Program Files\poi\resources\app.asar\node_modules\react-bootstrap\lib\PanelCollapse.js:66:29)
    at div
    at Panel (C:\Program Files\poi\resources\app.asar\node_modules\react-bootstrap\lib\Panel.js:100:35)
    at UncontrolledComponent (C:\Program Files\poi\resources\app.asar\node_modules\uncontrollable\cjs\uncontrollable.js:47:37)
    at div
    at OverviewArea (c:\users\Jzh\AppData\Roaming\poi\plugins\node_modules\poi-plugin-battle-detail\views\overview-area.js:33:1)
    at div
    at div
    at Transition (C:\Program Files\poi\resources\app.asar\node_modules\react-transition-group\Transition.js:133:30)
    at Fade (C:\Program Files\poi\resources\app.asar\node_modules\react-bootstrap\lib\Fade.js:100:29)
    at TabPane (C:\Program Files\poi\resources\app.asar\node_modules\react-bootstrap\lib\TabPane.js:131:30)
    at Tab (C:\Program Files\poi\resources\app.asar\node_modules\react-bootstrap\lib\Tab.js:38:29)
    at div
    at TabContent (C:\Program Files\poi\resources\app.asar\node_modules\react-bootstrap\lib\TabContent.js:78:30)
    at div
    at TabContainer (C:\Program Files\poi\resources\app.asar\node_modules\react-bootstrap\lib\TabContainer.js:88:29)
    at Tabs (C:\Program Files\poi\resources\app.asar\node_modules\react-bootstrap\lib\Tabs.js:107:29)
    at UncontrolledComponent (C:\Program Files\poi\resources\app.asar\node_modules\uncontrollable\cjs\uncontrollable.js:47:37)
    at div
    at MainAreaImpl (c:\users\Jzh\AppData\Roaming\poi\plugins\node_modules\poi-plugin-battle-detail\views\index.js:104:20)
    at ConnectFunction (C:\Program Files\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at PluginWrap (C:\Program Files\poi\resources\app.asar\views\components\tab-area\plugin-wrapper.js:24:5)
    at I18nextWithTranslation (C:\Program Files\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\withTranslation.js:32:31)
    at div
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at ae (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:13451)
    at PluginWindowWrap (C:\Program Files\poi\resources\app.asar\views\components\tab-area\plugin-window-wrapper.js:104:5)
    at div
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at t (C:\Program Files\poi\resources\app.asar\node_modules\react-resizable-area\dist\index.js:1:5417)
    at div
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at ControlledTabArea (C:\Program Files\poi\resources\app.asar\views\components\tab-area\index.js:248:5)
    at ConnectFunction (C:\Program Files\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at I18nextWithTranslation (C:\Program Files\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\withTranslation.js:32:31)
    at poi-nav-tabs
    at poi-nav
    at div
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at PoiApp (C:\Program Files\poi\resources\app.asar\views\poi-app.js:89:5)
    at ConnectFunction (C:\Program Files\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at poi-main
    at ResizeSensor (C:\Program Files\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\resize-sensor\resizeSensor.js:30:47)
    at exports.ThemeProvider (C:\Program Files\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:25072)
    at Poi (C:\Program Files\poi\resources\app.asar\views\app.js:76:5)
    at ConnectFunction (C:\Program Files\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at Provider (C:\Program Files\poi\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:21:20)
    at I18nextProvider (C:\Program Files\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\I18nextProvider.js:13:19)

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

**Comment by sslantis** [comment]
插件已恢复正常可用，原因不明

**Comment by lacafjh** [comment]
`v10.8.0` 出现同样问题，同时发生的异常情况还有航海日志插件的历史纪录全部不显示变为空白。航海日志版本为 `8.1.2`，战斗记录插件版本为 `5.12.0`。以下是打开战斗记录插件的报错信息：

```
TypeError: Cannot read properties of undefined (reading '3')
    at ItemView.render (%AppData%\poi\plugins\node_modules\poi-plugin-battle-detail\views\overview-area.js:261:32)
    at qi (%ProgramFiles%\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:187:188)
    at pi (%ProgramFiles%\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:186:173)
    at ck (%ProgramFiles%\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:269:427)
    at bk (%ProgramFiles%\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:250:347)
    at ak (%ProgramFiles%\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:250:278)
    at Tj (%ProgramFiles%\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:250:138)
    at Lj (%ProgramFiles%\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:243:163)
    at %ProgramFiles%\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:123:115
    at exports.unstable_runWithPriority (%ProgramFiles%\poi\resources\app.asar\node_modules\scheduler\cjs\scheduler.production.min.js:18:343)
    at gg (%ProgramFiles%\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:325)
    at jg (%ProgramFiles%\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:123:61)
    at ig (%ProgramFiles%\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:428)
    at Jg (%ProgramFiles%\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:237:203)
    at Object.enqueueSetState (%ProgramFiles%\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:133:211)
    at PluginWindowWrap.C.setState (%ProgramFiles%\poi\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:369)
    at %ProgramFiles%\poi\resources\app.asar\views\components\tab-area\plugin-window-wrapper.js:184:14

    at ItemView (%AppData%\poi\plugins\node_modules\poi-plugin-battle-detail\views\overview-area.js:238:1)
    at div
    at Col (%ProgramFiles%\poi\resources\app.asar\node_modules\react-bootstrap\lib\Col.js:219:29)
    at div
    at Grid (%ProgramFiles%\poi\resources\app.asar\node_modules\react-bootstrap\lib\Grid.js:48:29)
    at ShipView (%AppData%\poi\plugins\node_modules\poi-plugin-battle-detail\views\overview-area.js:115:1)
    at div
    at Col (%ProgramFiles%\poi\resources\app.asar\node_modules\react-bootstrap\lib\Col.js:219:29)
    at div
    at Row (%ProgramFiles%\poi\resources\app.asar\node_modules\react-bootstrap\lib\Row.js:35:29)
    at div
    at Grid (%ProgramFiles%\poi\resources\app.asar\node_modules\react-bootstrap\lib\Grid.js:48:29)
    at div
    at FleetView (%AppData%\poi\plugins\node_modules\poi-plugin-battle-detail\views\overview-area.js:74:1)
    at div
    at div
    at PanelBody (%ProgramFiles%\poi\resources\app.asar\node_modules\react-bootstrap\lib\PanelBody.js:51:29)
    at div
    at Transition (%ProgramFiles%\poi\resources\app.asar\node_modules\react-transition-group\Transition.js:133:30)
    at Collapse (%ProgramFiles%\poi\resources\app.asar\node_modules\react-bootstrap\lib\Collapse.js:155:35)
    at PanelCollapse (%ProgramFiles%\poi\resources\app.asar\node_modules\react-bootstrap\lib\PanelCollapse.js:66:29)
    at div
    at Panel (%ProgramFiles%\poi\resources\app.asar\node_modules\react-bootstrap\lib\Panel.js:100:35)
    at UncontrolledComponent (%ProgramFiles%\poi\resources\app.asar\node_modules\uncontrollable\cjs\uncontrollable.js:47:37)
    at div
    at OverviewArea (%AppData%\poi\plugins\node_modules\poi-plugin-battle-detail\views\overview-area.js:33:1)
    at div
    at div
    at Transition (%ProgramFiles%\poi\resources\app.asar\node_modules\react-transition-group\Transition.js:133:30)
    at Fade (%ProgramFiles%\poi\resources\app.asar\node_modules\react-bootstrap\lib\Fade.js:100:29)
    at TabPane (%ProgramFiles%\poi\resources\app.asar\node_modules\react-bootstrap\lib\TabPane.js:131:30)
    at Tab (%ProgramFiles%\poi\resources\app.asar\node_modules\react-bootstrap\lib\Tab.js:38:29)
    at div
    at TabContent (%ProgramFiles%\poi\resources\app.asar\node_modules\react-bootstrap\lib\TabContent.js:78:30)
    at div
    at TabContainer (%ProgramFiles%\poi\resources\app.asar\node_modules\react-bootstrap\lib\TabContainer.js:88:29)
    at Tabs (%ProgramFiles%\poi\resources\app.asar\node_modules\react-bootstrap\lib\Tabs.js:107:29)
    at UncontrolledComponent (%ProgramFiles%\poi\resources\app.asar\node_modules\uncontrollable\cjs\uncontrollable.js:47:37)
    at div
    at MainAreaImpl (%AppData%\poi\plugins\node_modules\poi-plugin-battle-detail\views\index.js:104:20)
    at ConnectFunction (%ProgramFiles%\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at PluginWrap (%ProgramFiles%\poi\resources\app.asar\views\components\tab-area\plugin-wrapper.js:24:5)
    at I18nextWithTranslation (%ProgramFiles%\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\withTranslation.js:32:31)
    at div
    at I (%ProgramFiles%\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at ae (%ProgramFiles%\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:13451)
    at PluginWindowWrap (%ProgramFiles%\poi\resources\app.asar\views\components\tab-area\plugin-window-wrapper.js:104:5)
    at div
    at I (%ProgramFiles%\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at t (%ProgramFiles%\poi\resources\app.asar\node_modules\react-resizable-area\dist\index.js:1:5417)
    at div
    at I (%ProgramFiles%\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at ControlledTabArea (%ProgramFiles%\poi\resources\app.asar\views\components\tab-area\index.js:248:5)
    at ConnectFunction (%ProgramFiles%\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at I18nextWithTranslation (%ProgramFiles%\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\withTranslation.js:32:31)
    at poi-nav-tabs
    at poi-nav
    at div
    at I (%ProgramFiles%\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (%ProgramFiles%\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at PoiApp (%ProgramFiles%\poi\resources\app.asar\views\poi-app.js:89:5)
    at ConnectFunction (%ProgramFiles%\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at poi-main
    at ResizeSensor (%ProgramFiles%\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\resize-sensor\resizeSensor.js:30:47)
    at exports.ThemeProvider (%ProgramFiles%\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:25072)
    at Poi (%ProgramFiles%\poi\resources\app.asar\views\app.js:76:5)
    at ConnectFunction (%ProgramFiles%\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at Provider (%ProgramFiles%\poi\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:21:20)
    at I18nextProvider (%ProgramFiles%\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\I18nextProvider.js:13:19)
```
