### ISSUE TITLE
插件 任务信息2 崩溃

### ISSUE THREAD

**Issue by er-fangNANO** [poooi/poi#2437]
**poi 版本 / poi version:10.8.0
**操作系统 / OS:win10 21H2  19044.1586

**插件名和版本 / Plugin name & version:任务信息2   0.6.4

**你遇到了什么样的问题 / The problem you've met:插件崩溃

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

![image](https://user-images.githubusercontent.com/102881218/161402240-532f1f6a-ca44-4f3c-ae65-1c761d5a9e0f.png)

Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Jg (F:\123\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:237:48)
    at Object.enqueueSetState (F:\123\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:133:211)
    at Text.C.setState (F:\123\poi\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:369)
    at Text.update (F:\123\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\text\text.js:60:14)
    at Text.componentDidUpdate (F:\123\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\text\text.js:40:14)
    at Yi (F:\123\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:219:502)
    at dk (F:\123\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:259:160)
    at exports.unstable_runWithPriority (F:\123\poi\resources\app.asar\node_modules\scheduler\cjs\scheduler.production.min.js:18:343)
    at gg (F:\123\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:325)
    at Uj (F:\123\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:252:279)
    at Lj (F:\123\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:243:371)
    at F:\123\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:123:115
    at exports.unstable_runWithPriority (F:\123\poi\resources\app.asar\node_modules\scheduler\cjs\scheduler.production.min.js:18:343)
    at gg (F:\123\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:325)
    at jg (F:\123\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:123:61)
    at ig (F:\123\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:428)
    at Jg (F:\123\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:237:203)
    at Oh (F:\123\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:170:408)
    at listener (C:\Users\qq104\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\poi\hooks.ts:43:32)
    at handleChange (C:\Users\qq104\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\poi\store.ts:26:7)
    at dispatch (F:\123\poi\resources\app.asar\node_modules\redux\lib\redux.js:305:7)
    at F:\123\poi\resources\app.asar\node_modules\redux-thunk\lib\index.js:27:16
    at parseResponses (F:\123\poi\resources\app.asar\views\env-parts\data-resolver.js:101:5)
    at resolveResponses (F:\123\poi\resources\app.asar\views\env-parts\data-resolver.js:126:7)
    at handleProxyGameOnResponse (F:\123\poi\resources\app.asar\views\env-parts\data-resolver.js:141:7)
    at CallbacksRegistry.apply (F:\123\poi\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\callbacks-registry.js:54:29)
    at F:\123\poi\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:345:23
    at EventEmitter.<anonymous> (F:\123\poi\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:327:13)
    at EventEmitter.emit (node:events:394:28)
    at Object.onMessage (node:electron/js2c/renderer_init:73:1017)

    at Text (F:\123\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\text\text.js:28:47)
    at div
    at I (F:\123\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at Card (F:\123\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\card\card.js:28:42)
    at I (F:\123\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at LargeQuestCard (C:\Users\qq104\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\components\QuestCard\index.tsx:30:3)
    at QuestCard (C:\Users\qq104\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\components\QuestCard\index.tsx:64:25)
    at div
    at CellMeasurer (F:\123\poi\resources\app.asar\node_modules\react-virtualized\dist\commonjs\CellMeasurer\CellMeasurer.js:51:37)
    at div
    at div
    at Grid (F:\123\poi\resources\app.asar\node_modules\react-virtualized\dist\commonjs\Grid\Grid.js:93:37)
    at List (F:\123\poi\resources\app.asar\node_modules\react-virtualized\dist\commonjs\List\List.js:50:37)
    at div
    at AutoSizer (F:\123\poi\resources\app.asar\node_modules\react-virtualized\dist\commonjs\AutoSizer\AutoSizer.js:48:37)
    at div
    at I (F:\123\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at QuestList (C:\Users\qq104\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\components\QuestList.tsx:103:3)
    at Main (C:\Users\qq104\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\App.tsx:39:39)
    at div
    at I (F:\123\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at StoreProvider (C:\Users\qq104\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\store\store.tsx:73:3)
    at App
    at div
    at Card (F:\123\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\card\card.js:28:42)
    at div
    at I (F:\123\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at PluginWrap (F:\123\poi\resources\app.asar\views\components\tab-area\plugin-wrapper.js:24:5)
    at I18nextWithTranslation (F:\123\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\withTranslation.js:32:31)
    at div
    at I (F:\123\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (F:\123\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at TabContentsUnion (F:\123\poi\resources\app.asar\views\components\tab-area\tab-contents-union.js:50:5)
    at ConnectFunction (F:\123\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at forwardConnectRef
    at div
    at I (F:\123\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (F:\123\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at ControlledTabArea (F:\123\poi\resources\app.asar\views\components\tab-area\index.js:248:5)
    at ConnectFunction (F:\123\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at I18nextWithTranslation (F:\123\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\withTranslation.js:32:31)
    at poi-nav-tabs
    at poi-nav
    at div
    at I (F:\123\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (F:\123\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at PoiApp (F:\123\poi\resources\app.asar\views\poi-app.js:89:5)
    at ConnectFunction (F:\123\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at poi-main
    at ResizeSensor (F:\123\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\resize-sensor\resizeSensor.js:30:47)
    at exports.ThemeProvider (F:\123\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:25072)
    at Poi (F:\123\poi\resources\app.asar\views\app.js:76:5)
    at ConnectFunction (F:\123\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at Provider (F:\123\poi\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:21:20)
    at I18nextProvider (F:\123\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\I18nextProvider.js:13:19)

**Comment by lawvs** [comment]
请问插件是突然崩溃还是在进行点击操作之后崩溃的呢？有办法稳定复现吗？

**Comment by er-fangNANO** [comment]
目前没有,  出现过三次 。在提交任务 、启动POI 、搜索任务详情各发生了一次，之后没有出现过崩溃

**Comment by lawvs** [comment]
尝试修了一下，发布了 v0.6.5，可以再观察观察
