### ISSUE TITLE
任务信息2崩溃

### ISSUE THREAD

**Issue by LilithLasdier** [poooi/poi#2438]
**poi 版本 / poi version:**

**操作系统 / OS:**

**插件名和版本 / Plugin name & version:**

**你遇到了什么样的问题 / The problem you've met:**

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:**

错误代码：
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Jg (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:237:48)
    at Object.enqueueSetState (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:133:211)
    at Text.C.setState (D:\poi\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:369)
    at Text.update (D:\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\text\text.js:60:14)
    at Text.componentDidUpdate (D:\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\text\text.js:40:14)
    at Yi (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:219:502)
    at dk (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:259:160)
    at exports.unstable_runWithPriority (D:\poi\resources\app.asar\node_modules\scheduler\cjs\scheduler.production.min.js:18:343)
    at gg (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:325)
    at Uj (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:252:279)
    at Lj (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:243:371)
    at D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:123:115
    at exports.unstable_runWithPriority (D:\poi\resources\app.asar\node_modules\scheduler\cjs\scheduler.production.min.js:18:343)
    at gg (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:325)
    at jg (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:123:61)
    at ig (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:428)
    at Jg (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:237:203)
    at Oh (D:\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:170:408)
    at listener (C:\Users\华为\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\poi\hooks.ts:43:32)
    at handleChange (C:\Users\华为\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\poi\store.ts:26:7)
    at dispatch (D:\poi\resources\app.asar\node_modules\redux\lib\redux.js:305:7)
    at D:\poi\resources\app.asar\node_modules\redux-thunk\lib\index.js:27:16
    at parseResponses (D:\poi\resources\app.asar\views\env-parts\data-resolver.js:101:5)
    at resolveResponses (D:\poi\resources\app.asar\views\env-parts\data-resolver.js:126:7)
    at handleProxyGameOnResponse (D:\poi\resources\app.asar\views\env-parts\data-resolver.js:141:7)
    at CallbacksRegistry.apply (D:\poi\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\callbacks-registry.js:54:29)
    at D:\poi\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:345:23
    at EventEmitter.<anonymous> (D:\poi\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:327:13)
    at EventEmitter.emit (node:events:394:28)
    at Object.onMessage (node:electron/js2c/renderer_init:73:1017)

    at Text (D:\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\text\text.js:28:47)
    at div
    at I (D:\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at Card (D:\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\card\card.js:28:42)
    at I (D:\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at LargeQuestCard (C:\Users\华为\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\components\QuestCard\index.tsx:30:3)
    at QuestCard (C:\Users\华为\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\components\QuestCard\index.tsx:64:25)
    at div
    at CellMeasurer (D:\poi\resources\app.asar\node_modules\react-virtualized\dist\commonjs\CellMeasurer\CellMeasurer.js:51:37)
    at div
    at div
    at Grid (D:\poi\resources\app.asar\node_modules\react-virtualized\dist\commonjs\Grid\Grid.js:93:37)
    at List (D:\poi\resources\app.asar\node_modules\react-virtualized\dist\commonjs\List\List.js:50:37)
    at div
    at AutoSizer (D:\poi\resources\app.asar\node_modules\react-virtualized\dist\commonjs\AutoSizer\AutoSizer.js:48:37)
    at div
    at I (D:\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at QuestList (C:\Users\华为\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\components\QuestList.tsx:103:3)
    at Main (C:\Users\华为\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\App.tsx:39:39)
    at div
    at I (D:\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at StoreProvider (C:\Users\华为\AppData\Roaming\poi\plugins\node_modules\poi-plugin-quest-info-2\src\store\store.tsx:73:3)
    at App
    at div
    at Card (D:\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\card\card.js:28:42)
    at div
    at I (D:\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at PluginWrap (D:\poi\resources\app.asar\views\components\tab-area\plugin-wrapper.js:24:5)
    at I18nextWithTranslation (D:\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\withTranslation.js:32:31)
    at div
    at I (D:\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (D:\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at TabContentsUnion (D:\poi\resources\app.asar\views\components\tab-area\tab-contents-union.js:50:5)
    at ConnectFunction (D:\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at forwardConnectRef
    at div
    at I (D:\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at t (D:\poi\resources\app.asar\node_modules\react-resizable-area\dist\index.js:1:5417)
    at div
    at I (D:\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at ControlledTabArea (D:\poi\resources\app.asar\views\components\tab-area\index.js:248:5)
    at ConnectFunction (D:\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at I18nextWithTranslation (D:\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\withTranslation.js:32:31)
    at poi-nav-tabs
    at poi-nav
    at div
    at I (D:\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (D:\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at PoiApp (D:\poi\resources\app.asar\views\poi-app.js:89:5)
    at ConnectFunction (D:\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at poi-main
    at ResizeSensor (D:\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\resize-sensor\resizeSensor.js:30:47)
    at exports.ThemeProvider (D:\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:25072)
    at Poi (D:\poi\resources\app.asar\views\app.js:76:5)
    at ConnectFunction (D:\poi\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at Provider (D:\poi\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:21:20)
    at I18nextProvider (D:\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\I18nextProvider.js:13:19)

**Comment by lawvs** [comment]
之前已经有人汇报过了，可以在 https://github.com/poooi/poi/issues/2409 跟进
