### ISSUE TITLE
为什么会Javascript报错

### ISSUE THREAD

**Issue by meisterpanzer** [poooi/poi#245]
Error 
A JavaScript error Occured in the browser process 
Uncaught Exception: 
Error: Cannot find module ‘path-extra’ 
at Function Module. resolveFilename (module.js:334:15） 
at Function Module. load (module.js:284:25) 
at Module.require (module.js:363:17） 
at require (module.js:382:17）
at Object. (C:\Users\xxxxx 
\Documents\poi-v3.2.1-win32-x64\resources\app\app.coffee:3:8) 
at Object. (C:\Users\xxxxx 
\Documents\poi-v3.2.1-win32-x64\resources\app\app.coffee:1:1) 
at Module. compile (module.js:428:26) 
at Object.loadFile (C:\Users\xxxxx 
\Documents\poi-v3.2.1-win32-x64\resources\app\node_modules\coffee-script\l...:19). 
at Module.load (C:\Users\xxxxx 
\Documents\poi-v3.2.1-win32-x64\resources\app\node_modules\coffee-script\l...:36). 
at Function.Module._load (module.js:308:12 ） 
at Module.require (module.js:363:17） 
at Function.Module._load (module.js:308:12 ） 
at Module.require (module.js:363:17） 
at require (module.js:382:17 )
at Object.<anonymous> (C:\Users\xxxxx 
\Documents\poi-v3.2.1-win32-x64\resources\app\index.js:2:1) 
at Module. compile (module.js:428:26) 
at Object.Module. extensions..JS (module.js:446:10)
at Module.load (module.js:353:32) 
at Function Module. load (module.js:308:12 ） 
at Object.<anonymous> (C:\Users\xxxxx 
\Documents\poi-v3.2.1-win32-x64\resources\atom.asar\browser\lib\init.js:106:10)
at Object.<anonymous> (C:\Users\xxxxx 
\Documents\poi-v3.2.1-win32-x64\resources\atom.asar\browser\lib\init.js:108:4) 
at Module. compile (module.js:428:26) 
at Object.Module. extensions..JS (module.js:446:10)
at Module.load (module.js:353:32) 
at Function Module. load (module.js:308:12) 
at Function Module.runMain (module.js:469:10) 
at startup (node.js:125:18） 
at node.js:960:3

**Comment by yukixz** [comment]
xxxxx 是中文？

**Comment by magicae** [comment]
中文不能出现在路径里
