### ISSUE TITLE
战果计算器变成了乌龟

### ISSUE THREAD

**Issue by pineapple94666** [poooi/poi#2470]
**poi 版本 / poi version:10.8.0

**操作系统 / OS:win11

**插件名和版本 / Plugin name & version:战果计算 5.1.6

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Vg (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:280:177)
    at A (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:143:356)
    at x (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:146:132)
    at C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:150:224
    at fi (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:176:171)
    at ck (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:271:134)
    at bk (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:250:347)
    at ak (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:250:278)
    at Tj (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:250:138)
    at Lj (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:243:163)
    at C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:123:115
    at exports.unstable_runWithPriority (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\scheduler\cjs\scheduler.production.min.js:18:343)
    at gg (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:325)
    at jg (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:123:61)
    at ig (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:122:428)
    at Wj (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:244:190)
    at Object.notify (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:21:7)
    at Object.notifyNestedSubs (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:92:15)
    at handleChangeWrapper (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:97:20)
    at dispatch (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\redux\lib\redux.js:305:7)
    at C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\redux-thunk\lib\index.js:27:16
    at PluginManager.readPlugins (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\views\services\plugin-manager\index.js:184:5)
    at PluginManager.getPlugins (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\views\services\plugin-manager\index.js:255:14)
    at PluginManager.initialize (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\views\services\plugin-manager\index.js:137:5)

    at div
    at div
    at FormGroup (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\forms\formGroup.js:28:42)
    at div
    at I (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at Calculator (C:\Users\shenjichen\AppData\Roaming\poi\plugins\node_modules\poi-plugin-senka-calc\views\calculator.js:44:29)
    at div
    at I (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at reactClass
    at div
    at Card (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\card\card.js:28:42)
    at div
    at I (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at PluginWrap (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\views\components\tab-area\plugin-wrapper.js:24:5)
    at I18nextWithTranslation (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-i18next\dist\commonjs\withTranslation.js:32:31)
    at div
    at I (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at TabContentsUnion (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\views\components\tab-area\tab-contents-union.js:50:5)
    at ConnectFunction (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at forwardConnectRef
    at div
    at I (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at t (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-resizable-area\dist\index.js:1:5417)
    at div
    at I (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at ControlledTabArea (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\views\components\tab-area\index.js:248:5)
    at ConnectFunction (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at I18nextWithTranslation (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-i18next\dist\commonjs\withTranslation.js:32:31)
    at poi-nav-tabs
    at poi-nav
    at div
    at I (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at PoiApp (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\views\poi-app.js:89:5)
    at ConnectFunction (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at poi-main
    at ResizeSensor (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\resize-sensor\resizeSensor.js:30:47)
    at exports.ThemeProvider (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:25072)
    at Poi (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\views\app.js:76:5)
    at ConnectFunction (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:235:41)
    at Provider (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:21:20)
    at I18nextProvider (C:\Users\shenjichen\Desktop\poi-10.8.0-win\resources\app.asar\node_modules\react-i18next\dist\commonjs\I18nextProvider.js:13:19)
<!--

**Comment by KochiyaOcean** [comment]
更新到 10.9.0

2022年9月25日(日) 19:42 pineapple94666 ***@***.***>:
