### ISSUE TITLE
士气速查变成了乌龟

### ISSUE THREAD

**Issue by Ice-Cirno** [poooi/poi#2475]
**poi 版本 / poi version:** 10.9.2 and 10.6.0

**操作系统 / OS:** Windows 10 21H2

**插件名和版本 / Plugin name & version:** 士气速查 0.8.3

**你遇到了什么样的问题 / The problem you've met:** 士气速查变成了乌龟

**有没有重现的方法，或者与问题相关的任何信息 / How to reproduce, or any information that might be related:** 打开插件显示士气速查变成了乌龟
```
TypeError: Cannot read properties of undefined (reading 'map')
    at C:\Users\IceCoffee\AppData\Roaming\poi\plugins\node_modules\poi-plugin-mo2\ui\fleet-morale-list\selectors.es:24:89
    at fillInfo (C:\Users\IceCoffee\AppData\Roaming\poi\plugins\node_modules\poi-plugin-mo2\ui\fleet-morale-list\selectors.es:126:21)
    at Array.map (<anonymous>:null:null)
    at C:\Users\IceCoffee\AppData\Roaming\poi\plugins\node_modules\poi-plugin-mo2\ui\fleet-morale-list\selectors.es:138:40
    at recomputationWrapper (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\reselect\lib\index.js:87:25)
    at memoized (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\reselect\lib\defaultMemoize.js:135:20)
    at dependenciesChecker (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\reselect\lib\index.js:101:40)
    at Function.memoized [as mapToProps] (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\reselect\lib\defaultMemoize.js:135:20)
    at mapToPropsProxy (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-redux\lib\connect\wrapMapToProps.js:59:46)
    at Function.detectFactoryAndVerify (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-redux\lib\connect\wrapMapToProps.js:68:19)
    at mapToPropsProxy (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-redux\lib\connect\wrapMapToProps.js:59:46)
    at handleFirstCall (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-redux\lib\connect\selectorFactory.js:30:18)
    at pureFinalPropsSelector (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-redux\lib\connect\selectorFactory.js:71:81)
    at selector (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-redux\lib\components\connect.js:340:18)
    at Object.useSyncExternalStore (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:185:368)
    at exports.useSyncExternalStore (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react\cjs\react.production.min.js:25:469)
    at ConnectFunction (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-redux\lib\components\connect.js:364:28)
    at Xh (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:167:137)
    at dj (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:197:258)
    at cj (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:195:204)
    at aj (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:194:176)
    at Wk (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:297:71)
    at Vk (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:280:389)
    at Uk (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:280:320)
    at Jk (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:280:180)
    at Fk (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:273:245)
    at jg (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:127:105)
    at mh (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:266:390)
    at Object.enqueueSetState (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:145:225)
    at PluginWindowWrap.E.setState (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:237)
    at C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\views\components\tab-area\plugin-window-wrapper.js:184:14


    at ConnectFunction (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:87)
    at div
    at TabPane (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-bootstrap\lib\TabPane.js:131:30)
    at Tab (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-bootstrap\lib\Tab.js:38:29)
    at div
    at TabContent (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-bootstrap\lib\TabContent.js:78:30)
    at div
    at TabContainer (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-bootstrap\lib\TabContainer.js:88:29)
    at Tabs (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-bootstrap\lib\Tabs.js:107:29)
    at UncontrolledComponent (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\uncontrollable\lib\cjs\uncontrollable.js:49:37)
    at div
    at MoraleMonitorImpl (C:\Users\IceCoffee\AppData\Roaming\poi\plugins\node_modules\poi-plugin-mo2\ui\index.es:36:5)
    at ConnectFunction (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:87)
    at PluginWrap (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\views\components\tab-area\plugin-wrapper.js:24:5)
    at I18nextWithTranslation (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\withTranslation.js:32:31)
    at div
    at I (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at ae (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:13451)
    at PluginWindowWrap (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\views\components\tab-area\plugin-window-wrapper.js:104:5)
    at div
    at I (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at t (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-resizable-area\dist\index.js:1:5417)
    at div
    at I (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at ControlledTabArea (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\views\components\tab-area\index.js:248:5)
    at ConnectFunction (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:87)
    at I18nextWithTranslation (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\withTranslation.js:32:31)
    at poi-nav-tabs
    at poi-nav
    at div
    at I (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at div
    at I (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19375)
    at PoiApp (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\views\poi-app.js:89:5)
    at ConnectFunction (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:87)
    at poi-main
    at ResizeSensor (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\@blueprintjs\core\lib\cjs\components\resize-sensor\resizeSensor.js:29:47)
    at exports.ThemeProvider (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:25072)
    at Poi (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\views\app.js:76:5)
    at ConnectFunction (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:87)
    at Provider (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:19:3)
    at I18nextProvider (C:\Users\IceCoffee\AppData\Local\Programs\poi\resources\app.asar\node_modules\react-i18next\dist\commonjs\I18nextProvider.js:13:19)
```

一直用的10.6.0，今天发远征发现插件挂了。
尝试重启插件，未解决；
尝试重装插件，未解决；
搜索到了issue #1793，尝试删除json后重启插件，未解决；
更新至10.9.2，未解决；
更新后重启、重装插件，均未解决。

**Comment by Ice-Cirno** [comment]
又出现这个问题了，持续乌龟好多天了QAQ
