### ISSUE TITLE
主程序插件载入行为异常

### ISSUE THREAD

**Issue by ilufang** [poooi/poi#275]
**最近发现海域血量和数据汇报插件不能正常加载.**

* 插件源代码应该没有问题: 经过多次删除插件目录内容并重新`git submodule init`,`git submodule update`后仍然无法显示, 设置->扩展程序中显示正常
* 尝试过修改插件源代码追踪, 插件的index文件被执行, 但`module.exports.reactClass`内容都没有被执行
* cjsx全部被转化为js且Console中没有相关错误
* 曾经修改插件代码时发生过插件间相互影响, 导致原来无法打开的插件(map-hp, 未被编辑)被载入而原来可以打开的插件(prophet, 被编辑)无法载入 (仅发生过一次), 全部重新下载代码后恢复原样 (prophet被载入, map-hp无法载入)

![插件在设置中被显示且已开启但不显示在插件列表中无法打开](https://cloud.githubusercontent.com/assets/6183259/9379582/fc34caf6-475c-11e5-8c65-497e2ccc0e3e.png)

没有修改过主程序除了index.html中webview的src和几个css文件以外的任何内容, 插件设置改变后均进行了重新启动, 以上截图亦是重启electron后

我是通过git安装, 独立electron运行的, 系统MacOS 10.9, 最近的几个版本都遇到过. 麻烦检查一下相关代码, 希望能获得一些关于插件载入机制的线索(毕竟这几个插件也会用到) 谢谢.

**Comment by magicae** [comment]
数据汇报没有UI本来就是隐藏的 海域血量应该是不小心被你点掉了 重开下应该就有海域血量插件了吧

**Comment by ilufang** [comment]
感谢帮助! 后来查了一下应该是electron在MacOS 10.9下的问题
在cjsx文件中是第3行`request = Promise.promisifyAll require('request')`中require部分, 抛出错误:
```
Error: UnknownSystemError: Unknown system error, uv_pipe_open
  at Error (native)
  at new Socket (net.js:127:18)
  at createWritableStdioStream (node.js:602:18)
  at process.stdout (node.js:628:16)
  at console.js:92:37
  at NativeModule.compile (node.js:947:5)
  at Function.NativeModule.require (node.js:895:18)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/ilufang/Github/poi/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/jsonpointer/jsonpointer.js:1:77)
  at Module._compile (module.js:428:26)
  at Object.Module._extensions..js (module.js:446:10)
  at Module.load (/Users/ilufang/Github/poi/node_modules/coffee-react/lib/register.js:44:34)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/ilufang/Github/poi/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/index.js:3:19)
  at Module._compile (module.js:428:26)
  at Object.Module._extensions..js (module.js:446:10)
  at Module.load (/Users/ilufang/Github/poi/node_modules/coffee-react/lib/register.js:44:34)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/ilufang/Github/poi/node_modules/request/node_modules/har-validator/lib/index.js:5:17)
  at Module._compile (module.js:428:26)
  at Object.Module._extensions..js (module.js:446:10)
  at Module.load (/Users/ilufang/Github/poi/node_modules/coffee-react/lib/register.js:44:34)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/ilufang/Github/poi/node_modules/request/lib/har.js:5:16)
  at Module._compile (module.js:428:26)
  at Object.Module._extensions..js (module.js:446:10)
  at Module.load (/Users/ilufang/Github/poi/node_modules/coffee-react/lib/register.js:44:34)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/ilufang/Github/poi/node_modules/request/request.js:22:11)
  at Module._compile (module.js:428:26)
  at Object.Module._extensions..js (module.js:446:10)
  at Module.load (/Users/ilufang/Github/poi/node_modules/coffee-react/lib/register.js:44:34)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/ilufang/Github/poi/node_modules/request/index.js:140:19)
  at Module._compile (module.js:428:26)
  at Object.Module._extensions..js (module.js:446:10)
  at Module.load (/Users/ilufang/Github/poi/node_modules/coffee-react/lib/register.js:44:34)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/ilufang/Github/poi/plugins/map-hp/index.cjsx:10:34)
  at Object.<anonymous> (/Users/ilufang/Github/poi/plugins/map-hp/index.cjsx:177:4)
  at Module._compile (module.js:428:26)
  at Object.loadFile (/Users/ilufang/Github/poi/node_modules/coffee-react/lib/register.js:15:17)
  at Module.load (/Users/ilufang/Github/poi/node_modules/coffee-react/lib/register.js:44:34)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at /Users/ilufang/Github/poi/views/single-tabarea.cjsx:23:16
  at Array.filter (native)
  at Object.<anonymous> (/Users/ilufang/Github/poi/views/single-tabarea.cjsx:20:21)
  at Object.<anonymous> (/Users/ilufang/Github/poi/views/single-tabarea.cjsx:212:4)
  at Module._compile (module.js:428:26)
  at Object.loadFile (/Users/ilufang/Github/poi/node_modules/coffee-react/lib/register.js:15:17)
  at Module.load (/Users/ilufang/Github/poi/node_modules/coffee-react/lib/register.js:44:34)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/ilufang/Github/poi/views/app.cjsx:165:96)
  at Object.<anonymous> (/Users/ilufang/Github/poi/views/app.cjsx:569:4)
  at Module._compile (module.js:428:26)
  at Object.loadFile (/Users/ilufang/Github/poi/node_modules/coffee-react/lib/register.js:15:17)
  at Module.load (/Users/ilufang/Github/poi/node_modules/coffee-react/lib/register.js:44:34)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at file:///Users/ilufang/Github/poi/index.html:42:5
```
[Electron uv_pipe_open on Mavericks](https://github.com/atom/electron/issues/1647)
[Works in atom-shell below 0.21](https://github.com/atom/atom/issues/6632#issuecomment-98819079)

如果可能, 希望做一个workaround (其实也无所谓, MacOS10.9用户也不多, electron估计也会修)
